### ISSUE TITLE
repo info error

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#105]
Im getting this error always, `There was an error retrieving the repository information, please check that the URL is correct and that the SSH key has been added` . can you tell me why this is happening.?

**Comment by REBELinBLUE** [comment]
OK I think I am going to have to try code commit out

**Comment by pavankumarkatakam** [comment]
First of all, tell me where this error firing off, so that i can also help you?

**Comment by REBELinBLUE** [comment]
it appears if DeployProject::updateRepoInfo() fails, basically if it can't clone the repository

**Comment by pavankumarkatakam** [comment]
I just dd the `$process->getErrorOutput()` in Deploy project, the output is 
    """
Permission denied (publickey).\r\n
fatal: Could not read from remote repository.\n
\n
Please make sure you have the correct access rights\n
and the repository exists.\n
"""

I think this can helpfull to you.

**Comment by pavankumarkatakam** [comment]
But when i do manually this command it success `git clone --quiet --branch master --depth 1 ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/laravel1`.

**Comment by REBELinBLUE** [comment]
Did you remember to add the SSH key to the remote repository?

**Comment by pavankumarkatakam** [comment]
In codecommit there is only IAM, and i have already added ssh to IAM user who has full control on codecommit repos.

**Comment by iflamed** [comment]
@pavankumarkatakam  You need to add the deployer's public ssh key to your repository so that deployer can ssh to your git server.

@REBELinBLUE  Could you add a QA tag to the issue?

**Comment by pavankumarkatakam** [comment]
I have already mentioned that im using codecommit by `aws`, there is no seetting for directly adding ssh to repository there is only IAM system. and i have done it.

**Comment by REBELinBLUE** [comment]
I am going to sign up to code commit at the weekend and have a look as I have no idea how it works

**Comment by pavankumarkatakam** [comment]
Hi @REBELinBLUE , have you seen the codecommit.

**Comment by REBELinBLUE** [comment]
Ah sorry I completely forgot as when I tried to sign up the activation SMS message wasn't arriving. I will try again tonight

**Comment by REBELinBLUE** [comment]
Still can't get the automated activation call, going to have to ring them tomorrow

**Comment by pavankumarkatakam** [comment]
Ok.

**Comment by pavankumarkatakam** [comment]
Can i give you a role in my aws account, you can know how the codecommit work

**Comment by pavankumarkatakam** [comment]
Atlast i figured out that, i want to add IAM sshid with the code commit git repo as  `ssh://<username>@<host>/path/to/repo`.

**Comment by pavankumarkatakam** [comment]
Now its working fine.

**Comment by REBELinBLUE** [comment]
Great to hear! Sorry I never got round to looking into it properly, work has been so manic lately :(
