### ISSUE TITLE
Production CSS is broken

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#111]
There seems to be an issue with the fonts when the CSS is compiled in production mode with

`$ gulp --production`

**Comment by REBELinBLUE** [comment]
Caused by this bug

http://stackoverflow.com/questions/32001352/gulp-sass-compiles-google-fonts-css-into-the-file-breaks-protocol-relative-link

**Comment by REBELinBLUE** [comment]
Fixing manually right now.... Hopefully fixed in elixir/gulp-minify-css soon

**Comment by JeffreyWay** [comment]
Duplicate. Closing.

**Comment by REBELinBLUE** [comment]
@JeffreyWay did you mean to comment here?

**Comment by JeffreyWay** [comment]
Yeah, sorry. Must have accidentally commented on the wrong thread.

**Comment by REBELinBLUE** [comment]
No worries :)
