### ISSUE TITLE
Access branch name in the commands

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#119]
For now, in commands there is only options for `{{ project_path }}`,`{{ release }}`,`{{ release_path }}`, but is there is any options to get the branch name that is specified when deploying.

**Comment by REBELinBLUE** [comment]
Hmm, no actually but it won't be hard to add, I'll do it this evening

**Comment by REBELinBLUE** [comment]
There you go, it is in `master` and `release`

**Comment by pavankumarkatakam** [comment]
Yes, its working. Once again thank you.

**Comment by REBELinBLUE** [comment]
👍
