### ISSUE TITLE
Refactor javascript

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#12]
Massively refactor the JS, clean up the duplication and sort out the Backbone.js code to not modify the DOM directly

- [ ] Cleanup duplication
- [ ] Sort out deployments and projects to use backbone
- [ ] Allow switching the socket.io code to pusher
- [ ] Change the timeline to update via sockets rather than ajax

**Comment by jbrooksuk** [comment]
What about using Vue.js? There isn't anything particularly crazy happening.

**Comment by REBELinBLUE** [comment]
Certainly worth looking at, Vue.js is not something I've ever looked at before (but then nor is backbone really)

**Comment by REBELinBLUE** [comment]
In progress https://github.com/REBELinBLUE/deployer/pull/248
