### ISSUE TITLE
socketio not working when changing from apache2 to ngnix.

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#120]
Hi @REBELinBLUE , i have just changed from apache2 to nginx, from then socketio not working and 

     Server error

A connection could not be established to the socket at http://deployer.app. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator

is showing, by some debugging im getting the console message that some event is recieved like server change logs, deployment logs but still the error in the web UI. is there any other settings to do when working with nginx.

**Comment by REBELinBLUE** [comment]
Are you running from master or release? If from master make sure you've done `npm install` and `gulp` as the CSS has changed, if release I must have forgotten to commit the compiled CSS so I will update it this afternoon

**Comment by pavankumarkatakam** [comment]
Actually im running from master, once again i update npm,bower and done gulp but the alert message is still visible.

**Comment by REBELinBLUE** [comment]
Hmm, weird. Does `public/build/css/app-*.css` have the following in, around line 40

```
    app.connection_error = false;

    app.listener.on('connect_error', function(error) {
        if (!app.connection_error) {
            $('#socket_offline').show();
        }

        app.connection_error = true;
    });

    app.listener.on('connect', function() {
        $('#socket_offline').hide();
        app.connection_error = false;
    });

    app.listener.on('reconnect', function() {
        $('#socket_offline').hide();
        app.connection_error = false;
    });```

**Comment by pavankumarkatakam** [comment]
Yes, it has. but in the `public/build/js/app.js` file.

**Comment by REBELinBLUE** [comment]
Oops, that is what I meant

**Comment by pavankumarkatakam** [comment]
When i examine in the network tab, socket.io connection is 404, here is the screen shot that routecollection error.
![socket_response](https://cloud.githubusercontent.com/assets/6078669/10640800/ee707d54-7833-11e5-8efe-a899f02dec38.png)

**Comment by pavankumarkatakam** [comment]
Its working now, i forget to change the socket_url in env when migrating the project.

**Comment by REBELinBLUE** [comment]
Ah!
