### ISSUE TITLE
Problems with BitBucket

### ISSUE THREAD

**Issue by rdehnhardt** [REBELinBLUE/deployer#124]
Not work for Bitbucket? I used in the repository git@bitbucket.org:org/repo.git, but I get the message "There was an error retrieving the repository information, please check that the URL is correct and that the SSH key has been added"

git clone git@bitbucket.org:org/repo.git in server works

**Comment by dancryer** [comment]
We use deployer with bitbucket without issue here. Is there anything coming up in the logs that may shed more light on what's going wrong?

Also, just to clarify, have you added the deployer project's SSH key to bitbucket's deploy keys section?

**Comment by rdehnhardt** [comment]
Was the key to deployer that had to be registered in bitbucket. I thought it was only the server key that would get the code should have the key! My mistake! Taking advantage, I could help in translation for pt-BR application.

**Comment by REBELinBLUE** [comment]
That would be awesome if you can.

Sorry, I should make it clearer in deployer (will fix it next week). If you use a private URL you need to add the key to the server, you can get around that by using the public URL

**Comment by skeith69** [comment]
I have the same problem I already added the key to my Bitbucket repository still no luck
