### ISSUE TITLE
websocket not updates the screen

### ISSUE THREAD

**Issue by Gabriellpweb** [REBELinBLUE/deployer#125]
I've installed on a AMI distro linux and the websocket is not working to update the interface with the broadcast job.

**Comment by REBELinBLUE** [comment]
Never heard of that distro, I will need to install it to take a look.

Do you have anything in the browser console? Also, in the web inspector is it opening a connection to the  correct address? (I assume it is otherwise you would get an error message)

**Comment by Gabriellpweb** [comment]
Hello, AMI is the distro linux of amazon and the console has no errors, just see a websocket connection with someframes but have no broadcast awnser. Everything works except the broadcastEvent via websocket to update the interface. I've checked the beanstalkd, redis, supervisor, cron, tested websocket connection but have no ideia about what is going on. 
Thanks for help.

**Comment by REBELinBLUE** [comment]
Ah I see, looks like you can only use it on EC2

Can you edit `.env` and set `APP_ENV` to `local` and `APP_DEBUG` to `true`

Delete the files in `storage/logs/` then restart supervisor and php5-fpm (assuming you are using nginx).

The run a deploy an paste the logs here

Thanks

**Comment by Gabriellpweb** [comment]
Helloo!!
I've changed the redis connection to my elasticcache on AWS in the .env file, but he still trying to connect on localhost. Take a look:


[2015-11-12 11:46:01] local.ERROR: exception 'Predis\Connection\ConnectionException' with message 'Connection refused [tcp://127.0.0.1:6379]' in /home/www/deployer/vendor/predis/predis/src/Connection/AbstractConnection.php:168
Stack trace:
#0 /home/www/deployer/vendor/predis/predis/src/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /home/www/deployer/vendor/predis/predis/src/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /home/www/deployer/vendor/predis/predis/src/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection->createResource()
#3 /home/www/deployer/vendor/predis/predis/src/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection->connect()
#4 /home/www/deployer/vendor/predis/predis/src/Connection/AbstractConnection.php(193): Predis\Connection\StreamConnection->connect()
#5 /home/www/deployer/vendor/predis/predis/src/Connection/StreamConnection.php(184): Predis\Connection\AbstractConnection->getResource()
#6 /home/www/deployer/vendor/predis/predis/src/Connection/StreamConnection.php(290): Predis\Connection\StreamConnection->write('*3\r\n$7\r\nPUBLISH...')
#7 /home/www/deployer/vendor/predis/predis/src/Connection/AbstractConnection.php(123): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command\PubSubPublish))
#8 /home/www/deployer/vendor/predis/predis/src/Client.php(326): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\PubSubPublish))
#9 /home/www/deployer/vendor/predis/predis/src/Client.php(310): Predis\Client->executeCommand(Object(Predis\Command\PubSubPublish))
#10 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/RedisBroadcaster.php(47): Predis\Client->__call('publish', Array)
#11 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/RedisBroadcaster.php(47): Predis\Client->publish('server', '{"event":"REBEL...')
#12 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(47): Illuminate\Broadcasting\Broadcasters\RedisBroadcaster->broadcast(Array, 'REBELinBLUE\\Dep...', Array)
#13 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Broadcasting\BroadcastEvent->fire(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#14 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(53): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#15 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\BeanstalkdJob->fire()
#16 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), '1', 0)
#17 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'deployer-defaul...', 0, '3', '1')
#18 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'deployer-defaul...', 0, '3', '1')
#19 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(103): Illuminate\Queue\Worker->daemon(NULL, 'deployer-defaul...', 0, 128, '3', '1')
#20 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'deployer-defaul...', 0, 128, true)
#21 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#22 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Container/Container.php(503): call_user_func_array(Array, Array)
#23 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#24 /home/www/deployer/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/www/deployer/vendor/symfony/console/Application.php(838): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/www/deployer/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/www/deployer/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/www/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/www/deployer/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 {main}

**Comment by REBELinBLUE** [comment]
Hmm. Did you remember to restart supervisor?

**Comment by Gabriellpweb** [comment]
i've tryed to reboot the instance and all servirces including nginx, php-fpm, beanstalkd, supervisor, redis elasticache. Tryied to clear all caches on artisan but nothing changes =(

**Comment by REBELinBLUE** [comment]
Can you paste `.env`

**Comment by REBELinBLUE** [comment]
@Gabriellpweb are you still having problems?

**Comment by Gabriellpweb** [comment]
Hello, sorry the idle. I give up and changed the EC2 distro to ubuntu and everything ok i guess rsrsrs.
Thanks for the help!

Rgs.

**Comment by REBELinBLUE** [comment]
Ah OK, thanks. I guess I'll have to try out AMI at some point
