### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by maveius** [REBELinBLUE/deployer#128]
@REBELinBLUE Could You help me? 

>A connection could not be established to the socket at http://deploy.local. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator.

**Comment by REBELinBLUE** [comment]
Yeah sorry this is an issue I still need to work out with Apache, nginx can proxy the connection where as Apache can't. In `.env` change the `SOCKET_URL` to include the port, so `http://deploy.local:6001`

**Comment by maveius** [comment]
Ok thx

**Comment by maveius** [comment]
still the same 

A connection could not be established to the socket at http://deploy.local:6001/. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator

**Comment by maveius** [comment]
A connection could not be established to the socket at http://deploy.local:6001. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator

**Comment by REBELinBLUE** [comment]
Do you have the node socket server running? See `examples/supervisor.conf` for an example supervisor configuration but you can just run `node socket.js` in the root to test it

**Comment by maveius** [comment]
ok it's new command witch is not in README.md ok. I'm trying.

**Comment by maveius** [comment]
ok its solved;

**Comment by REBELinBLUE** [comment]
It is in the supervisor config, unfortunately just running `node socket.js` won't keep the server running, as soon as you close your terminal session it will quit. You need to use something like supervisor to keep it running, and Laravel also recommends using supervisor to keep the queue worker running

**Comment by maveius** [comment]
But I see logout error, I can try to repair it but I thing is too many Laravel dependecies. I don't like that frameworks do somthing without my controll. But I understood that It is for "help". But when you have no control is not good. Maybe You know more than I Laravel concepts.

**Comment by REBELinBLUE** [comment]
It is for the laravel event broadcasting http://laravel.com/docs/5.1/events#broadcasting-events it uses a Redis pub/sub queue and then a socket.io socket server to subscribe to the channel and broadcast them out to client.

It is used when models change, i.e. updating the progress of deployments etc to get realtime updates broadcast straight to the browser instead of continually polling with AJAX

**Comment by maveius** [comment]
I have forgotten:

>[2015-11-14 22:52:50] production.ERROR: exception 'Pheanstalk\Exception\ConnectionException' with message 'Socket error 111: Connection refused (connecting to localhost:11300)' in /var/www/localhost/deployer/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45
Stack trace:
#0 /var/www/localhost/deployer/vendor/pda/pheanstalk/src/Connection.php(191): Pheanstalk\Socket\NativeSocket->__construct('localhost', 11300, 2, false)
#1 /var/www/localhost/deployer/vendor/pda/pheanstalk/src/Connection.php(98): Pheanstalk\Connection->_getSocket()
#2 /var/www/localhost/deployer/vendor/pda/pheanstalk/src/Pheanstalk.php(396): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\UseCommand))
#3 /var/www/localhost/deployer/vendor/pda/pheanstalk/src/Pheanstalk.php(347): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\UseCommand))
#4 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Queue/BeanstalkdQueue.php(71): Pheanstalk\Pheanstalk->useTube('deployer-defaul...')
#5 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Queue/BeanstalkdQueue.php(58): Illuminate\Queue\BeanstalkdQueue->pushRaw('{"job":"Illumin...', NULL)
#6 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(33): Illuminate\Queue\BeanstalkdQueue->push('Illuminate\\Broa...', Array, NULL)
#7 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(262): Illuminate\Queue\Queue->pushOn(NULL, 'Illuminate\\Broa...', Array)
#8 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(217): Illuminate\Events\Dispatcher->broadcastEvent(Object(REBELinBLUE\Deployer\Events\ModelChanged))
#9 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(337): Illuminate\Events\Dispatcher->fire(Object(REBELinBLUE\Deployer\Events\ModelChanged), Array, false)
#10 /var/www/localhost/deployer/app/Traits/BroadcastChanges.php(28): event(Object(REBELinBLUE\Deployer\Events\ModelChanged))
#11 [internal function]: REBELinBLUE\Deployer\User::REBELinBLUE\Deployer\Traits\{closure}(Object(REBELinBLUE\Deployer\User))
#12 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#13 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1694): Illuminate\Events\Dispatcher->fire('eloquent.update...', Object(REBELinBLUE\Deployer\User))
#14 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1574): Illuminate\Database\Eloquent\Model->fireModelEvent('updated', false)
#15 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1506): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#16 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(78): Illuminate\Database\Eloquent\Model->save()
#17 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(589): Illuminate\Auth\EloquentUserProvider->updateRememberToken(Object(REBELinBLUE\Deployer\User), 'GvpYJXa5KriXSi2...')
#18 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(550): Illuminate\Auth\Guard->refreshRememberToken(Object(REBELinBLUE\Deployer\User))
#19 [internal function]: Illuminate\Auth\Guard->logout()
#20 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Support/Manager.php(137): call_user_func_array(Array, Array)
#21 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): Illuminate\Support\Manager->__call('logout', Array)

**Comment by REBELinBLUE** [comment]
Sounds like you don't have beanstalkd running? If you'd rather use redis for the queue as well just change `QUEUE_DRIVER` in `.env` to `redis` (although I haven't tried it myself, the whole point of Laravel is so you can easily switch between drivers like that)

**Comment by maveius** [comment]
Tomoorow. Now I am tired.

**Comment by maveius** [comment]
I change QUEUE_DRIVER but still after press "sign out" button I have an laravel error like "whops ..."  after create or edit some objects in app I have returned error message but everything is saved.
After I configured all (projects, commands and other I have "whoops" error and everything I do I can logout and see login page.

I start to create Deploment module in [PHPCI](https://github.com/Block8/PHPCI) 

I didn't change to dev, but is very inconvenient app. 

>[2015-11-15 17:07:17] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function format() on null' in /var/www/localhost/deployer/app/Http/Controllers/DashboardController.php:69
Stack trace:
#0 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /var/www/localhost/deployer/app/Http/Controllers/DashboardController.php(39): REBELinBLUE\Deployer\Http\Controllers\DashboardController->buildTimelineData()
#4 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): REBELinBLUE\Deployer\Http\Controllers\DashboardController->index()
#5 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:256}()
#6 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction()
#7 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call()
#8 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#9 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#10 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#12 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then()
#13 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#14 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch()
#15 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher()
#16 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(712): Illuminate\Routing\Route->run()
#17 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#19 /var/www/localhost/deployer/vendor/graham-campbell/htmlmin/src/Http/Middleware/MinifyMiddleware.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): GrahamCampbell\HTMLMin\Http\Middleware\MinifyMiddleware->handle()
#21 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#22 /var/www/localhost/deployer/app/Http/Middleware/Authenticate.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): REBELinBLUE\Deployer\Http\Middleware\Authenticate->handle()
#24 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#25 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#27 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(714): Illuminate\Pipeline\Pipeline->then()
#28 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\Routing\Router->runRouteWithinStack()
#29 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(639): Illuminate\Routing\Router->dispatchToRoute()
#30 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch()
#31 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#32 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#33 /var/www/localhost/deployer/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Clockwork\Support\Laravel\ClockworkMiddleware->handle()
#35 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#36 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#38 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#39 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#41 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#42 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()
#44 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#45 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#47 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#48 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#50 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#51 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#53 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#54 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#56 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then()
#57 /var/www/localhost/deployer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#58 /var/www/localhost/deployer/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle()
#59 /var/www/localhost/deployer/public/index.php(0): {main}()
#60 {main}

**Comment by REBELinBLUE** [comment]
I'm really sorry you are having so many problems, I really don't get it. Dan, the creator of PHPCI uses Deployer many times a day https://twitter.com/dancryer/status/665175807615238144 as does the company I work for. We were actually discussing this thread this morning and we are both equally stumped.

**Comment by REBELinBLUE** [comment]
Could you upload a dump of your DB so I can try and figure out what state it is in?

**Comment by maveius** [comment]
It's to late I droped this databes and user :) This app has a lot of problem PHPCI is more comfortable to develop and implement a Deployment module ;)

**Comment by REBELinBLUE** [comment]
I'm sorry but I disagree, as I said Dan himself uses Deployer many times a day, my company uses it dozens of times a day. 

I've just looked into it, and your issue is because you didn't have the queue software setup before running a deployment so Laravel created the model but failed to add it to the queue. I've just pushed a fix to `master` to stop it trying to load deployments which didn't get queued correctly

**Comment by maveius** [comment]
The idea of deployment in my opinion is very simple, but I am not specialist.
PHPCI looks like to be a good place to be a Continuous Integration and Continuous Deployment tool. 

All In One App like "One Ring too rule them all", because If you have a lot of systems, one to Build and the other to Deploy is havy to manage. I think the best way is to merge it in one system :)
PHPCI have a good home page and it is next argument to use PHPCI to build and Deploy :) 

Thank You for Help, but I lost strength to use this project. I lost 4 days with fighting with this app, ok a lot of problems maybe was my mistakes or hasn't got knowledge. I am a Java programmer at work, but I think this is a hard language which need compile - developers loose a lot of time to wait to compile project and I try do something in PHP and Laravel becouse it simpler and faster for developers.
Now I a little bit change my mind. 

I wish you good luck and best regards and more power for developing this tool, mayby it will be alternative for everybody who would like to only deploy web-apps.
