### ISSUE TITLE
Failed to connect to a remote server

### ISSUE THREAD

**Issue by jcornide** [REBELinBLUE/deployer#134]
Hi
I have set up the tool in the same server as the code and it works fine (the staging server). But when I try to connect to a remote server (production) I wasn't able to make the ssh key.

- I've created the deploy user in the production server and added the key with the ssh-copy-id command. 
- I've verified that the deploy user has the key added to the authorized_keys file

But the connection nerwer worked anyway.

So I did some research in the code and I saw the command the app uses. I tried that command from the very same server the app is installed using hte RSA key in the database and I always get the invalid public,private key message.

I don't know if this is a bug, I don't think so because the key works in github correctly. I also tried to use the key generated by the app to connect from my computer to the prod environment and I also get the same error. But If i add my key that one works.

It might be something wrong at some point?

**Comment by jcornide** [comment]
My fault, problem found and solved :)

**Comment by dgpro** [comment]
I know this is an old thread but what is the command deployer run and what was you solution? As I'm having similar issue, it just fails to connect and I have set deployer and staging on the same server

**Comment by REBELinBLUE** [comment]
It is much easier to find the commands now as I extracted them from the code, take a look in `resources/scripts/`; any local commands (i.e. clone repository and archive release) are wrapped in the `RunScriptLocally.sh` and scripts run on the servers are wrapped in `RunScriptOverSSH.sh`

The 4 main steps run on the actual server are in `resources/scripts/deploy/steps/`

**Comment by REBELinBLUE** [comment]
You can also see the actual commands (i.e. without the place holders) in `storage/logs/cli-YYYY-MM-DD.log`

**Comment by dgpro** [comment]
Thank you!
