### ISSUE TITLE
Security issue with socket.io coding

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#135]
Any body can listen to socket.io channel for another persons also. Is this security issue ha?

**Comment by REBELinBLUE** [comment]
That is a very good point actually, I will have to look into how to use authentication with socket.io/redis pubsub

**Comment by REBELinBLUE** [comment]
https://github.com/auth0/socketio-jwt

**Comment by pavankumarkatakam** [comment]
socketio-jwt is for JWT authentication, I dont know regarding the below two links, i will checkout those links.

**Comment by REBELinBLUE** [comment]
Yeah sorry that was more notes for myself to look at

**Comment by pavankumarkatakam** [comment]
IHi @REBELinBLUE , take a look at this discussion https://laracasts.com/series/real-time-laravel-with-socket-io/episodes/2#comment-2309468203

**Comment by pavankumarkatakam** [comment]
And also this post https://www.ukietech.com/blog/programming/step-by-step-instruction-of-setting-up-real-time-secure-broadcasting-with-laravel-5-1-socket-io-and-redis/

**Comment by REBELinBLUE** [comment]
Thanks, I will take a look. Just finished work for the holidays so should get a chance to fix this, although probably not until sunday

**Comment by REBELinBLUE** [comment]
Working on this, think I have it working, need to do some testing and some cleanup

**Comment by pavankumarkatakam** [comment]
Hey thanks, Im developing docker image for this project so that anybody can install instantly ans also scale. But its still in dev , take a look at https://hub.docker.com/r/katakampavankumar/docker-deployer/.

**Comment by REBELinBLUE** [comment]
Awesome, thanks. Will take a look in a bit, never actually used docker

**Comment by pavankumarkatakam** [comment]
its  a containerization concept, i really like it and im doing everything with dockers now. like virtual box but application level virtualization where as virtualbox is hardware level virtualization.

**Comment by REBELinBLUE** [comment]
Yeah I know what it is, we are moving to it from OpenVZ at work, I've just never gotten around to actually playing around with it myself ;)

**Comment by pavankumarkatakam** [comment]
I'm also still learning ....

**Comment by REBELinBLUE** [comment]
I have merged it into master now, seems to be working fine for me, let me know if it works for you. You need to

**Comment by pavankumarkatakam** [comment]
Sure.

**Comment by REBELinBLUE** [comment]
Sorry, just realised I haven't updated the update command to generate `JWT_SECRET` in `.env`, doing so now

**Comment by REBELinBLUE** [comment]
Done
