### ISSUE TITLE
How to run socket?

### ISSUE THREAD

**Issue by gansky-alexander** [REBELinBLUE/deployer#136]
I have follow all steps from readme.md. Install project, configure nginx, add admin user and login to system. Then it show me next message. Can anyone help me to run socket?

*A connection could not be established to the socket at http://deployer.host.name. This is required for reporting the status on running deployments. Please reload, if the issue continues please contact the system administrator*

**Comment by REBELinBLUE** [comment]
Have you setup supervisor and node? Well node, supervisor isn't required but it is used to keep the socket server running.

Take a look at https://github.com/REBELinBLUE/deployer/blob/master/examples/supervisor.conf specifically line 15 to 25 for the socket server

**Comment by gansky-alexander** [comment]
I have install "apt-get install supervisor", run supervisor.
I have crate /etc/supervisor/conf.d/deployer.conf. Restart supervisor. But have see the same message.
I never works with node, so i do not know host to start sockets, can you help me to do that?

**Comment by REBELinBLUE** [comment]
Can you paste the output of `ps aux`?

Did you remember to edit the file to point to the path you've installed deployer?

**Comment by gansky-alexander** [comment]
root:/var/www/deployer# ps waux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       264  0.0  0.0   3008   160 ?        S    Oct19   0:00 upstart-udev-bridge --daemon
root       270  0.0  0.0  12036     4 ?        Ss   Oct19   0:00 /lib/systemd/systemd-udevd --daemon
root       327  0.0  0.0      0     0 ?        S<   Oct19   0:00 [ttm_swap]
root       527  0.0  0.0   3000   156 ?        S    Oct19   0:00 upstart-socket-bridge --daemon
root       647  0.0  0.0      0     0 ?        S<   Oct19   1:18 [kworker/u17:1]
root       678  0.0  0.0      0     0 ?        S    Oct19   0:00 [jbd2/xvda1-8]
root       679  0.0  0.0      0     0 ?        S<   Oct19   0:00 [ext4-rsv-conver]
root       804  0.0  0.0   2880   132 ?        S    Oct19   0:00 upstart-file-bridge --daemon
message+   808  0.0  0.1   4364   408 ?        Ss   Oct19   0:00 dbus-daemon --system --fork
syslog     849  0.0  0.3  48236   948 ?        Ssl  Oct19   0:20 rsyslogd
root       856  0.0  0.2   4212   524 ?        Ss   Oct19   0:00 /lib/systemd/systemd-logind
root       870  0.0  0.0   4168     4 tty4     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty4
root       874  0.0  0.0   4168     4 tty5     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty5
root       883  0.0  0.0   4168     4 tty2     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty2
root       884  0.0  0.0   4168     4 tty3     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty3
root       887  0.0  0.0   4168     4 tty6     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty6
root       920  0.0  0.0   7796   116 ?        Ss   Oct19   0:15 /usr/sbin/sshd -D
root       924  0.0  0.0   2192     4 ?        Ss   Oct19   0:00 acpid -c /etc/acpi/events -s /var/run/acpid.socket
daemon     931  0.0  0.0   2640    12 ?        Ss   Oct19   0:00 atd
root       932  0.0  0.0   3052   176 ?        Ss   Oct19   0:05 cron
whoopsie   973  0.0  0.2  50728   532 ?        Ssl  Oct19   0:01 whoopsie
root      1272  0.0  0.0   4168     4 tty1     Ss+  Oct19   0:00 /sbin/getty -8 38400 tty1
root      1294  0.0  0.0      0     0 ?        S    Oct19   0:00 [kauditd]
snmp      3043  0.0  0.2  12480   736 ?        S    Oct21  22:47 /usr/sbin/snmpd -Lsd -Lf /dev/null -u snmp -g snmp -I -smux mteTrigger mteTriggerConf -p /var/run/snmpd.pid
root      8471  0.0  0.1  29756   468 ?        Ssl  Dec22   2:30 /usr/local/bin/redis-server *:6379               
root      8809  0.0  0.0 113448    68 ?        Ss   Dec22   0:06 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)                    
www-data  8812  0.0  4.6 118328 11424 ?        S    Dec22   0:33 php-fpm: pool www                                                       
www-data  8813  0.0  5.0 118076 12612 ?        S    Dec22   0:33 php-fpm: pool www                                                       
root     10170  0.0  0.0  15224   152 ?        Ss   Nov19   0:00 nginx: master process /usr/sbin/nginx
www-data 12812  0.0  4.9 117044 12340 ?        S    Dec23   0:22 php-fpm: pool www                                                       
root     15603  0.0  0.0      0     0 ?        S    Dec24   0:03 [kworker/u16:1]
www-data 16002  0.0  0.1  15680   416 ?        S    Dec24   0:02 nginx: worker process
www-data 16003  0.0  0.0  16004   208 ?        S    Dec24   0:03 nginx: worker process
www-data 16004  0.0  0.4  15864  1036 ?        S    Dec24   0:02 nginx: worker process
www-data 16005  0.0  0.0  15864   156 ?        S    Dec24   0:02 nginx: worker process
root     21187  0.0  0.0      0     0 ?        S    06:41   0:00 [kworker/u16:2]
root     21541  0.0  0.7  11164  1748 ?        Ss   07:38   0:00 sshd: root@pts/1    
root     21636  0.0  1.0   6456  2588 pts/1    Ss   07:38   0:00 -bash
root     21938  0.0  2.7  15916  6908 ?        Ss   07:42   0:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
root     21941 16.7  5.6  57048 13856 ?        R    07:42   0:00 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
root     21942 17.5  5.5  57048 13836 ?        R    07:42   0:00 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
root     21947 16.7  5.6  57048 13856 ?        R    07:42   0:00 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
root     21948 16.7  5.5  57048 13852 ?        R    07:42   0:00 php artisan queue:work --queue=deployer-default --sleep=3 --tries=1 --daemon
root     21949  9.7  7.7  75808 19144 ?        Sl   07:42   0:00 node socket.js
root     21967  1.0  1.0   9828  2488 ?        Ss   07:42   0:00 sshd: root [priv]   
sshd     21968  0.0  0.4   9144  1116 ?        S    07:42   0:00 sshd: root [net]    
mysql    32689  0.1 20.9 330244 51752 ?        Ssl  Oct30 110:14 /usr/sbin/mysqld

<<< Did you remember to edit the file to point to the path you've installed deployer? 
I do not know )) there is my supervisor.conf

cat /etc/supervisor/conf.d/deployer.conf
[program:deployer]
command=php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
directory=/var/www/deployer
process_name=queue_%(process_num)s
numprocs=3
numprocs_start=0
stdout_logfile=/var/www/deployer/storage/logs/supervisord-%(process_num)s-stdout.log
stderr_logfile=/var/www/deployer/storage/logs/supervisord-%(process_num)s-stderr.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB
redirect_stderr=true
autostart=true
autorestart=true

[program:deployer-socketio]
command=node socket.js
directory=/var/www/deployer
numprocs=1
autostart=true
autorestart=true
environment=NODE_ENV=production
stderr_logfile=/var/www/deployer/storage/logs/node-stderr.log
stdout_logfile=/var/www/deployer/storage/logs/node-stdout.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB

[program:deployer-broadcast]
command=php artisan queue:work --queue=deployer-default --sleep=3 --tries=1 --daemon
directory=/var/www/deployer
numprocs=1
stderr_logfile=/var/www/deployer/storage/logs/broadcast-stderr.log
stdout_logfile=/var/www/deployer/storage/logs/broadcast-stdout.log
stderr_logfile_maxbytes=1MB
stdout_logfile_maxbytes=1MB
redirect_stderr=true
autostart=true
autorestart=true

How you think, meybe if would be better to create gitter channel?

**Comment by gansky-alexander** [comment]
Another proposal. Did you think about site where anyone can to read some kind of wiki?
For example: my next question wiil be "How to use deployer".

**Comment by gansky-alexander** [comment]
I have founded issue:
1. You use "meta_url" for storing URI for socket.io
2. Is have shage config: SOCKET_URL=http://deployer.mindteam.name -> SOCKET_URL=http://deployer.mindteam.name:6001

It works for me.

Can you comment it?

**Comment by REBELinBLUE** [comment]
Ah, sorry yes when using Apache you need to add the port to the `SOCKET_URL`, sorry I will make it clearer in the `README.md` file.

I do plan to make a website, I was planning to try out various CMS next week
