### ISSUE TITLE
Ignore deployment if already deploying

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#145]

**Comment by REBELinBLUE** [comment]
This is definitely on my list of things to do but when finishing #129 the idea is to make it deploy a specific revision passed into the webhook rather than simply the latest so I am wondering if rather than simply not queuing a new deployment it should cancel the running on/any queued and queue the newest one

**Comment by jbrooksuk** [comment]
You could use [AltThree/Locker](https://github.com/AltThree/Locker) for this.

**Comment by REBELinBLUE** [comment]
Thanks I'll take a look

**Comment by jbrooksuk** [comment]
Any update on this @REBELinBLUE? This is a constant issue for me because of the GitHub webhooks.

**Comment by REBELinBLUE** [comment]
Hey, Sorry I have been really busy recently. I am free this weekend for the first time in about 6 weeks so I will try and sort it out on saturday, can't imagine it'll be much work

**Comment by jbrooksuk** [comment]
:+1:

**Comment by REBELinBLUE** [comment]
I have started on this now, but how do you have your hook set up? If I am understanding the documentation correctly it'll only call the hook once for each push so it shouldn't deploy each commit?

Or is it just that you are pushing so often?

**Comment by jbrooksuk** [comment]
Our GitHub repo has a web hook setup that should only do `push` events. But we get it hit multiple times for some reason.

Deployer should also have a setting to only listen to webhooks on `x` branches.

**Comment by REBELinBLUE** [comment]
Hmm, interesting. OK well I am working on it. https://github.com/REBELinBLUE/deployer/blob/webhook-services/app/Http/Controllers/WebhookController.php#L78

You can actually pass in update_only=true to the webhook and it'll only deploy if the webhook request matches the currently deployed branch (although obviously this doesn't work with github currently as it doesn't know which branch the commit is on). Still working on it though

**Comment by jbrooksuk** [comment]
:+1:

Let me know when you need me to test it.

**Comment by REBELinBLUE** [comment]
Hi @jbrooksuk I am trying to get this finished today. Could you send an example of the data which is sent to Deployer by a web hook? I have one sent up an whether it is a push with 1 commit or a push with multiple commits the URL is only hit once

!()[http://dropshare.rebelinblue.com/Screen-Shot-2016-05-02-09-58-51-VwHE7M7i3Z/Screen-Shot-2016-05-02-09-58-51.png]

Some of those pushes have 1 commit in, some have dozens but each push is only hitting the URL once and triggering one deployment

**Comment by jbrooksuk** [comment]
That's the same as what we have. But what if you push, then push again?

**Comment by REBELinBLUE** [comment]
Well multiple pushes will hit the hook multiple times. I obviously misunderstood you.

**Comment by REBELinBLUE** [comment]
Fixed in cf941f2
