### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jonnylor63** [REBELinBLUE/deployer#149]
Hello,
i try to install deployer on vagrant/homested machine (http://deployer.app/) - Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64).
After the install i try to configure my nginx server using the configuration found in examples/nginx.conf but when i log into the application i receive a "Server error" message.
The problem comes from the call to the http://deployer.app/socket.io/?.... who return 502 Bad Gateway nginx/1.9.7

**Comment by REBELinBLUE** [comment]
Have you started the node server? `node socket.js` https://github.com/REBELinBLUE/deployer/blob/master/examples/supervisor.conf#L15-L25

and does your nginx config have the upstream https://github.com/REBELinBLUE/deployer/blob/master/examples/nginx.conf#L1-L3
