### ISSUE TITLE
css broken

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#152]
after gulp --production, i get broken css

mostly because of path setting and if i use http://domain.com/deployer/public its breaking i guess

![image](https://cloud.githubusercontent.com/assets/3512953/12402513/7c2af8a6-bdfb-11e5-9a85-d20f0d509902.png)

**Comment by REBELinBLUE** [comment]
Unfortunately I believe Laravel is designed so that the `public` folder is the webroot so the paths etc are relatively to there. I will take a look around and see if there is an easy way around it but I doubt there is

**Comment by lorvent** [comment]
yes, when using virtual domain... UI is working great

socket error is coming up but thats not related to this issue so closing this one
