### ISSUE TITLE
Console command to create user

### ISSUE THREAD

**Issue by jcornide** [REBELinBLUE/deployer#155]
It would be great to have console command to create users. That way it would be easier to create an ansible role to install the deployer and later add the first user.

**Comment by REBELinBLUE** [comment]
That makes sense, don't think it would be too difficult

**Comment by jcornide** [comment]
Great :) Unfourtunately I'm not familiar with laravel but with symfony. I'd love to contribute to this tool, we're actually using it a lot

**Comment by REBELinBLUE** [comment]
Create to hear that other people are using it

![](https://s3.amazonaws.com/f.cl.ly/items/1o3W0h1z2x2W102q1e3s/Image%202016-01-27%20at%205.05.30%20pm.png)

Should be able to finish it tonight, just need to add validation

**Comment by REBELinBLUE** [comment]
I have committed to `master`, take a look

**Comment by jcornide** [comment]
looks great, how can I test it? I updated the code but the command is not
available

On Wed, Jan 27, 2016 at 6:35 PM, Stephen Ball <notifications@github.com>
wrote:

> I have committed to master, take a look
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/REBELinBLUE/deployer/issues/155#issuecomment-175760246>
> .
>



-- 
José Cornide
Tlf.: 609 720 220

**Comment by REBELinBLUE** [comment]
Have you switched to `master`? You will also probably need to run `composer install` so it generates a new autoloader
