### ISSUE TITLE
Minor UI issues in modals, deploy button

### ISSUE THREAD

**Issue by alsotop** [REBELinBLUE/deployer#161]
Modals slightly disappear behind the header because their z-index is less than it:
http://i.imgur.com/9Ve5Rlb.png
.main-header has a z-index: 21 and .modal has a z-index: 10

Deploy button incorrectly styled because the Deploy text is within the span for fontawesome icon instead of outside the span:
http://i.imgur.com/I6GMbPm.png
This could be changed to:
`<button id="deploy_project" data-toggle="modal" data-backdrop="static" data-target="#reason" type="button" class="btn btn-danger" title="Deploy the project"><span class="fa fa-cloud-upload"></span> Deploy</button>`

**Comment by REBELinBLUE** [comment]
Yeah we noticed this at work today,it only seems to happen in production mode with minified CSS & HTML. Will try and get it fixed this evening

**Comment by REBELinBLUE** [comment]
Fixed the problem, I've merged it into the `release` branch so you can switch to it without having to install the dev dependencies you'd need to run from `master`
