### ISSUE TITLE
how to run gulp and chmod storage folder properly

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#167]
Hello,
i know i am bugging you for whole day... sorry :( but i am trying to do it all the ways possible and spent hours but not able to figure out.

I want to deploy my laravel project where, i want to
* run migrations
* chmod storage, bootstrap/cache folder
* npm install
* gulp

can you please point me in right direction.

thanks

**Comment by REBELinBLUE** [comment]
So I'd have 3 "before activate" tasks where I

Run migrations
```
cd {{ release_path }}
php artisan migrate --force
```

Run node
```
cd {{ release_path }}
npm install --production
```

Run gulp
```
cd {{ release_path }}
gulp --production
```

For the storage folder I would test it up as a "Persistent file" on the "Files" tab with a path of `storage/` that will then create a `shared` folder at the same level as `releases` and them the storage folder will be moved to there and symlinked between releases

For the bootstrap directory you can also add a "before activate" task with

```
cd {{ release_path }}
chmod 755 bootstrap/cache
```

You'd presumably also want a before activate task with

```
cd {{ release_path }}
php artisan down
```

as the first one

and an after activate task with

```
cd {{ release_path }}
php artisan up
```

Ignore the invalid tag BTW, that is just so it doesn't appear in the changelog

**Comment by lorvent** [comment]
Thanks for the help,
i almost doing same but i added bootstrap/cache also into persistent files,

also,can you please tell me how you are handling .env?

if i put server details into .env.example then there is no use of having .env.example at all,
I am sure you might be handling in a smart way.

**Comment by REBELinBLUE** [comment]
Ah of course I forgot `.env`. On the `files` tab put that in `configuration files` and it'll create it in the folder on each deploy (or you could make it a persistent file and it'll symlink it on each deployer but you'd need to manually add the file with the correct content to the `shared` folder by hand)

**Comment by lorvent** [comment]
oh ok, i am doing that now... manually adding .env into shared then adding it into persistent files, but i thought you might be using some other flow like adding it into configuration files.

i tried configuration files option last time but i think it failed....

thanks for the info... this helps me in creating doc for a laravel app deployment.

**Comment by REBELinBLUE** [comment]
Hmm that is weird, configuration file should work unless I have broken something. I will have to try later

**Comment by lorvent** [comment]
Hi,

friendly reminder: 0.0.28 seems to be broken

its not working for me on fresh install and upgrade

i had to move back to 0.0.27 to make it work properly.

**Comment by REBELinBLUE** [comment]
Hmm you're right, odd it is working on my dev machine fine but not on my production machine. Looking at it now

**Comment by REBELinBLUE** [comment]
My issue "just" turned out to be that my storage/* folders weren't writable for some reason, can you check yours are?

**Comment by lorvent** [comment]
for me, first it has shown storage error, after fixing that it started showing lot of manifest.json errors, one after another.

**Comment by REBELinBLUE** [comment]
Can you try the latest `release` branch?

**Comment by lorvent** [comment]
same issue like i told before
![screencapture-deploy-lorvent-com-1454665616967](https://cloud.githubusercontent.com/assets/3512953/12842865/8b1813e6-cbc3-11e5-9103-a8cd2cb4403b.png)

**Comment by REBELinBLUE** [comment]
That makes no sense, it is there https://github.com/REBELinBLUE/deployer/tree/release/public/build

Can you try `git reset --hard HEAD`

**Comment by lorvent** [comment]
that made it work

**Comment by REBELinBLUE** [comment]
👍

**Comment by lorvent** [comment]
running npm install, composer install may caused this problem...

**Comment by REBELinBLUE** [comment]
That is very odd, because obviously I did that as well

**Comment by REBELinBLUE** [comment]
Crap, I see why. I tagged the `master` branch as the release, not the `release` branch. That explains it. Making a new release now

**Comment by REBELinBLUE** [comment]
Fixed, apologises for that, `0.0.29` is out

**Comment by lorvent** [comment]
Hey no problem,
i want to metion one more thing.... mail notification working only 2-3times out of 10 builds, did you face similar issue anytime?

**Comment by REBELinBLUE** [comment]
Honestly, I have never used mail notifications, someone added those as a pull request. I'll see if I can have a play around tomorrow evening, refactoring them as part of the hipchat stuff anyway

**Comment by lorvent** [comment]
Oh ok... I want you to be aware of it...
if hipchat notifications are there, i may not use mail notifications :smile:

**Comment by lorvent** [comment]
another interesting thing is,

before command like

````
pwd

cd {{ release_path }}

pwd
```` 
used to get executed, now its displaying them as plain text , not sure whether its executing them or not.

**Comment by REBELinBLUE** [comment]
Uh, nothing has changed in that. Do you have `APP_DEBUG` on in `.env`?

In debug mode I use `set -e` which means bash will print out the commands along with running them

**Comment by lorvent** [comment]
Oh nice...may be thats the reason, yes i do have APP_DEBUG=true

**Comment by REBELinBLUE** [comment]
You may need to run `php artisan optimize --force && php artisan config:cache` after to change it to ensure the cached version of the config is cleared (app:update normally does it for you)

**Comment by lorvent** [comment]
hmm, its still displaying those commands after making debug false and running above command but that does no hard so we can leave it.

I have few other questions/suggestion beside hipchat notifications
- [ ] can we run deployment only if branch specified matches with branch in github? usually github triggers webhook for push to any branch where as deployer pulls and runs only for specific branch (intened) so can we avoid those extra builds?

- [ ] can we have user roles? i have seen another issue for that....

**Comment by REBELinBLUE** [comment]
The first one is definitely on the list, I just haven't had a chance to look at the github/bitbucket/gitlab etc APIs yet. The [Deployer plugin for PHPCI](https://github.com/Block8/PHPCI/blob/master/PHPCI/Plugin/Deployer.php) currently does this.

The second one I am still not 100% sure about yet, I want to do it at some point but for me it is quite low priority so I haven't even began to think about it. Of course I am always open to pull requests ;)

**Comment by lorvent** [comment]
Thanks for that.

i really love this project so i will see if my skill set allows me to send PR
