### ISSUE TITLE
Servers list, variables list, files lists on Project Page empty on 0.0.28 (Potential Javascript error)

### ISSUE THREAD

**Issue by alsotop** [REBELinBLUE/deployer#168]
On 0.0.28, the servers list, variables list and files lists are empty on the Project page, and there is a Javascript error reporting to the console:

`Uncaught TypeError: app.VariablesTab is not a function`

**Comment by REBELinBLUE** [comment]
Hmm, someone else is having problems with 0.0.28 but it is working for me. Can you try switching to the `release` branch and see what happens?

**Comment by REBELinBLUE** [comment]
Crap, I see why. I tagged the `master` branch as the release, not the `release` branch. That explains it. Making a new release now

**Comment by REBELinBLUE** [comment]
Fixed, apologises for that, `0.0.29` is out

**Comment by alsotop** [comment]
Thanks, that's done the trick. Great work as always!

**Comment by REBELinBLUE** [comment]
Ha ha, thanks. I should double check what I am doing in future!
