### ISSUE TITLE
While running queue always error "No query results for model"

### ISSUE THREAD

**Issue by qunabu** [REBELinBLUE/deployer#172]
Thanks for a great app. Yet i have a problem i cannot solve from few hours. 
I have installed depolyer on webfaction 
queue is always throwing me 
``` 
[Illuminate\Database\Eloquent\ModelNotFoundException]       
No query results for model [REBELinBLUE\Deployer\Project].  

[Illuminate\Database\Eloquent\ModelNotFoundException]          
No query results for model [REBELinBLUE\Deployer\Deployment]. 
```
so neighter testing server nor deployments works. What can i do to make it works ?

**Comment by REBELinBLUE** [comment]
Hmm. Is there anything in `storage/logs/cli-YYYY-MM-DD.log` ?

**Comment by qunabu** [comment]
jest cleared all the logs and rerun, nothings there unfortunetly.

**Comment by qunabu** [comment]
is there any unit test for queue ?

**Comment by REBELinBLUE** [comment]
Embarrassingly there are no unit tests at all currently. 

Run `php artisan queue:flush` to clear the queue, although not sure what could have gotten into there which is causing it. You could try `php artisan queue:failed` before flushing it, there might be something in there I can use to debug it

Can you try enabling `APP_DEBUG` in `.env` and then running `php artisan cache:clear` and `php artisan optimize --force` to set it into debug mode, hopefully then there will be some more useful information

**Comment by qunabu** [comment]
it helped. thanks

**Comment by REBELinBLUE** [comment]
Oh?

**Comment by qunabu** [comment]
there seems to be "something" left either in redis or cache. Clearing those removed `No query results for model` for model issue. I do have another one but will raise another
