### ISSUE TITLE
Custom deployment templates

### ISSUE THREAD

**Issue by qunabu** [REBELinBLUE/deployer#174]
Is it possible at the moment to have totally custom deployment templates. 
To have full control on commands under DeployJobs, to create own ones or to disable/delete default ones. 

Running scripts _before_ and _after_ works fine, but for instance I would like to have a deployment template that does only 

1. cd project_path
2. git fetch --all
3. git checkot -f branch
4. clear app cache 
5. update app database 

it this scenario there is no need for cloning. What I've seen is that those commands are hardcoded in app/Jobs/DeployProject.php. 

Above would be possible with _before_ and _after_ script and disabling default ones.

**Comment by lorvent** [comment]
well....in this case you want just a git cloning type of project, you don't need to utilize deployer for it.

my simplest bet it, you use https://github.com/Perennials/apache-git-sync-tool which is enough for your needs.

**Comment by qunabu** [comment]
I do really like deployer and I think that giving full control on deployment script swould make it just better and more useful software.  

I'm aware of those tools, I've given simplest scenario. What I really want is to have more control on deployment scripts. 

Form one the repository that Im participating cloning takes about 1 hour, and has more then 3GBs. This is not always necessary for stage servers.

**Comment by REBELinBLUE** [comment]
#129 Should solve this problem... (although it would also use a lot of space in your case) I am also looking at the github etc APIs so that I can get just the specific revision. The problem with git is that it doesn't have anything like `svn export url@revision`. The closest is `git archive` bit services like github disable that and you have to use their API.

**Comment by qunabu** [comment]
I've seen that ticket and I meant something different. My issue is not _git_ related.

At the moment __deployer__ force user how his application must be deployed and in my opinion it should be only a default option. 

I could found __deployer__ extremely useful when I could have run script I want to and those 4 steps would be only default option or I could amend actual scripts. I can setup jenkins and give him some scripts but i find __deployer__ more suitable for me. If that's not clear I can answer in details
