### ISSUE TITLE
Dashboard. project is forever "Deploying"

### ISSUE THREAD

**Issue by qunabu** [REBELinBLUE/deployer#178]
Im not sure when and how it happen but this is blocking deployer from workign at all 
In dashborad project is always in "Deploying"
![image](https://cloud.githubusercontent.com/assets/214608/13079257/9c7cfe72-d4c3-11e5-9f51-d43904858a3c.png) and i cannot run next deploy 

What i did already 
1. restart node app
2. flushed and restart redis  
3. clear app chace 
4. clear laraver queue

when above didnt help I've truncated database tables `deployments`, `deploy_steps` and `server_logs` 
 
What else can i do to make __deployer__ alive again

**Comment by REBELinBLUE** [comment]
I am guessing this is from the issue you had with the queue the other day, run

`php artisan deployer:cleanup`

or

`UPDATE projects SET status = '3' WHERE status = '2';`

**Comment by qunabu** [comment]
that was quick !! 
it solved my problem

**Comment by REBELinBLUE** [comment]
I happened to have github open ;)

I think I need to add a cronjob which will check for stalled deployments which are no longer in the queue, will need to investigate how to check the queue in laravel
