### ISSUE TITLE
Exception when project has deployments but none are 'completed'

### ISSUE THREAD

**Issue by Patabugen** [REBELinBLUE/deployer#188]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Load the Project View page

### Actual behaviour

An exception is thrown

### Steps to reproduce

I've roughly diagnosed this error and think I've got it right. I setup a project and hit Deploy, it didn't work and I cancelled it (I think with a cleanup through 'artisan'). As a result I have a project with two failed deployments and no completed ones, causing an error when the system tried to find the current deployment.

I suspect the system should load the latest deployment regardless of status (remove the `WHERE status` clause) as a fix, but I haven't explored any of the workings of the system to be able to be sure of that idea

I now have these deployments in the DB:
```
mysql> select status, project_id, id from deployments where project_id = 3;
+--------+------------+----+
| status | project_id | id |
+--------+------------+----+
| 3      |          3 |  2 |
|        |          3 |  3 |
+--------+------------+----+
2 rows in set (0.00 sec)
```

when I load `/projects/3` I get an exception thrown from this bit of code:

```
    /**
     * Determines if the deployment is the latest deployment.
     *
     * @return bool
     */
    public function isCurrent()
    {
        if (!isset(self::$currentDeployment[$this->project_id])) {
            self::$currentDeployment[$this->project_id] = self::where('project_id', $this->project_id)
                                                              ->where('status', self::COMPLETED)
                                                              ->orderBy('id', 'desc')
                                                              ->first();
        }

        return (self::$currentDeployment[$this->project_id]->id === $this->id);
    }
```

The error is because `self::$currentDeployment[$this->project_id]` is not an object, because the SQL lookup finds nothing - since there are no deployments with a `status` of 0.

To work around I manually set the status of one deployment to 0 ( `update deployments set status = '0' where id = 3;` and now it loads (but thinks it completed).

### Environment info
Operating System: Ubuntu 14.04.1
PHP Version: 5.6.18
Node Version: 0.10.25
Database System: mysql
Database Version: 5.5.47
[apache2handler-2016-03-09.log.txt]

### Logs (see storage/logs/) or other output that would be helpful
(https://github.com/REBELinBLUE/deployer/files/165231/apache2handler-2016-03-09.log.txt)

**Comment by jbrooksuk** [comment]
I'm getting this too (latest `master`).

**Comment by REBELinBLUE** [comment]
I shall take a look at this this evening

**Comment by REBELinBLUE** [comment]
This should be fixed now as the method now tests that there is a current deployment... although I am a bit unsure how the error is happening because `isCurrent` is only called on a deployment that `isSuccessful` so there should always be at least one successful deployment when the method is called.

That said, the method shouldn't just assume there is a successful deployment so now it doesn't
