### ISSUE TITLE
Installation fails at app:install on Faker not found

### ISSUE THREAD

**Issue by hawle** [REBELinBLUE/deployer#192]
This is the problem here: 
`composer install --no-dev`

This will prevent Faker from installing into the app and `php artisan app:install` will fail at the seeding step, since it wants to use Faker for the seeds.

In order to install the app properly, you have to install the app in dev mode (install dev packages, and in local environment), then when you have your admin user, switch back to production mode.

**Comment by REBELinBLUE** [comment]
Confirmed, not sure how the hell I have managed to do this! I will fix it over my lunch break in an hour.

**Comment by REBELinBLUE** [comment]
hmm, sorry just realised the issue I was having was something completely different

Don't suppose you can paste the output you were getting and/or the log? `app:install` should not do any seeding.

**Comment by hawle** [comment]
Thanks, you can close this issue, it is not package-related! 

The problem was, that I am trying to install this on Homestead, and the default yaml file contains `APP_ENV => local` variable. This overrides your .env file which is written during app:install runs. 

Maybe it would be nice to let the user know during install, what the current environment is. 

Thanks for checking though!

**Comment by REBELinBLUE** [comment]
Ah interesting, I will take a look at installing it on homestead the normal way. I use the homestead box but as a proper Vagrant VM (see the Vagrantfile)
