### ISSUE TITLE
Can't go through installation process with PostgreSQL

### ISSUE THREAD

**Issue by badnazo** [REBELinBLUE/deployer#194]
Hi, I'm looking to get your piece of software working, but can't do righht now. So here's my bug report

### Expected behaviour

Expected to go through installation process and be able to login with provided information during script.

### Actual behaviour

2 Errors at the end of the artisan script.
Admin account isn't created, but default admin@example.com user is in the database after script fail.
Can't Log-in. Maybe i could try default user if i had default password.

### Steps to reproduce

Just trying a clean install following instructions in README.md
Droping & Recreating database + git clean -x -f -d at each try.

### Environment info

Operating System: Debian 8 + Testing Repo
PHP Version: v5.6.17-3 (same error on v7.0)
Node Version: v4.3.1
Database System: PostgreSQL
Database Version: v9.5

### storage/logs/cli.log (same output at the end of php artisan)

production.ERROR: exception 'PDOException' with message 'SQLSTATE[42803]: Grouping error: 7 ERROR:  column "projects.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...= $2 and "projects"."deleted_at" is null order by "name" asc
                                                             ^' in /opt/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335
[...]
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42803]: Grouping error: 7 ERROR:  column "projects.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...= $2 and "projects"."deleted_at" is null order by "name" asc
                                                             ^ (SQL: select count(*) as aggregate from "projects" where "projects"."group_id" = 1 and "projects"."group_id" is not null and "is_template" = 0 and "projects"."deleted_at" is null order by "name" asc)' in /opt/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
[...]

### Steps I could do
- Installation on MariaDB or MySQL Database ?

**Comment by REBELinBLUE** [comment]
Hmm, I shall take a look at this as soon as I am free in about an hour.

**Comment by REBELinBLUE** [comment]
This is fixed in `master` I will release a new tagged version later today
