### ISSUE TITLE
Can't go through installation #2

### ISSUE THREAD

**Issue by badnazo** [REBELinBLUE/deployer#195]
### Expected behaviour

Would really want to test this piece of software following REAMDE.md

### Actual behaviour

Fail when i call the home page.
Username is now created sucessfully in database

### Steps to reproduce

Fresh install from 'master' after PostgreSQL corrections
seems to be linked to a missing json file

### Environment info
Operating System: Debian 8 + Testing
PHP Version: v5.6.17-3 
Node Version: v4.3.1
Database System: PostgreSQL
Database Version: v9.5

### Logs (storage/logs/fpm-fcgi-2016-03-21.log)
[2016-03-21 20:11:06] production.ERROR: exception 'ErrorException' with message 'file_get_contents(/opt/deployer/public/build/rev-manifest.json): failed to open stream: No such file or directory' in /opt/deployer/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:341

**Comment by REBELinBLUE** [comment]
Sorry `master` is only for development so doesn't have compiled assets in, you'd need to install gulp etc and build it. Don't worry, I am just making a few final tests and will then release a new tag with the fix to your previous issue

**Comment by REBELinBLUE** [comment]
Version `0.0.31` is out now
