### ISSUE TITLE
Be able to run commands from the deployer server

### ISSUE THREAD

**Issue by jcornide** [REBELinBLUE/deployer#199]
I think it might be useful to be able to choose 
- to run the commands from the servers where you're going to deploy (cache clear, assets regenaration, etc...) 
- OR directly from the deployer server (which might be useful to, i.e., launch a Jenkins task, hip chat notificaction, etc...). 

There are some tasks that, I think, makes more sense to be executed directly from the deployer rather than the application servers.

**Comment by REBELinBLUE** [comment]
Never thought about that before but I guess it makes sense. Technically it should be fairly simple to implement, although I'll need to think how to make it clear in the UI

**Comment by jcornide** [comment]
Here's my scenario, we have the following set up:
- The deployer server which deploys code to staging and production envs, only accesible in our internal network
- The staging and production servers, both with public access
- The jenkins server, which launches the tests on both staging and production. Only accesible in our internal network

What we do is that we have a Jenkins job that everyday at 00:01 launches the deploy on the stagin enviroment using the very nice feature you implemented it :). After the deploy is done we want to notify Jenkins so it will start perfoming the tests on the staging environment. That can be done with a curl to an URL. But, and here's the tricky part, the command is executed in the staging server and we don't want it to have access to Jenkins.

I found a workaround which is add the deployer server as a server in the project, don't deploy the code on it and run the commands from it. The only downside of this is I have to add the ssh key to the authorized_keys... only to connect to itself :) But it works

So I don't know if more people have this sort of environment and might found this useful.

Cheers

**Comment by REBELinBLUE** [comment]
Yeah that makes sense

**Comment by REBELinBLUE** [comment]
Now that notifications have the ability to call a URL on deployment does that fit your need for this?

**Comment by jcornide** [comment]
absolutely! thanks

**Comment by REBELinBLUE** [comment]
Awesome :)
