### ISSUE TITLE
Setup the app with the guide and deployed codes,but nothing happend

### ISSUE THREAD

**Issue by aiddroid** [REBELinBLUE/deployer#200]
### Expected behaviour
- Generate ssh key automatic

- Deploy codes to target server

### Actual behaviour
- No ssh key generated in new project's DB record (I have generated by myself manually)
- Nothing happend after check server connection(always testing) & deploy project(always pending)

### Steps to reproduce

- install the app with the guide
- run redis and beanstalkd
- add crontab jobs and run socket.io
- create new project 
- add target deploy servers
- check server connection & deploy codes

### Environment info
Operating System:CentOS 7 x64
PHP Version:7.0
Node Version:0.10.42
Database System:MariaDB
Database Version:5.5.44

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
It sounds like you haven't got the queue listener and socket server running? see `examples/supervisor.conf`

**Comment by aiddroid** [comment]
Thank you very much,with supervisor,it works well.

**Comment by REBELinBLUE** [comment]
Awesome, good to hear 😃
