### ISSUE TITLE
SSH key not being created

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#201]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour
1. while creating a project, its not accepting ssh key which is generated for a previous project
2. in project page, clicking on ssh key, its showing empty key
![x](http://www.clipular.com/c/6157926283083776.png?k=pYYaCASKXOlnf6aOWlW5ipGQtEo)

### Actual behaviour

1. showing error ```The private key is not a valid passphrase-less key.```

2. empty ssh key
### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

### Environment info
Operating System:
PHP Version:
Node Version:
Database System:
Database Version:

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
Investigating now

**Comment by lorvent** [comment]
thanks.... thats quick

**Comment by REBELinBLUE** [comment]
Hang on, I've just realised something. How are you using the key created for a previous project? Deployer over ever shows the public key, you have to enter the private key if you want to supply your own. Did you go into the DB and get it?

**Comment by lorvent** [comment]
hi no,
i took it from other project directly by going to that page, click on ssh key and copy the key.

**Comment by REBELinBLUE** [comment]
That is a public key, not a private key, you can't use that. You need to generate a private key on your computer and set both projects to use that. The private key is never exposed anywhere as doing so is a big security risk, especially if you aren't on HTTPs.

**Comment by REBELinBLUE** [comment]
I am fixing situation 2

**Comment by REBELinBLUE** [comment]
I have fixed the blank SSH key in `master`, I will tag a new release later this evening. All you need to do is edit the project and save it

**Comment by lorvent** [comment]
Ok,
thank you

> That is a public key, not a private key, you can't use that. You need to generate a private key on your computer and set both projects to use that. The private key is never exposed anywhere as doing so is a big security risk, especially if you aren't on HTTPs.

in that case, how can we make use of this insert ssh key feature for using keys of existing projects.

**Comment by REBELinBLUE** [comment]
You could get it directly from the DB, the `private_key` column in the `projects` table but I'd recommend you change the for the existing project.

I may see if I can think of a way to share keys between projects in the feature, rather than each having their own copy

**Comment by lorvent** [comment]
updated to latest version still key is not being generated, shall i re-create project?

also in readme, please change version to 0.0.33 instead of 0.0.34 as that tag not yet created.

**Comment by REBELinBLUE** [comment]
Hmm, how on earth did that happen, it is all automated :| Must be a bug in my `create-release` script.

Glad to hear it fixed it
