### ISSUE TITLE
Export/import configuration

### ISSUE THREAD

**Issue by jcornide** [REBELinBLUE/deployer#202]
I think it would be a nice thing to have: the option to import and export the configuration (projects, commands, servers...) so in case its needed to restart the server it can be restored easily.
Right now I'm doing it with a mysqldump and discarding some table to just export the configuration:
`mysqldump -u root deployer --ignore-table=deployer.migrations --ignore-table=deployer.jobs --ignore-table=deployer.deployments --ignore-table=deployer.deploy_steps --ignore-table=deployer.failed_jobs --ignore-table=deployer.server_logs --ignore-table=deployer.password_resets > dump.sql`

**Comment by REBELinBLUE** [comment]
I actually use https://github.com/backup-manager/laravel to backup the DB whenever an update is run, so it should be possible to use this to do what you want, try running `php artisan db:backup` ;) Not sure if there is a way to ignore tables off hand though
