### ISSUE TITLE
How to deploy deployer with ..deployer itself?

### ISSUE THREAD

**Issue by phoenixgao** [REBELinBLUE/deployer#204]
Is it possible?

**Comment by REBELinBLUE** [comment]
This is something I am still trying to figure out, the problem is as part of the update process it needs to restart the queue so doing that will kill the running job. Another install of deployer can update it, but that isn't very useful

**Comment by pavankumarkatakam** [comment]
I think restarting the queue with `php artisan queue:restart` will not effect the ongoing job as mentioned [here](https://laravel.com/docs/5.2/queues) . Take a look at it.

**Comment by REBELinBLUE** [comment]
Yeah I know that won't, I can't remember off hand exactly what the problem was, I have tried it before like 6 months ago and I remember there being a problem

**Comment by REBELinBLUE** [comment]
I just tried it, seems it works. I had to set up 3 commands

Before activate

Run updater
```shell
cd {{ release_path }}
php artisan app:update
```

After activate

Restart php-fpm
```shell
sudo /usr/sbin/service php7.0-fpm restart
```

Restart queue
```shell
cd {{ release_path }}
php artisan queue:restart
```

Although come to think of it, the last one isn't actually needed as `app:update` does it.

I also added

```
deploy	ALL=NOPASSWD:/usr/sbin/service php7.0-fpm restart
```

to `/etc/sudoers`
