### ISSUE TITLE
Support for TrustedProxies package

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#209]
Its just a feature so i deleted all the todo's, Ofcourse im already running the latest version.

To run laravel application under load balance or reverse proxy, there is a package fr easyness
https://github.com/fideloper/TrustedProxy . So that deployer application can be run under load balancer. 
Also see the discussion here https://laracasts.com/discuss/channels/general-discussion/routes-https-on-loader-balance?page=0

Actually my use case is , im developing an Docker version of deployer application so that it is easy to install and scale. Actually i started this in the past due to some work load it is delayed. This is the development repo https://github.com/pavankumarkatakam/deployer

**Comment by REBELinBLUE** [comment]
I did see your docker container but hadn't tried it out.

**Comment by pavankumarkatakam** [comment]
Thanks for supporting this package, but is it work for tag 0.0.30 or master only.

**Comment by REBELinBLUE** [comment]
It is currently in `master`, I will merge it into `release` tomorrow evening so it is at least usable without the dev dependencies but it'll be a little while until I tag a new release
