### ISSUE TITLE
Custom port configuration for repository

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#210]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour
To deploy successfully

*Please describe what you're expecting to see happen.*

### Actual behaviour
Not deploying the code to server

*Please describe what you're actually seeing happen.*

### Steps to reproduce
1. added new project in the administration side menu. (I have left the `Private SSH Key ` filed blank )
2. Added a server and tested successfully, showing green color indication in the servers tab.
3. now pressing the deploy button (which is in enabled state)

*If your issue requires any specific steps to reproduce, please outline them here.*

### Environment info
Operating System:
PHP Version:
Node Version:
Database System:
Database Version:

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

here is the logs from storage/log/cli file 
```

[2016-04-16 11:18:49] production.ERROR: exception 'RuntimeException' with message 'Could not mirror repository - Cloning into bare repository '/var/www/deployer/storage/app/mirrors/https___pavankumar_git.sample.com_pamilyaweb1_host.git'...
fatal: could not read Password for 'https://pavankumar@git.sample.com': No such device or address

```

**Comment by pavankumarkatakam** [comment]
Changed the git url from https format to git format now im getting this error

```
/var/www/deployer/storage/app/mirrors/git_git.invizotechnologies.com_pamilyaweb1_host.git'...
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

It is saying that you doesn't have permissions, but i have set the key in deployer key in my gitlab instance as well as authorized key file also.

**Comment by pavankumarkatakam** [comment]
I found the issue, that is my gitlab instance is running in ssh port 2222, So i changed the `resources/scripts/tools/SSHWrapperScript.sh` to like this 

```
#!/usr/bin/env sh

ssh -o CheckHostIP=no \
    -o IdentitiesOnly=yes \
    -o StrictHostKeyChecking=no \
    -o PasswordAuthentication=no \
    -p 2222 \
    -o IdentityFile={{ private_key }} $*

```


Then it is working fine, may be you want to give option for port when adding the project.

**Comment by pavankumarkatakam** [comment]
ping @REBELinBLUE

**Comment by pavankumarkatakam** [comment]
Now i know that we can specify port in git url like this
`ssh://git@sample.com:2222/url/repo.git`

**Comment by REBELinBLUE** [comment]
Never thought about that. I will add some text to the repo label

**Comment by REBELinBLUE** [comment]
I've thought about this, and for now I'm not going to do this. That is normally what you would do to specify a port in a URL. If it comes up again I guess I will revisit this and think about how to present it on the project edit dialog
