### ISSUE TITLE
Server always testing,.. 

### ISSUE THREAD

**Issue by cerw** [REBELinBLUE/deployer#216]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

I click on check server and it should check the serve rand return some results. 

### Actual behaviour

It gets stuck on testing and I dont see any event to be executed in Queue? 

### Steps to reproduce

Adding new server click on check. 

### Environment info
Operating System: Ubuntu 64 trusty
PHP Version: PHP 5.6.21-1+donate.sury.org~trusty+4 (cli) 
Node Version:v6.1.0
Database System:Mysql
Database Version:5.5.49-0ubuntu0.14.04.1 

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
Do you have beanstalk and redis running? Can you past the output of the 2 logs for the date in `storage/logs/` ?

**Comment by cerw** [comment]
Yes I have redis and beanstalk running and socket.io as well (via NGINX proxy) they all seem to work. as Event are being fired.. 

There are no entries in log files when i press check server.. no error nothing..

**Comment by REBELinBLUE** [comment]
can you run `ps aux` on the server after clicking on the check option and paste the output here?

**Comment by cerw** [comment]
@REBELinBLUE https://git.nano.rocks/snippets/7

**Comment by REBELinBLUE** [comment]
Hmm, ok so nothing useful there. Can you run

```shell
$php artisan queue:failed
```

**Comment by cerw** [comment]
deployer@logs:~/deployer$ php artisan queue:failed
No failed jobs!

**Comment by cerw** [comment]
Which event should running to test the server?

**Comment by cerw** [comment]
![image](https://cloud.githubusercontent.com/assets/16146/15428067/dbbeb722-1ecb-11e6-96e6-d9934a16e45a.png)

@REBELinBLUE Here is screenshot of queue and socket server when i created new server, but there is no log or anything :( 

Me must be missing something...

**Comment by REBELinBLUE** [comment]
Ah! I should have spotted that in the ps output. Your queue worker is only watching the `deployer-default` queue. That is only used for events, there is a `deployer-high` queue which is used for actual deployments and `deployer-low` which is used for things like notifications, server tests, emails etc

Take a look at https://github.com/REBELinBLUE/deployer/blob/master/examples/supervisor.conf

You need at least 2 separate workers, one listening to the default queue so that updates are broadcast to the client in realtime so that it can update the UI and one listening to the high/low queue. If you want to be able to run multiple deployments, tests etc at a time you can have multiple workers for the high/low queues (see line 4 of the supervisor config)

**Comment by cerw** [comment]
@REBELinBLUE exactly right, I have spoted it once i star reading supervisor config, I thought by default it will run all queue but i was wrong. Sorry to waste your time! Thanks for help. 
It seem you got inspired by envoyer.io a lot :) Which we are using for some time but looking into in-house solution, This one looks pretty good!

**Comment by REBELinBLUE** [comment]
Glad it here it works 👍 Yeah sort of, I started it about a week before envoyer was released, then refactored a lot of it as I preferred the way envoyer worked but at the time envoyer didn't work with gitlab which is what we were using at work, and the repos were on a private network anyway

**Comment by cerw** [comment]
@REBELinBLUE Yeah we use private gitlab too. 

at envoyer you can upload custom .env file which is then distributed to server. What is the workflow here? Do I need to set this as shared file ? Or you export each variable individually? 

Also I have noticed in Template it still need to as "deploy as" but each server has differnet user, can there be option to leave it empty so it will uses the server specified user? 

thanks

**Comment by REBELinBLUE** [comment]
"Files > Configuration Files" is where you would put the `.env` file

Do you mean in the before/after commands? You're right that should actually be optional, I'll get that fixed
