### ISSUE TITLE
node socket server exited itself

### ISSUE THREAD

**Issue by yekz** [REBELinBLUE/deployer#218]
sorry I'm not familiar with node, I can just report this information to you
I run node socket server by run `node socket server &`, but i found it will exit after a few hours later

**Comment by REBELinBLUE** [comment]
Hi

This is a common problem with node https://blog.nodejitsu.com/keep-a-nodejs-server-up-with-forever/

It is recommended that you use supervisor to ensure it keeps running, there is a config file in the examples folder. It also helps ensure the queue worker continues to rub
