### ISSUE TITLE
Permission denied on release directory

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#220]
- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.
### Expected behaviour

The deploying process should work
### Actual behaviour

The deployed fails on the "Install composer dependencies" step with error:
`bash: line 41: cd: /var/www/feedbacks/releases/20160520164752: Permission denied`
### More informations
- The SSH user is deploy
- This user owns the /var/www/feedbacks folder
- The "releases" folder is created with deploy:deploy rwxrwxr-x
- The "20160520164752" is created with deploy:deploy rw-rw-r--
- My code is properly checked out of Bitbucket in the "releases/20160520164752" folder
- Permission is denied because deploy user has no execution permission "x" on the "20160520164752" folder; if I add +x, deploy user may access the folder
### Environment info

Operating System: Ubuntu
PHP Version: 5.5.9
Node Version: 5.10.1
Database System: MySQL

Thanks a lot

**Comment by axeloz** [comment]
When editing file deployer/resources/scripts/deploy/ConfigurationFile.sh, I replaced
`chmod 0664 {{ path }}`
with 
`chmod 0774 {{ path }}`

It works now...

**Comment by REBELinBLUE** [comment]
Hmm, that is odd, `ConfigurationFile.sh` is not used for setting the permission on the release folder.

What do you have set as "Configuration Files" on the "Files" tab?

**Comment by axeloz** [comment]
So this is VERY odd indeed because that fixed my problem immediatly and the right permissions were given to the release folder. 

I have to tell you that I managed to make the deploy work without editing the configuration file. 
Then I moved on configuring the project, add persistent file, add steps like Laravel DB migration using artisan, ...
At this stage, the deploy failed because of the permission. I got confused as I made it work once. Then I found the fix I talked about. But it is very likely a problem related to the configuration I have added:

- Adding two commands after Composer:
  - db migration using PHP artisan
  - clearing Laravel cache
- Adding a persistent .env file for Laravel settings
- Adding one Heartbeat
- Adding one URL check

And that's it.

**Comment by REBELinBLUE** [comment]
Can you run `umask` and tell me what the output is? It should normally be `0022`

The permissions for me at set to the following on a completely new VM

```vagrant at web in /var/www
$ ls -Al
total 8
lrwxrwxrwx 1 deploy   32 May 21 17:31 latest -> /var/www/releases/20160521182740/
drwxr-xr-x 3 deploy 4096 May 21 17:27 releases/
drwxr-xr-x 4 deploy 4096 May 21 17:29 shared/

vagrant at web in /var/www
$ cd releases/

vagrant at web in /var/www/releases
$ ls -Al
total 4
drwxr-xr-x 10 deploy 4096 May 21 17:29 20160521182740/

vagrant at web in /var/www/releases
$ cd ../shared/

vagrant at web in /var/www/shared
$ ls -Al
total 20
-rw-r--r-- 1 deploy 1079 May 21 17:10 LICENSE.md
-rw-r--r-- 1 deploy 4822 May 21 17:10 README.md
drwxr-xr-x 6 deploy 4096 May 21 17:10 storage/
drwxr-xr-x 2 deploy 4096 May 21 17:10 upload/```

**Comment by axeloz** [comment]
I cannot run the command as I'm out of this office. 
I'll do it next monday. 
But clearly you wrote:

> drwxr-xr-x 10 deploy 4096 May 21 17:29 20160521182740/

I have not the same permissions on the release folder; I'm missing the X

**Comment by REBELinBLUE** [comment]
It's OK I can wait, that is why I want to see what `umask` returns

**Comment by axeloz** [comment]
Hello @REBELinBLUE , 
thank you for your patience, here is the output:

```
axel@dev:/var/www/feedbacks$ ls -Al
total 16
lrwxrwxrwx  1 deploy deploy   50 May 20 18:50 latest -> /var/www/feedbacks/releases/20160520184959
drwxrwxr-x+ 8 deploy deploy 4096 May 20 18:50 releases
drwxrwxr-x+ 2 deploy deploy 4096 May 20 17:43 shared
axel@dev:/var/www/feedbacks$ cd releases/
axel@dev:/var/www/feedbacks/releases$ ls -Al
total 48
drw-rw-r--+ 10 deploy deploy 4096 May 20 17:43 20160520174317
drwxrwxr--+ 11 deploy deploy 4096 May 20 18:01 20160520175816
drwxrwxr--+ 11 deploy deploy 4096 May 20 18:11 20160520181124
drwxrwxr-x+ 11 deploy deploy 4096 May 20 18:44 20160520184420
drwxrwxr-x+ 11 deploy deploy 4096 May 20 18:45 20160520184534
drwxrwxr-x+ 11 deploy deploy 4096 May 20 18:50 20160520184959
axel@dev:/var/www/feedbacks/releases$ cd ../shared/
axel@dev:/var/www/feedbacks/shared$ ls -Al
total 0
axel@dev:/var/www/feedbacks$ umask
0022
axel@dev:/var/www/feedbacks$ cd releases/
axel@dev:/var/www/feedbacks/releases$ umask
0022
```

**Comment by REBELinBLUE** [comment]
Oh wow, not sure how I totally missed your response 6 months ago 😮 Sorry about that. I assume you got it working?

**Comment by axeloz** [comment]
Hello,

No problem, yes it seems to be fixed now. 
Kind regards
