### ISSUE TITLE
URL check task fails after edition

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#221]
### Actual behaviour

The task seems confused. It display the new URL then the old URL then the new URL

### Steps to reproduce

- Add a URL check (ie: /auth/login)
- Edit the URL (ie: /auth/login2)
- Revert the URL (ie: /auth/login)

### Environment info
Operating System: Ubuntu
PHP Version: 5.9
Node Version: 5.1
Database System: MysQL

### Logs (see storage/logs/) or other output that would be helpful

see video attached

[bug.mov.zip](https://github.com/REBELinBLUE/deployer/files/274999/bug.mov.zip)

**Comment by axeloz** [comment]
I could not find a way to stop this. So I deleted the URL check and created a new one. 
It works now.
Thanks.

**Comment by REBELinBLUE** [comment]
What is the output of `curl --verbose URL` with the URL you are setting up?

**Comment by axeloz** [comment]
I cannot run the command right now as I'm not in the office. But
- the URL /auth/login does work and there is no reason CURL fails on it. Deployer also says this URL is working
- the URL /auth/login2 is a fake URL (I should have mentioned that at the first place): I wanted to test the deployer reaction when checking an invalid URL

It seems to be a conflict between two tasks: one for auth/login and one for auth/login2 as if the second one was not aborted despite my edition. Does it make sense?

**Comment by REBELinBLUE** [comment]
Oh I hadn't actually noticed that in the video that the URL was changing. Hmmm this chould be interesting...

**Comment by REBELinBLUE** [comment]
Well that was very easy to recreate

**Comment by axeloz** [comment]
Sorry if my post wasn't clear enough. 
Yes the URL is changing from old to new and to old again.
