### ISSUE TITLE
"Run as" user on the before/after command hooks should be optional

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#223]
So that it picks up the default user for the connection

**Comment by cerw** [comment]
👍

**Comment by cerw** [comment]
@REBELinBLUE so this will use the server default SSH user not jsut deploy user right?

**Comment by REBELinBLUE** [comment]
it will use the user who is set in the server, the placeholder for the user field has been changed from "deploy" to "server default"
