### ISSUE TITLE
Not getting notifications when Heartbeats breaks

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#224]
### Expected behaviour

When setting a 10 minutes heartbeats, Deployer should notify me when the heartbeat is offline since more than 10 minutes.

### Actual behaviour

The heartbeat is shown as "Healthy" when the last received ping was three days ago.

### Steps to reproduce

Create a 10 minutes heartbeats. Ping it once then stop

### Environment info
Operating System: Ubuntu
PHP Version: 5.6
Database System: MySQL

### More information

Screenshot attached
See the "Last check-in" date.

<img width="1017" alt="deployer" src="https://cloud.githubusercontent.com/assets/1597611/15474753/947dd752-2106-11e6-9ef8-53b553ca3431.png">

**Comment by REBELinBLUE** [comment]
Do you have the cronjobs configured as in (examples/crontab)[https://github.com/REBELinBLUE/deployer/blob/master/examples/crontab]?

**Comment by axeloz** [comment]
@REBELinBLUE thank you for your reply. I didn't know crontab were used. I thought that Deployer was using either the tasks queue with Beanstalk/Redis or the crontab.
It does work now. Sorry about my false bug report. 
Thanks

**Comment by REBELinBLUE** [comment]
Yeah crontabs have to be used for scheduled tasks, queues are used for things which are dispatched by a user action, i.e. deploying, testing servers etc
