### ISSUE TITLE
Deploy fails at Install Composer Dependencies step

### ISSUE THREAD

**Issue by dasuchin** [REBELinBLUE/deployer#226]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Expecting deploy to complete, including installing Composer dependencies.

### Actual behaviour
Deploy is failing at the Install Composer Dependencies step.

I see no output in the Process Output window other than the text that appears when sshing into the server. No errors in the log.

### Steps to reproduce

No steps aside from what was outlined in  the docs.

### Environment info
Operating System: OS X 10.11.3
PHP Version: 5.6.10
Node Version: 0.12.7
Database System: mysql
Database Version: 5.5.42

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).
No errors in the logs pertaining to this issue. I see debug output out of the generated commands it's running.

```
[2016-05-26 14:21:26] production.DEBUG: ssh -o CheckHostIP=no \
    -o IdentitiesOnly=yes \
    -o StrictHostKeyChecking=no \
    -o PasswordAuthentication=no \
    -o IdentityFile=LOCAL_PATH/deployer/storage/app/sshkeydDJ6k6 \
    -p 22 USER@HOST 'bash -s' << 'EOF'
        # Turn on quit on non-zero exit
        set -e
        cd REMOTE_URL

# If there is no composer file, skip this step
if [ -f REMOTE_URL/releases/20160526142123/composer.json ]; then
    # Check composer is installed
    composer="$(command -v composer)"
    if [ ! hash composer 2>/dev/null ]; then
        # If not, check for composer.phar
        composer="$(command -v composer.phar)"

        if [ ! hash composer.phar 2>/dev/null ]; then
            # If still not, check for composer.phar in the project path
            if [ ! -f REMOTE_URL/composer.phar ]; then
                # Finally, resort to downloading it
                curl -sS https://getcomposer.org/installer | php
                chmod +x composer.phar
            fi

            composer="php REMOTE_URL/composer.phar"
        fi
    fi

    cd REMOTE_URL/releases/20160526142123

    if [ -n "" ]; then
        $composer install --no-interaction --optimize-autoloader \
                          --prefer-dist --no-ansi --working-dir "REMOTE_URL/releases/20160526142123"
    else
        $composer install --no-interaction --optimize-autoloader \
                          --no-dev --prefer-dist --no-ansi --working-dir "REMOTE_URL/releases/20160526142123"
    fi
fi

cd REMOTE_URL/releases/20160526142123
EOF
  
[2016-05-26 14:21:27] production.DEBUG: ssh -o CheckHostIP=no \
    -o IdentitiesOnly=yes \
    -o StrictHostKeyChecking=no \
    -o PasswordAuthentication=no \
    -o IdentityFile=LOCAL_PATH/deployer/storage/app/sshkeydDJ6k6 \
    -p 22 USER@HOST 'bash -s' << 'EOF'
        # Turn on quit on non-zero exit
        set -e
        cd REMOTE_URL

# Remove the archive
if [ -f REMOTE_URL/2_20160526142123.tar.gz ]; then
    rm REMOTE_URL/2_20160526142123.tar.gz
fi

# Remove the release directory
if [ -d REMOTE_URL/releases/20160526142123 ]; then
    rm -rf REMOTE_URL/releases/20160526142123
fi
EOF
  
[2016-05-26 14:21:28] production.DEBUG: bash -s << 'EOF'
    # Turn on quit on non-zero exit
    set -e
    cd LOCAL_PATH/deployer/storage/app/mirrors/REPO_URL.git

git tag --list --no-column
EOF
  
[2016-05-26 14:21:28] production.DEBUG: bash -s << 'EOF'
    # Turn on quit on non-zero exit
    set -e
    cd LOCAL_PATH/deployer/storage/app/mirrors/REPO_URL.git

git branch --list --no-column
EOF
  
```

**Comment by dasuchin** [comment]
Turns out Composer wasn't installed on my server for some reason.

**Comment by REBELinBLUE** [comment]
hmm, that is strange, if it can't find composer it should download composer into the project directory and run it from there. Could you try running `curl -sS https://getcomposer.org/installer | php` on the server on tell me what the output is?

**Comment by dasuchin** [comment]
It was able to download it, so not sure why it would error out. Not a huge deal, just switched to the server that had Composer installed on it already.
