### ISSUE TITLE
update broken

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#229]
when i run `php artisan app:update`

it throws error

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Call to undefined method Illuminate\Queue\RedisQueue::getPheanstalk()
```

Thanks.

**Comment by REBELinBLUE** [comment]
Crap, I forget to check in the updater for people who weren't using beanstalk. I'lll push out a fix tomorrow but for now you can just comment out these lines

https://github.com/REBELinBLUE/deployer/blob/master/app/Console/Commands/InstallApp.php#L646-L653

**Comment by lorvent** [comment]
That did the trick :D
