### ISSUE TITLE
Autodeploy / WebHook / PHPCI

### ISSUE THREAD

**Issue by cerw** [REBELinBLUE/deployer#231]
Hello got few questions:

1) How to trigger deployment via Hook from gitlab/github? Atm it seem to check for for new commit via cron, but never does anything? 

2) WebHook woudl be nice, Similar like envoyer, which uses GItLab API to trigger that.. 

3) How to integrate with PHPCI on success build -> deploy ..

thanks

**Comment by REBELinBLUE** [comment]
1) the cronjob are for checking URLs, checking heartbeats have happened and for general maintenance not for triggering deployments

2) take a look at the commands tab, the we hook URL is there ;)

3) PHPCI has a Deployer plugin which you just need to add to the "success" section of your yml file with the webhook URL. Take a look at their wiki, there should be a page for the plugin

Stephen Ball
stephen@rebelinblue.com

**Comment by cerw** [comment]
Thank you so it seem you prefer CI -> CD only and bypass the each commit triggers deploy, makes sense. 

I have tried deployer plugin and (which is easy as we using phpci.yml) and it worked ! 

How about webhook from deployer to URL when deploys finishes? Do you have that in roadmap? (atm I catch slack notification from envoyer and parse it to my neeeds) 

Loving deployer + phpci combo!

**Comment by REBELinBLUE** [comment]
Well if you use the hook URL in github it will trigger a deploy for each
commit (well, the latest commit for each push) :)
 
Had not thought about adding a webhook to call on deployment, that makes
sense. You could sort of do it by adding a custom command "After
Activate" to use curl to call a URL but that will obviously only work on
success. I am planning to refactor the notifications to add hipchat and
let you select under which conditions a notification should be sent
(i.e. at the moment email notifications are only sent for deployments;
slack notifications are sent under multiple conditions but there is no
way to say something like send to this channel for deployments, send to
this channel for heartbeats etc) so adding a callback URL as another
type of notification would make sense and shouldn't be much work.
 
Thanks :) @dancryer and I have talked about how we'd integrate them
better, i.e. share user database etc but neither of us have had much
time to look into it more. I joked about renaming Deployer to PHPCD as
there already is a product called deployer
 
-----------------
Stephen Ball
stephen@rebelinblue.com
 
 
On Thu, 2 Jun 2016, at 10:15 AM, Petr Cervenka wrote:
> Thank you so it seem you prefer CI -> CD only and bypass the each
> commit triggers deploy, makes sense.
> I have tried deployer plugin and (which is easy as we using phpci.yml)
> and it worked !
> How about webhook from deployer to URL when deploys finishes? Do you
> have that in roadmap? (atm I catch slack notification from envoyer and
> parse it to my neeeds)
> Loving deployer + phpci combo!
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/REBELinBLUE/deployer/issues/231#issuecomment-223238466
  2. https://github.com/notifications/unsubscribe/ACC2pBmKXdJlDJJ6g0a1WO3b7TF1bGYIks5qHp83gaJpZM4IsI_D
