### ISSUE TITLE
Customize webhook integration

### ISSUE THREAD

**Issue by eduebrasil** [REBELinBLUE/deployer#235]
This is actually an enhancement request.
What I propose is allow user to customize the events for proper webhook triggering.
If I understand it correctly the deploy is triggered when you push to repository only. We are using Bitbucket and you can choose another events for webhooks like merge a pull request.
### Expected behaviour

Customize integration events hook points.
### Actual behaviour

Deployer listens only for push events
### Steps to reproduce
- Setup a deploy
- Setup Bitbucket webhook
- If it's not a push deployer ignores it

**Comment by REBELinBLUE** [comment]
I'll take a look, shouldn't be too difficult, just a case of updating https://github.com/REBELinBLUE/deployer/blob/master/app/Http/Webhooks/Bitbucket.php to listen for `pullrequest:fulfilled`

https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Merged

**Comment by REBELinBLUE** [comment]
This was done a long time ago, should have closed this issue then
