### ISSUE TITLE
Newly pushed branches not being displayed for deployment

### ISSUE THREAD

**Issue by digster** [REBELinBLUE/deployer#240]
While clicking on deploy, if the option to deploy the other branches is selected, any newly pushed branches after the last deployment are not displayed.
If any of the existing branch is then deployed, the git branch list gets updated and the new branches get available to deploy. 
Ideally the git branch list should get periodically updated or an option should be given to explicitly do so.

**Comment by REBELinBLUE** [comment]
Do you have the cronjob running? It should update the list of available branches periodically 

Stephen Ball
stephen@rebelinblue.com

**Comment by digster** [comment]
Yes, the cronjob and supervisor tasks, both are running.

**Comment by criography** [comment]
I was actually about to ask you about this. I have no clue how much of a hassle would that be but something like a 'sync branches' button would be a nice falback and useful addition ot the interface.
![branch-sync](https://cloud.githubusercontent.com/assets/619115/16522527/67edcfd6-3f96-11e6-9213-77ae4802dbdc.png)

**Comment by REBELinBLUE** [comment]
Good idea @criography 

@digster could you try running `php artisan deployer:update-mirrors` and tell if you that fixes the problem? If not, is there any output, and if not can you share the log from `storage/logs/cli-YYYY-MM-DD.log`

**Comment by digster** [comment]
Turns out it was an issue with access permissions and fixing the same solved it. Although, the behavior of the cron script is unpredictable sometimes. Didn't seem to sync the deleted branches properly.
A dedicated sync button though sounds like a good idea.

**Comment by REBELinBLUE** [comment]
hmm, that is odd, it uses `git clone --mirror` to keep a copy of the remote repository. which should remove branches which have been deleted. Can you tell me which version of git is installed on your deployer server, `git --version`

Thanks
