### ISSUE TITLE
Change to use event broadcasting

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#25]
https://mattstauffer.co/blog/broadcasting-events-with-pusher-socket-in-laravel-5.1 instead of polling ajax

**Comment by iflamed** [comment]
@REBELinBLUE  Hi, I'm running the code from the master. How i enable the event broadcasting? Just run ``` node socket.js ```?

**Comment by iflamed** [comment]
@REBELinBLUE  And I got a error ```PHP Fatal error:  Class 'Pusher' not found in /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php on line 123```.

**Comment by REBELinBLUE** [comment]
Sorry I need to write some instructions. Laravel defaults to using pusher. Take a look at the .env.example there are 2 new lines

BROADCAST_DRIVER=redis

and

SOCKET_URL=http://deploy.app

if you are using nginx you can use nginx to proxy the websocket connection (see the  location /socket.io and upstream websocket in nginx.conf.example) so SOCKET_URL just needs to be the same as APP_URL. If you aren't using nginx you'll need to set SOCKET_URL to include the port 6001

**Comment by iflamed** [comment]
And, You need update the composer.lock and composer.json to add the pusher package.

**Comment by REBELinBLUE** [comment]
No I'm not using pusher, that is what laravel defaults to if you don't have BROADCAST_DRIVER=redis

**Comment by iflamed** [comment]
Oh, It's so wired ! I run the queue on the master and the error of pusher not found. But I run composer install there nothing to be installed. So I run the command ```composer require pusher/pusher-php-server:~2.0```, then queue don't report any error.

**Comment by iflamed** [comment]
Sorry, I just got what you say. I forgot to update my .env file and add the code ```BROADCAST_DRIVER=redis```;

**Comment by REBELinBLUE** [comment]
👍
