### ISSUE TITLE
Ship with pre-built assets

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#251]
Shipping without NPM is a huge bonus to users. NPM is slow and makes Deployer harder to get started with.

**Comment by REBELinBLUE** [comment]
Uh, the release branch/tags have the assets prebuilt? https://github.com/REBELinBLUE/deployer/tree/release/public/build

But NPM is still needed for the node socket server stuff, hopefully though with Laravel 5.3 and Laravel echo I will be able to easily offer the ability to switch between socket.io and pusher for those who don't want to install & run a node server.

**Comment by jbrooksuk** [comment]
Of course. My bad!

**Comment by jbrooksuk** [comment]
Also, will you be at Laracon US?

**Comment by REBELinBLUE** [comment]
Sadly not, you?

**Comment by jbrooksuk** [comment]
Yeah :)
