### ISSUE TITLE
usort(): Array was modified by the user comparison function

### ISSUE THREAD

**Issue by postfriday** [REBELinBLUE/deployer#258]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Tried to open project dashboard (/projects/1), expected to see dashboard.

### Actual behaviour

ErrorException in Project.php line 414:
usort(): Array was modified by the user comparison function

### Steps to reproduce

New instance of the Deployer with one project.
Opening project dashboard after first manual deploy generates an exception.

### Environment info
Operating System: Ubuntu 14.04.4
PHP Version: 5.6.23
Node Version: 4.4.7
Database System: MySQL
Database Version: 5.5.50

### Logs (see storage/logs/) or other output that would be helpful

[2016-08-11 12:46:12] production.ERROR: exception 'ErrorException' with message 'usort(): Array was modified by the user comparison function' in /var/www/src/app/Project.php:414
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'usort(): Array ...', '/var/www/deploy...', 414, Array)
#1 /var/www/src/app/Project.php(414): usort(Array, Object(Closure))
#2 /var/www/src/app/Http/Controllers/DeploymentController.php(75): REBELinBLUE\Deployer\Project->tags()
#3 [internal function]: REBELinBLUE\Deployer\Http\Controllers\DeploymentController->project('1')
#4 /var/www/src/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#5 /var/www/src/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('project', Array)
...

**Comment by REBELinBLUE** [comment]
Hmm, I shall take a look at this after I finish work

**Comment by REBELinBLUE** [comment]
This seems to be a bug in PHP

http://stackoverflow.com/questions/3235387/usort-array-was-modified-by-the-user-comparison-function?answertab=votes#tab-top

Because the `usort` function throws an exception even though it is caught. I will suppress it

**Comment by REBELinBLUE** [comment]
Can you give me the output of `git tag -l` for project 1 in deployer?

**Comment by postfriday** [comment]
```
root@de-phpci-01:/var/www/src$ git tag -l
0.0.1
0.0.10
0.0.11
0.0.12
0.0.13
0.0.14
0.0.15
0.0.16
0.0.17
0.0.18
0.0.19
0.0.2
0.0.20
0.0.21
0.0.22
0.0.23
0.0.24
0.0.25
0.0.26
0.0.27
0.0.28
0.0.29
0.0.3
0.0.30
0.0.31
0.0.32
0.0.33
0.0.34
0.0.35
0.0.36
0.0.37
0.0.4
0.0.5
0.0.6
0.0.7
0.0.8
0.0.9
```

**Comment by REBELinBLUE** [comment]
Sorry, I don't mean deployer itself but the repository for the project you have set up in deployer

**Comment by postfriday** [comment]
Sorry, my bad.

```
0.1.1
125
135
404
bugfix
push-world-integration
push-world-integration-manifest
r.js
stats-platforms
table-tfoot
```

**Comment by REBELinBLUE** [comment]
Thanks, I have managed to recreate the issue with that data, only happens prior to PHP 7
