### ISSUE TITLE
Install Composer Dependencies fails with Rsync error when running deployment

### ISSUE THREAD

**Issue by alex-osborn** [REBELinBLUE/deployer#260]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Deployment should run, set up directories as expected, then move on to installing composer dependencies.

### Actual behaviour

Deployment is failing at Install Composer Dependencies.

Errors in the "view the output" logs are:
```
rsync: change_dir#3 "/home/innocentorders/container/application/releases/20160820142357" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.0]
[120.138.22.13]: rsync: change_dir#3 "/home/innocentorders/container/application/releases/20160820142357" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(712) [Receiver=3.1.0]
```

Connection to the server appears correct (Clicking Test the server connection from the servers tab)

On the server, the application directory looks like:

```
drwxr-x--- 3 innocentorders innocentorders    4096 Aug 20 14:28 ./
drwxr-xr-x 6 root           root              4096 Jul 20 10:15 ../
-rw-r--r-- 1 innocentorders innocentorders 1481332 Aug 20 14:26 3_20160820142638.tar.gz
drwxr-x--- 2 innocentorders innocentorders    4096 Jul 20 10:15 public/
```

Looks like the releases directory is unable to be created, then rsync fails? However I am not sure where to see any errors on the failure in the logs.

### Steps to reproduce

- Set up project in Deployer
- Set up server for project, click test connection button (passes)
- Click deploy
- Create New Release passes
- Install Composer Dependencies fails, with message above.

### Environment info
Operating System: Ubuntu 14.04.3 LTS
PHP Version: PHP 7.0.8 (cli)
Node Version: v4.4.4
Database System: mysql
Database Version: 5.6.30

### Logs (see storage/logs/) or other output that would be helpful

Attached.
[cli-2016-08-20.log.zip](https://github.com/REBELinBLUE/deployer/files/428096/cli-2016-08-20.log.zip)

**Comment by REBELinBLUE** [comment]
Hmm, this is odd. Did that the entire log for 2016-08-20? The error is for 14:23:57 but the logs seem to be a path for 14:38:38

**Comment by alex-osborn** [comment]
Ah - I may have copied the wrong log from the UI. On my install there are a number of deploys that all failed with the same error.

I cleaned the server logs before rerunning a deploy to be sure I was sending the right lines from there.

![screenshot-deploy idesignmedia co nz 2016-08-22 11-23-21](https://cloud.githubusercontent.com/assets/880420/17840420/239d945e-685b-11e6-9d23-699ee13f12d1.png)

**Comment by REBELinBLUE** [comment]
Sorry for the late reply. I see you have a .env file being created, that is where it appears to be failing looking at those logs.

 Can you try removing that from the files tab?

**Comment by alex-osborn** [comment]
Thanks, that has stopped the deployment failing - all steps show up as completed. The actual deployments themselves are not running correctly - but I can now confirm this is likely to do with the environment the app is running in. 

From my tests, any script running remote commands over SSH (RunScriptOverSSH.sh etc) is connecting - but no commands from the script are run, and no output is returned. I have been able to reproduce this by running the SSH scripts manually. My hosting provider is using a docker container based setup, so I will follow up with them, and also set up the app on a separate server to retest.

**Comment by REBELinBLUE** [comment]
Hmm, that is very odd. Not sure all the scripts running remote commands are failing though, otherwise the create new release step would fail as it transfers an archive to the server, oddly enough using the same script as it used to create the .env file (line 59-70 of your log file but that is successful, line 102-113 is the same command creating the .env file and that fails because the next step is to remove the archive and release directory which is the cleanup that happens on failure).

I will have to try setting up a docker container myself, will have to be on sunday though. Don't suppose you have the dockerfile used to create it?

**Comment by alex-osborn** [comment]
Quick update for reference. Isolated a test case and send to my hosting provider who confirmed this was an edge case with their containers. They fixed the issue and now the deployments run as expected. I don't have access to the dockerfile - this is abstracted away as part of their platform.

Thanks for your help!
