### ISSUE TITLE
Event broadcast for log updates can quickly fill the beanstalkd queue

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#262]
Reported by @alasdairw

The changes for the ServerLog so that each log line update is broadcast can quickly fill the Beanstalkd queue faster than the events are consumed so it starts results in JOB_TOO_BIG errors

**Comment by cgi-cgi** [comment]
Run beanstalkd with key `-z 134217728` (or another, greater than default) solved this problem for me.

**Comment by alasdairw** [comment]
Thanks, but at one point we were testing with a 512MB threshold, and still hitting the error, and that wasn't even deploying our largest repo.  Upping the limit is certainly an option, but for large repos, there's a threshold on just how far it's safe to just *keep* upping it. :)

**Comment by REBELinBLUE** [comment]
Note to self, can also happen when broadcasting models with large amounts of data, i.e the log is very big
