### ISSUE TITLE
Projects using git submodules are not supported 

### ISSUE THREAD

**Issue by alex-osborn** [REBELinBLUE/deployer#264]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Git submodules are included in the project archive created during deployment the local mirror.

### Actual behaviour

Git submodules are not included via `git archive`.

### Steps to reproduce

Run a deployment.

--

Ran into an issue I wasn't expecting when deploying a project - the git archive command does not support submodules.

From a little research, the accepted method to attack this is to is a wrapper. One example:
https://github.com/meitar/git-archive-all.sh/wiki

What do you think about this? If you're happy this would be in scope for deployer, I can work on a pull request? 

CreateReleaseArchive.sh could just be updated directly, or another approach would be to create a separate script, and hide this behind a UI toggle when setting up the project, i.e. "Include GIT submodules?".

**Comment by REBELinBLUE** [comment]
Ah, bugger, I forgot to check that when switching to using git-archive! I will take a look

**Comment by REBELinBLUE** [comment]
OK been looking into this, turns out it'll take a bit of work as the archive uses a mirror of the repo (a bare repository) so can't init the submodules when creating the archive. I will have to look into rewriting how the archive is creted
