### ISSUE TITLE
deployments are failing on npm install step

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#271]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.
- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.
### Expected behaviour

deployment should run properly
### Actual behaviour

Its working fine on all other servers but recently i have created a new server wth ubuntu 16,
in this server, in `npm install` step, its failing and its not giving clear info also.

when i look at response, its truncated with npm install info so i am not able to trace it properly

I know this is not a bug with deployer but thought you may know any solution for it.
### Steps to reproduce

_If your issue requires any specific steps to reproduce, please outline them here._
### Environment info

Operating System:
PHP Version:
Node Version:
Database System:
Database Version:
### Logs (see storage/logs/) or other output that would be helpful

http://pastebin.com/PxaJEJMm

**Comment by REBELinBLUE** [comment]
Sorry, but unwell recently so haven't been online.

Hmm, that is odd. What type of column is `output` on the `server_logs` table? I was sure I changed it to prevent it being truncated

Could you change the command to send the output to a file, i.e. `npm install > /var/www/deployer/npm-log.txt 2>&1` and then check the file to see the full output?

**Comment by lorvent** [comment]
How are you feeling now?

sad to know you are unwell, i can sense that from commits on repo...

output field is longtext.

deployment may be failing because of an error in my gulpfile.js but before it used to show complete log so i can findout the error but now log is bring truncated

**Comment by REBELinBLUE** [comment]
Better thanks, although still not 100% >_<

Hmm, not sure it is being truncated then..... LONGTEXT has a limit of 4,294,967,295 bytes, i.e. 4GB 😂 MEDIUMTEXT probably would have been enough, 16MB.

Just noticed the entry finishes with "Closed" so sounds like something on the server may be killing long running processes or maybe the NPM process is hinting a memory limit and getting killed? Does the log in the DB actually contain the closed? Could you try with the piping it to a log, be interesting to see if it is because it because of the length of the log causing PHP to hint it's memory limit

**Comment by REBELinBLUE** [comment]
Did you have any luck piping the output to file?

**Comment by lorvent** [comment]
Hi,
looks like whenever there is an error with gulp/bower, its behaving like that...
since we fixed all bugs...i gave up on this.

but if you are interested in output file, i can send you.

**Comment by bbashy** [comment]
Is it just a timeout because the command takes longer on this new server?

**Comment by REBELinBLUE** [comment]
Closing for now, feel free to reopen it
