### ISSUE TITLE
Persistent Folder creating multiple folders?

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#273]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Symlinks a folder/file (defined) to the shared directory

### Actual behaviour

I'm trying to link the storage folder (Laravel) and have it persistent over each release. It seems to be duplicating the folder on each deploy like it's copying it then symlinking.

![](https://d.pr/i/CMui/2gRLWcnL.jpg)

I have this folder structure;

```
shared
->storage
-->storage (created each deploy)
```
The symlink works correctly and points to the 1 level deep folder.
```
# ls -lah
storage -> /var/www/project/shared/storage
```

### Steps to reproduce

- Add project.
- Add folder (that exists in the repo) to files tab in deployer.
- Deploy

### Environment info
_For both deployer and web servers_
Operating System: Debian Jessie 64
PHP Version: PHP 7.0.11-1

**Comment by REBELinBLUE** [comment]
Hmm, interesting. Which distro/version of Linux are you using on the server you are deploying to?

**Comment by bbashy** [comment]
Debian Jessie 64
PHP 7.0.11-1

Had it on two different servers now. Could be something I'm doing wrong as the duplicate folder isn't ever used and looked like the default in Laravel (with no cache/session files).

**Comment by REBELinBLUE** [comment]
Interesting, that sounds like exactly the same setup as my test VMs. i'll have a play around this evening and see if I can recreate it

**Comment by bbashy** [comment]
I believe I tried both `/storage/` and `storage/` but you could test that also.

Thanks for the swift response :+1:

**Comment by bbashy** [comment]
Not sure what you've looked into yet but this could be it: https://github.com/REBELinBLUE/deployer/blob/master/resources/scripts/deploy/ShareDirectory.sh#L3

**Comment by bbashy** [comment]
Definitely that copy command. Getting this when I set shared folder to nginx user/group.

```
cp: cannot create directory ‘/home/user/project/shared/storage/storage’: Permission denied
```

**Comment by REBELinBLUE** [comment]
Hey, sorry for the late reply, I have been on holiday the last few weeks without a net connection. I will take a look at this issue this evening

**Comment by bbashy** [comment]
No problem! It's not made deployments fail but an interesting issue.

If you need any logs or info, let me know.
