### ISSUE TITLE
Install dev dependencies does not work with older versions of composer due to using a 1.2+ flag

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#275]
Getting this error when deploying
```
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-suggest" option does not exist.               
                                                          
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] []...
```
This is with "install dev dependencies" option ticked in create project modal.

![](https://d.pr/i/CGXw/5RVIOR8W.jpg)

**Comment by bbashy** [comment]
Didn't work in `Composer version 1.1.3 2016-06-26 15:42:08` but does in latest `Composer version 1.2.1 2016-09-12 11:27:19`?

**Comment by REBELinBLUE** [comment]
This is an option which was added in composer 1.2 https://github.com/composer/composer/blob/master/CHANGELOG.md#120-rc---2016-07-04

To be honest I have never known anyone not to keep their version of composer up-to-date, I will see how difficult it is to have the script check for the option before using it

**Comment by bbashy** [comment]
Makes sense. I do try and keep them updated but on this environment I forgot.

Thanks!
