### ISSUE TITLE
node socket.js with SSL

### ISSUE THREAD

**Issue by uLow** [REBELinBLUE/deployer#276]
Hi there!
I'm trying to run `node socket.js` as daemon with SSL certificate, but it's asking for certificate PEM password, so i can't start it like `node socket.js &` or using `supervisord`. 

Could you advice how to achieve that?

**Comment by REBELinBLUE** [comment]
You'd need to remove the password from the key https://futurestud.io/tutorials/how-to-remove-pem-password-from-ssl-certificate

**Comment by uLow** [comment]
Of course it's not a solution. Since my company is under PCI DSS licence, we can't remove password from the key. Is there another workaround?

**Comment by REBELinBLUE** [comment]
Edit

https://github.com/REBELinBLUE/deployer/blob/master/socket.js#L20

and add `passphrase` to the object, i.e so you have

```
    var ssl_conf = {
        key:  (process.env.SOCKET_SSL_KEY_FILE  ? fs.readFileSync(process.env.SOCKET_SSL_KEY_FILE)  : null),
        cert: (process.env.SOCKET_SSL_CERT_FILE ? fs.readFileSync(process.env.SOCKET_SSL_CERT_FILE) : null),
        ca:   (process.env.SOCKET_SSL_CA_FILE   ? fs.readFileSync(process.env.SOCKET_SSL_CA_FILE)   : null),
       passphrase: 'mypassword'
    };
```

https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

That seems rather ridiculous to me personally as that means the password is being stored on disk in plaintext 😧

I'll see about add a `SOCKET_SSL_KEY_PASSPHRASE` option
