### ISSUE TITLE
How to run projects cronjob and queue's

### ISSUE THREAD

**Issue by Cannonb4ll** [REBELinBLUE/deployer#277]
Whenever I deploy a project it gets a unique project path url, which is logic, but in my case I need to have the cronjob running from the project root folder. Also a supervisor has to run, its a laravel project.

How would I go about setting this up?

**Comment by REBELinBLUE** [comment]
If you have the base folder as `/var/www/myproject` it will deploy to `/var/www/releases/20161028101010` for example, but there is a symlink `/var/www/latest` to the current release so you should use that path for cronjobs etc

Is that what you mean?

**Comment by Cannonb4ll** [comment]
Totally forgot.... you are the best, thanks mate!

**Comment by REBELinBLUE** [comment]
No worries, glad to help :)

**Comment by Cannonb4ll** [comment]
I would like to reopen this ticket due to a supervisor problem.

Whenever I deploy a new project supervisor does not run the project anymore (other projects are just fine). When I restart the supervisor service then it runs just fine. How would I go about fixing this? (Laravel project)

**Comment by REBELinBLUE** [comment]
Sorry I missed that you'd reopened it

**Comment by REBELinBLUE** [comment]
You would need to run either `sudo supervisorctl restart <jobname>` or `sudo service supervisor restart` obviously this isn't possible as you'd need to enter a password.

However you can use the sudoers file to allow the user to run a particular command without the password. For example, on my server I have `/etc/sudoers.d/deployer` with the following content


```
deploy ALL=NOPASSWD:/usr/sbin/service php7.0-fpm restart
```

This allows the "deploy" user to run the command `sudo /usr/sbin/service php7.0-fpm restart` without being prompted for the password

So you'd have something like

```
deploy ALL=NOPASSWD:/usr/bin/supervisorctl restart <jobname>
```

See https://help.ubuntu.com/community/Sudoers for more info although if you are using something other than Ubuntu or Debian the process may be slightly different

**Comment by REBELinBLUE** [comment]
Hope that answered your question. Closing for now, feel free to reopen it
