### ISSUE TITLE
Undefined index: DB_TYPE

### ISSUE THREAD

**Issue by uLow** [REBELinBLUE/deployer#278]
after running `php artisan app:install` i get 

```
[ErrorException]
  Undefined index: DB_TYPE
```

on latest `0.0.39` release

**Comment by uLow** [comment]
This issue causes that `deployer` is not finishing install and nothing works further.

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
`app-69de1cc69c.js:1 Uncaught TypeError: Cannot read property 'id' of undefined`
and so on...

**Comment by uLow** [comment]
`0.0.38` works great meanwhile...

**Comment by REBELinBLUE** [comment]
Hmm, very odd, I will take a look when I get home from work this evening... Can you post the content of `.env` and `.env.prev` (obviously hide the passwords)

**Comment by uLow** [comment]
emm... i have reverted all changes back to 0.0.38, but you can reproduce that error by simply doing all usual install steps. Nothing more or less.

**Comment by REBELinBLUE** [comment]
That is weird because I ran the installer on my own install. You should still have `.env.prev` though as `.env` gets backed up to though as soon as you try to run the installer

**Comment by REBELinBLUE** [comment]
@dancryer @jbrooksuk Don't suppose either of you have had this if/when you've upgraded? I did a fresh install on 0.0.38 and then upgraded and it worked fine.

@uLow I don't suppose you used the `refactor/react` branch at any point did you?

**Comment by riyono** [comment]
Experienced the same issue just now, seems the error happen in one of the migrations: 2016_09_06_195043_add_targetable_attributes.php line 85 (and potentially 89 and 92)

Submitted a pull request which kind of solve [let user proceed with app:install per normal], but I guess it is not solving the root cause ($_ENV is not available yet when running the migrations?).

**Comment by REBELinBLUE** [comment]
Interesting, could you post your `.env`?

**Comment by riyono** [comment]
```
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:xxXX8x8+8XxxxXxxXXx8X8xxx8XXXxxX8xXXx88/x88=
APP_URL=https://deployer.xxxxxxxxxxxx.com
APP_TIMEZONE=Asia/Singapore
APP_LOCALE=en
APP_THEME=green
APP_LOG=daily

JWT_SECRET=xX78xXXxxxxxXxX88x8XXxxXxxXxxXxxx

SOCKET_URL=http://localhost
SOCKET_PORT=6001

DB_TYPE=mysql
DB_HOST=localhost
DB_DATABASE=deployer
DB_USERNAME=deployer
DB_PASSWORD=XXx%XX88x8x,X)x$xxxXXxxxXxXxxxX8

MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=xxxxx
MAIL_PASSWORD=XX.8XxXXxXxXX8xxXxxXXx8xX.xXxx8xXXXxXX8X8XXX-xXxx8X8X8x-xXxX8X8XXXXXX
MAIL_FROM_NAME=Xxxxxxxx
MAIL_FROM_ADDRESS=xxxxxxxx@xxxxxxxxxxxx.com

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_DATABASE=0

QUEUE_HOST=localhost
QUEUE_DRIVER=beanstalkd

CACHE_DRIVER=file
SESSION_DRIVER=file
IMAGE_DRIVER=gd
```

Oh, earlier, I had an issue with truncated database password (when the password contains an equals symbol "=" in it). But I think that is a separate issue.

**Comment by uLow** [comment]
@REBELinBLUE my `.env`:
```
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:*****
APP_URL=http://************
APP_TIMEZONE=Europe/Riga
APP_LOCALE=en
APP_THEME=green
APP_LOG=daily

JWT_SECRET=*****************

SOCKET_URL=http://*********:6001
SOCKET_PORT=6001
SOCKET_SSL_KEY_FILE=*************
SOCKET_SSL_CERT_FILE=*************
SOCKET_SSL_CA_FILE=*************

DB_TYPE=mysql
DB_HOST=localhost
DB_DATABASE=deployer
DB_USERNAME=deployer
DB_PASSWORD=************

MAIL_DRIVER=sendmail
MAIL_FROM_NAME=Deployer
MAIL_FROM_ADDRESS=deployer@***********

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_DATABASE=0
REDIS_PASSWORD=null

QUEUE_DRIVER=beanstalkd
QUEUE_HOST=localhost
QUEUE_PORT=11345

CACHE_DRIVER=file
SESSION_DRIVER=file
IMAGE_DRIVER=gd
```

and i don't have `.env.prev`

**Comment by REBELinBLUE** [comment]
Thanks. Yeah sorry it deletes the `.env.prev` if the resulting `.env` file is no different to the `.env` (i.e. it copies it to `.env.prev`, updates `.env` with any new fields from the example file and then compares `.env` and `.env.prev` and removes it the `.env.prev` if it is the same)

**Comment by REBELinBLUE** [comment]
if you edit `database/migrations/2016_09_06_195043_add_targetable_attributes.php` and after the `<?php` line add `$_ENV['DB_TYPE'] = 'mysql'; (or pgsql or sqlite) it should allow the migrations to run correctly at least.

Still trying to figure out what is actually happening

**Comment by gauthier** [comment]
@REBELinBLUE thanks for the clarification. I can't wait for a stable fix ;)

**Comment by REBELinBLUE** [comment]
Busy couple of evenings. I shall be spending tomorrow evening investigating and (hopefully) fixing

![](http://i.giphy.com/26ufkAIaEOMx3610s.gif)

**Comment by obayesshelton** [comment]
I think this is also an issue with the **database.php** it doesn't seem to pick the .env variable up

**Comment by REBELinBLUE** [comment]
Hmm that is weird as that is part of Laravel itself. Could you try running `php artisan tinker` and then at the prompt type `$_ENV` and see if it outputs the values from the `.env` file

**Comment by REBELinBLUE** [comment]
I may have a fix, still investigating though, problem is I can't actually recreate this issue so far

Can you tell me your environments, i.e. which version of PHP, whether you are using php-fpm, sapi etc (not that it should matter) and what the values of `error_reporting` and `display_errors` is for the CLI version of PHP.

Also, could someone give me a DB dump, but just the structure not the data. You can do this with something like the following

`$ mysqldump -d -h localhost -u DBUSERNAME -pDBPASSWORD DBNAME > dumpfile.sql`

Thanks

**Comment by REBELinBLUE** [comment]
OK I have managed to recreate the issue

**Comment by REBELinBLUE** [comment]
Can someone try the `bug/278` branch and see if that works?

You may need to run the following query

```sql
ALTER TABLE commands DROP COLUMN target_id;
ALTER TABLE commands DROP COLUMN target_type;

ALTER TABLE variables DROP COLUMN target_id;
ALTER TABLE variables DROP COLUMN target_type;

ALTER TABLE config_files DROP COLUMN target_id;
ALTER TABLE config_files DROP COLUMN target_type;

ALTER TABLE shared_files DROP COLUMN target_id;
ALTER TABLE shared_files DROP COLUMN target_type;
```

To clean up the mess that the DB was left in after the failed migration.

You should backup the DB before with

```shell
$ php artisan db:backup
```

**Comment by ValerioOnGithub** [comment]
I have tried to install the app from `bug/278` branch and the app has been successfully installed.

**Comment by REBELinBLUE** [comment]
That is great to hear, did you have the issue with the upgrade previously or was it a fresh install

**Comment by ValerioOnGithub** [comment]
It was the fresh install.

**Comment by axeloz** [comment]
Hello all, 

just did a fresh install and same problem here. I used @REBELinBLUE's cheat, the installation worked but I am now stuck on login with error :

`[2016-11-18 11:17:54] production.ERROR: exception 'InvalidArgumentException' with message 'Database (/var/www/deployer/database/database.sqlite) does not exist.' in /var/www/deployer/vendor/laravel/framework/src/Illuminate/Database/Connectors/SQLiteConnector.php:34`

It seems related to the DB_TYPE again. My .env file :


APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:yHs9bBPBg7h8sYZ0tj447G+hJGiFc/7TrxPmkWxRU=
APP_URL=http://deploy.xxxxx.io
APP_TIMEZONE=Europe/Paris
APP_LOCALE=en
APP_THEME=green
APP_LOG=daily
JWT_SECRET=1MZxUpnu7rrNSwKmP75bhZPoZ30zRNHh
SOCKET_URL=http://deploy.xxxx.io
SOCKET_PORT=6001
DB_TYPE=mysql
DB_HOST=localhost
DB_DATABASE=deployer
DB_USERNAME=deployer
DB_PASSWORD=KD2kcjs2kjs29jvpm2
MAIL_DRIVER=mail
MAIL_FROM_NAME=Deployer
MAIL_FROM_ADDRESS=deployer@xxxx.io
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_DATABASE=0
QUEUE_HOST=localhost
QUEUE_DRIVER=beanstalkd
CACHE_DRIVER=file
SESSION_DRIVER=file
IMAGE_DRIVER=gd


Thanks a lot

Axel

**Comment by REBELinBLUE** [comment]
Hmm, that is odd, can you try

```bash
$ php artisan config:clear
```

to remove the cached configuration?

I may end up just merging the fix over the weekend, although I am 99% sure it works for people with the previous failed upgrade I am not able to test it without someone providing me the DB dump as I have still not been able to recreate the issue myself so am not 100% sure what state the database gets left in. But leaving it unmerged is causing more problems now

**Comment by axeloz** [comment]
Ooops I just deleted it all and switched back to 0.38. Sorry.

**Comment by REBELinBLUE** [comment]
No worries. Could you provide the your PHP config file, maybe php-fpm config if you are using that and your Apache or Nginx config? Maybe I can figure out why $_ENV is empty during migrations for some people and then I would be able to recreate the issue 🤔
