### ISSUE TITLE
Redirect /login 404 not found

### ISSUE THREAD

**Issue by TomCamin** [REBELinBLUE/deployer#282]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Steps to reproduce

Find all command that i have execute : https://gist.github.com/TomCamin/2d93832b7ef1cd25191803ede9a2fbc6

### Environment info
Operating System: CEST 2016 x86_64 GNU/Linux - Debian 8.6
PHP Version: PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28) Zend Engine v2.6.0, with Zend OPcache v7.0.6-dev
Node Version: v6.9.1
Database System: mysql
Database Version: 5.5.52-0+deb8u1 (Debian)

### Logs (see storage/logs/) or other output that would be helpful
To check the bug : http://ks3367462.kimsufi.com

I have a problem to install deployer on debian server. All the install works but when i try to test the redirect to login is an 404 Not found error. I haven't any log of error in (/var/log/apache or in storage/log).
I have try to install many times but nothing :/ 

Thanks a lot to help me!

**Comment by REBELinBLUE** [comment]
You need to enable the `mod_rewrite` module in Apache

On debian you can do this with

```shell 
$ sudo a2enmod rewrite
$ sudo service apache2 restart
```

**Comment by TomCamin** [comment]
Thanks a lot it's works :)
