### ISSUE TITLE
404 Not Found after fresh installation of version 0.0.38

### ISSUE THREAD

**Issue by oitsem099** [REBELinBLUE/deployer#283]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ ] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Would load normally after fresh installation

### Actual behaviour

All I see is 404 Not Found - on deployer.app/login
url is deployer.app

### Steps to reproduce

cloned the latest version
checkout on version 0.0.38
followed the instructions properly
everything was successful but when I load it its giving me this error 404 not found.
permission on my /var/www/deployer is www-data:www-data.
all my other laravel projects are just running fine.

### Environment info
Operating System: Ubuntu 16.10
PHP Version: 7.0.8
Node Version: 6.9.1
Database System: 
Database Version: 10.0.25-MariaDB-1 - Ubuntu 16.10

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
Are you using Apache? If so, same as https://github.com/REBELinBLUE/deployer/issues/282 you need to enable `mod_rewrite`

**Comment by oitsem099** [comment]
yalloow @REBELinBLUE yes I'm using Apache2 and mod_rewrite is enabled.
all my other laravel projects are just fine.

**Comment by REBELinBLUE** [comment]
Hmm, that is odd, it is just a standard laravel application, I haven't modified the `.htaccess` file in any way. Is there anything in the Apache error log?

**Comment by REBELinBLUE** [comment]
Were you able to check the error log?

**Comment by REBELinBLUE** [comment]
Closing for now, feel free to reopen it
