### ISSUE TITLE
git requests password when cloning during deployment

### ISSUE THREAD

**Issue by Balgor** [REBELinBLUE/deployer#285]
### Expected behaviour

Connect to BitBucket using private/public key and clone a repo

### Actual behaviour

Deployment process hangs at deploying stage. When examining queue daemon (by running it in shell directly) when deployment starts there is "Password:" prompt that hangs indefinitely

Based on logs GIT_SSH is being exported and private and public keys are set (in Deployer and on Bitbucket). 

### Environment info
Operating System: Centos 6.8
PHP Version: 7
Node Version: 0.10.46
Database System: mysql
Database Version: 14.14

**Comment by REBELinBLUE** [comment]
Do you have a password on your private key? 

Stephen Ball
stephen@rebelinblue.com

**Comment by Balgor** [comment]
Nope, made extra sure that it's password less. Same issue persist even if i let deployer generate the keypair by itself

**Comment by Balgor** [comment]
I resolved the issue.

Problem was at specific restriction settings for ssh at my server.

Solved

**Comment by REBELinBLUE** [comment]
Ah, glad it was solved :)
