### ISSUE TITLE
Webhook - events to trigger

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#288]
Hello, 

I'm using Webhooks to trigger deployments but there are something that I don't understand and/or could be improved according to me : 

I'm using Gitea (fork of Gogs). In Gitea, I may choose what event does trigger the webhook (push, pull request, ...) but without more settings, meaning that any push or any pull request (new, modified, accepted, merged) **on any branch** will trigger the webhook and therefore the deployment. This doesn't work for me (and I guess for many others) as it should (according to me) run deployments on the master branch only (which is supposed to be stable, right?), maybe only when a PR is merged. Gitea doesn't offer such option...

Concerning the Deployer, I'm more surprised. I have a project who deploys the "master" branch and only the "master" branch (defined in the project settings). However, when receiving a webhook for a push on the "dev" branch, the deployer starts a deployment (of the master branch of course). 

My guess would be : 
* the deployer should not deploy if the webhook doesn't concern the current branch
* the deployer could have options to filter the kind of webhook that will trigger the deployment. For instance : push on a given branch, PR on a given branch, PR merged, ...

Or is there something I didn't understand? Is there a better way to handle the webhook?

Thanks

Axel

**Comment by REBELinBLUE** [comment]
Deployer doesn't currently understand the Gogs (and presumably by extension Gitea) data which is posted to the web hook so it processes all requests to the webhook, and because it doesn't know the branch it trigger a deployment of the default branch.

I have a ticket to work on it but I have not had time yet unfortunately.

https://github.com/REBELinBLUE/deployer/issues/261

**Comment by axeloz** [comment]
OK I understand now. I was surprised the webhook could trigger a deploy for any branch. 
So you confirm : if my project on deployer is set to use the master branch, the deployer should parse the webhook request and react only if the event concerns the master branch?

**Comment by axeloz** [comment]
Also, on Gitea, I can choose JSON or form-urlencoded webhooks. Should the deployer be able to understand both ?

**Comment by axeloz** [comment]
Actually, it works fine when selecting "form-urlencoded". Workflow:

* I set a webhook in Gitea for pushes only
* I push in my "dev" branch => no deployment
* I create a pull request from "dev" to "master" => no deployment
* I accept the PR, "dev" is merged to "master" => a deployment starts

So this looks pretty good to me...
Doesn't it?

**Comment by axeloz** [comment]
Erratum : doesn't work, deploy is started even if I push in "dev". I will have a look and try to provide a PR.

**Comment by REBELinBLUE** [comment]
It should just be a case of adding a class to https://github.com/REBELinBLUE/deployer/tree/master/app/Http/Webhooks to parse the data and adding it to this array https://github.com/REBELinBLUE/deployer/blob/master/app/Http/Controllers/WebhookController.php#L25-L30 if not I'll try and have a look on sunday

**Comment by REBELinBLUE** [comment]
Had a quick look at gogs, looks like it might be the same format as the github data so it should just be a case of updating the `isRequestOrigin` method in the github webhook. At work right now so can't test it but if it contains a header which can be used that makes it easier.

One thing I should add, to make it only deploy the default branch you need to add ?update_only=true to the webhook URL (see the ? icon next to the webhook URL in deployer for a full description)

**Comment by REBELinBLUE** [comment]
And looking at the source of gogs https://github.com/gogits/gogs/blob/7e15ff9486cde36b76f3d39b7db23f89278acb7d/models/webhook.go#L510 there does appear to the an `X-Gogs-Event` header.

So in theory change the github.php to the following and it might work (as I said I'm at work so I don't have the ability to test right now)

```php

<?php

namespace REBELinBLUE\Deployer\Http\Webhooks;

/**
 * Class to handle integration with Github webhooks.
 */
class Github extends Webhook
{
    /**
     * Determines whether the request was from Github.
     *
     * @return bool
     */
    public function isRequestOrigin()
    {
        return ($this->request->headers->has('X-GitHub-Event') || $this->request->headers->has('X-Gogs-Event'));
    }
    /**
     * Parses the request for a push webhook body.
     *
     * @return mixed Either an array of parameters for the deployment config, or false if it is invalid.
     */
    public function handlePush()
    {
        // We only care about push events
        if ($this->request->header('X-GitHub-Event') !== 'push' && $this->request->header('X-Gogs-Event') !== 'push') {
            return false;
        }

        $payload = $this->request->json();
        // Github sends a payload when you close a pull request with a non-existent commit.
        if ($payload->has('after') && $payload->get('after') === '0000000000000000000000000000000000000000') {
            return false;
        }

        $head   = $payload->get('head_commit');
        $branch = preg_replace('#refs/(tags|heads)/#', '', $payload->get('ref'));
        return [
            'reason'          => trim($head['message']),
            'branch'          => $branch,
            'source'          => 'Github',
            'build_url'       => $head['url'],
            'commit'          => $head['id'],
            'committer'       => $head['committer']['name'],
            'committer_email' => $head['committer']['email'],
        ];
    }
}
```

**Comment by axeloz** [comment]
@REBELinBLUE actually the Github handler doesn't work because there is not "head_commit" in the Payload. I just created a new handler for Gogs/Gitea and added a PR. 
Thanks

**Comment by REBELinBLUE** [comment]
Ah yes
