### ISSUE TITLE
Try to update but error with composer install

### ISSUE THREAD

**Issue by TomCamin** [REBELinBLUE/deployer#291]
Hi,

I have try to update my projet to the last version but it's broken after lunch composer install.

### Expected behaviour

Try to update 0.0.38 to 0.0.40

### Logs (see storage/logs/) or other output that would be helpful
after : composer install -o --no-dev
```
Generating optimized autoload files
> ([ -f .env ] && php artisan optimize) || exit 0
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/deployer/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
```

**Comment by REBELinBLUE** [comment]
I've seen this before, seems to be a problem in laravel, do you have a space in any of the entries in `.env` ? If so, try quoting them

**Comment by TomCamin** [comment]
Thanks that works i don't know why but two line on the same line with space...

I have an other question but not link really about deployer. I use symfony and with deployer my project doesn't works really well.

I have the LiipImageBundle and deployer create a symbolic link between latest and the last release but the liip bundle think that the folder is in the differente place that the project.
My error is : 
`Source image invalid "....../releases/20161126154310/src/Test/TestBundle/Resources/public/img/folder/myimage.jpg" as it is outside of the defined root path `

Thanks a lot!

**Comment by REBELinBLUE** [comment]
Hmm, I don't know anything about that bundle but it looks like it resolving the symlink and using the real path.

https://github.com/liip/LiipImagineBundle#images-outside-data-root

Make you could set the `data_root` to the releases directory?

**Comment by TomCamin** [comment]
I have post on the project and just find the fix : https://github.com/liip/LiipImagineBundle/issues/826

This was because I was using symbolic links for the assets that were already in latest folder (a symbolic link too).

Really nice project Deployer! Thanks for your work!

**Comment by REBELinBLUE** [comment]
Glad you got it working :)
