### ISSUE TITLE
Always running after a deploy, when ssh to server failed!

### ISSUE THREAD

**Issue by iflamed** [REBELinBLUE/deployer#31]
![image](https://cloud.githubusercontent.com/assets/1819687/7763268/e58807c4-0070-11e5-8d58-71447c3e10be.png)

Today after i test, i found this issue! Because i chmod the server's .ssh dir to 600. So ssh is failed. And the deploy is always running.

**Comment by iflamed** [comment]
yeah, add detail photo for a deploy.

![image](https://cloud.githubusercontent.com/assets/1819687/7763289/3b4ba0d0-0071-11e5-9a74-59a314f555e1.png)

**Comment by REBELinBLUE** [comment]
Are you using the latest release or are you using master?

I believe fixed this in master a few days ago, will double check though

To clean up the DB so you can run deploys run the following SQL

UPDATE projects SET status = '3' WHERE status = '2';
UPDATE deployments SET status = '3' WHERE status = '2';

**Comment by iflamed** [comment]
I'm run in the master and the commit is #7168c4dfa17024ec6cd6ab7f0b090cc459f55341.

And it's also exists. If you ```chmod .ssh 600```, then you can replay this issue.

**Comment by REBELinBLUE** [comment]
Hmm, interesting. I just tried this and got

"Permission denied (publickey,password)." in the output

The step was marked as failed as was the deploy.

Can you share the log file from storage/logs ? Hopefully something in there will give a clue as to what is happening

Thanks

**Comment by iflamed** [comment]
I have debuged it before. Below is my step:

1. Change the target server's .ssh to 600 
2. Back to deployer then click deploy for a project.
![image](https://cloud.githubusercontent.com/assets/1819687/7770307/a2f4f710-00bf-11e5-8a46-1a1b27b821fc.png)

3. I check the laravel-2015-05-22.log but it's empty.
4. Then refresh the " Deployment Details " page. Get the page below!
![image](https://cloud.githubusercontent.com/assets/1819687/7770326/da9a52f0-00bf-11e5-804c-2ab74b4a2efd.png)

**Comment by iflamed** [comment]
```php
[2015-05-22 20:22:31] local.ERROR: exception 'RuntimeException' with message 'Unable to connect to remote server.' in /www/sites/deployer/vendor/laravelcollective/remote/src/Connection.php:232
Stack trace:
#0 /www/sites/deployer/vendor/laravelcollective/remote/src/Connection.php(107): Collective\Remote\Connection->getGateway()
#1 /www/sites/deployer/app/Commands/TestServerConnection.php(55): Collective\Remote\Connection->run(Array)
#2 [internal function]: App\Commands\TestServerConnection->handle()
#3 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(202): Illuminate\Container\Container->call(Array)
#5 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Commands\TestServerConnection))
#6 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(App\Commands\TestServerConnection))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Commands\TestServerConnection))
#8 /www/sites/deployer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(App\Commands\TestServerConnect
ion))
```

This exception log is the test connection failed reason after i changed the .ssh to 600.

**Comment by REBELinBLUE** [comment]
Even with a
