### ISSUE TITLE
WebSocket connection handshake Error 502

### ISSUE THREAD

**Issue by skeith69** [REBELinBLUE/deployer#310]
vendor-bbb4ee8bb3.js:11
WebSocket connection to 'wss://domain.com/socket.io/?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUz…oxfQ.lMfG9vaMUcLMuwiVRaD1HAy7j2s3T4z8ZQf2QPwSOUY&EIO=3&transport=websocket' failed:
Error during WebSocket handshake: Unexpected response code: 502

does anyone know how to fix this?

**Comment by REBELinBLUE** [comment]
Are you using apache or nginx?

**Comment by oitsem099** [comment]
nginx with ssl on

**Comment by oitsem099** [comment]
nevermind I fixed it. the mistake was on my nginx block file

**Comment by oitsem099** [comment]
after I change the block file upstream settings

server domain.com:6001

now its

1:1 WebSocket connection to 'wss://deployer.altimit.online/socket.io/?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUz…oxfQ.jsptkMSuw5QDVVobj3xEAWEi3JL6MWWi4Y_YCXk4-ys&EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established

and I get a 405 error posting on the webhook

**Comment by REBELinBLUE** [comment]
Glad you got the websocket working at least....

Hmm, can you post the content of your logs? from `storage/logs/`

**Comment by bbashy** [comment]
I had some problems with it (using Cloudflare for TLS). I found the following works.

.env
```
# //deployer.domain.com so it's wss:// but uses http within socket.js
SOCKET_URL=//deployer.domain.com
SOCKET_PORT=6001
```
nginx vhost
```
upstream websocket {
    server 127.0.0.1:6001;
}

server {
    listen 443 ssl http2;

    [...] // other options

    # prevents 502 Bad Gateway error
    large_client_header_buffers 8 32k;

    location /socket.io {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;

        # prevents 502 bad gateway error
        proxy_buffers 8 32k;
        proxy_buffer_size 64k;

        proxy_pass http://websocket;
        proxy_redirect off;

        # enables WS support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by oitsem099** [comment]
@bbashy thanks for your config it kinda fixed some of the bugs on deployer. but still not usable though.

like creating server and testing connection takes forever and doesn't respond

**Comment by REBELinBLUE** [comment]
uh, easiest would be to `cat storage/logs/*.log` and then copy and paste the output

**Comment by oitsem099** [comment]
http://pastebin.com/gr5faLLq

**Comment by bbashy** [comment]
Can see a few errors on that log. bootstrap/cache/compiled.php permission denied and beanstalkd connection.

**Comment by REBELinBLUE** [comment]
Hmm yeah that looks like the problem, although that is weird because the installer should warn you of that.

Did you use the `php artisan app:install` command to install Deployer or did you just run the migrations using `php artisan migrate` ?

**Comment by oitsem099** [comment]
app:install
so what should I do?

**Comment by REBELinBLUE** [comment]
Ensure beanstalkd is running

**Comment by oitsem099** [comment]
beanstalkd is running

beanstalkd.service - Simple, fast work queue
   Loaded: loaded (/lib/systemd/system/beanstalkd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-02-01 04:37:28 UTC; 1 weeks 2 days ago
     Docs: man:beanstalkd(1)
 Main PID: 2744 (beanstalkd)
    Tasks: 1
   Memory: 224.0K
      CPU: 7ms
   CGroup: /system.slice/beanstalkd.service
           └─2744 /usr/bin/beanstalkd -l 127.0.0.1 -p 11300

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by oitsem099** [comment]
here is my block file on deployer

upstream websocket {
    # If you are using SSL, make sure the upstream server name
    # corresponds to the certificate's server name(s).
    server deployer.domain.com:6001;
}

server {
    listen 80;
    server_name deployer.domain.com;
    return 301 https://$host$request_uri;
}

server {

    listen 443;

    server_name domain.com;

    root /var/www/deployer/public;

    charset utf-8;

    access_log off;
    error_log /var/log/nginx/deployer_error_log;

    sendfile off;

    client_max_body_size 100m;

    large_client_header_buffers 8 32k;

    ssl on;
    ssl_certificate fullchain.pem;
    ssl_certificate_key privkey.pem;

    location / {
        index index.php;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;

        include fastcgi_params;
	#include /etc/nginx/fastcgi.conf;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 8 32k;
    }

    location /socket.io {
	proxy_set_header X-Real-IP $remote_addr;

	# enables WS support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
	proxy_set_header X-NginX-Proxy true;

	proxy_buffers 8 32k;
	proxy_buffer_size 64k;

        # if you are using SSL, below line should be 'proxy_pass https://websocket;'
        proxy_pass https://websocket;
    }

    location ~* /\.(?!well-known\/) {
        deny all;
    }
}

**Comment by bbashy** [comment]
Try without https for the internal socket.

Change `proxy_pass https://websocket;` to `proxy_pass http://websocket;`

Change `server deployer.domain.com:6001;` to `server 127.0.0.1:6001;`

**Comment by oitsem099** [comment]
@bbashy no luck. its even worse.
can someone share their block file with me? I'll try using other configs

**Comment by bbashy** [comment]
Weird. I don't think changing the config will help if that doesn't work. Are you using any sort of proxy over the domain/server? What nginx/php versions are you running?

Have you tried without HTTPS?

**Comment by REBELinBLUE** [comment]
What do you mean by block file?

Can you change your `.env` file so that `SOCKET_URL` has the port at the end, i.e :6001.

Then run `php artisan config:clear` to clear the cached config.

That will set the web UI to connect to the websocket server directly rather than via the nginx proxy, let's see if we can rule out nginx for now.

Also, from your computer (not the server), can you try running 

`telnet deployer.domain.com 6001` 

to see if you can connect

You'll get something like

```$ telnet localhost 6001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.```

and

```$ telnet localhost 6001
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused``` 

if it doesn't

**Comment by oitsem099** [comment]
@REBELinBLUE
I will try this I will let you know.

**Comment by oitsem099** [comment]
I'm getting no response from it.

its just saying
trying ServerIPAddress

**Comment by REBELinBLUE** [comment]
That definitely sounds like the server isn't running then or the port is blocked. Can you try it from the server itself, so you use 127.0.0.1 ? That way we should be able to tell if the port is blocked

**Comment by oitsem099** [comment]
probably the port is blocked cause the server is running smoothly.

**Comment by bbashy** [comment]
You're doing telnet from the server itself, correct?

**Comment by oitsem099** [comment]
I just did try on the server I'm getting this
telnet: Unable to connect to remote host: Connection refused
127.0.0.1 6001
even without the port same response

**Comment by bbashy** [comment]
Actually, is nginx listening directly on that port @REBELinBLUE ? I've not done too much socket stuff in nginx but it basically fakes it through the stream, right?

**Comment by REBELinBLUE** [comment]
nginx isn't listening on that port, but the node socket server is (or should be) so you should be able to telnet to it if it is running

**Comment by bbashy** [comment]
True. Forgot about that part.

Here's what I see
```
$ sudo netstat -anp | grep 8443
tcp6       0      0 :::8443                 :::*                    LISTEN      12314/node
```
```
$ telnet 127.0.0.1 8443
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

**Comment by REBELinBLUE** [comment]
@oitsem099 that definitely sounds like the server isn't running. Can you run `ps aux` and paste the output, and `sudo netstat -anp | grep 6001`

**Comment by oitsem099** [comment]
the server is running I just tried again on port 80, 443, 11300 and 6379 but not on 6001

**Comment by REBELinBLUE** [comment]
Can you please provide the output of `ps aux`

**Comment by oitsem099** [comment]
@REBELinBLUE here is the output I forgot to give http://pastebin.com/MJSb9UcE

**Comment by bbashy** [comment]
Yeah, there's no node running by the looks of it?

**Comment by REBELinBLUE** [comment]
Yeah I don't see node running, nor supervisor or the queue listener

**Comment by oitsem099** [comment]
thank you for pointing that out. there was an error on my supervisor regarding my phpi.conf file.
I fixed it and restart supervisor and nginx it looks like its running normal now I THINK cause I don't see the error anymore.

but I don't know how to create to set Servers on the project hahahaha
it keeps failing the connection test on my server

**Comment by REBELinBLUE** [comment]
Have you copied the SSH key to the authorized_keys on the server?

**Comment by oitsem099** [comment]
no I haven't yet where is it located?

**Comment by bbashy** [comment]
Top right of project page

![](https://d.pr/i/ZsLJ/DcWq18tn.jpg)

**Comment by oitsem099** [comment]
I added the ssh key on the ~/.ssh/authorized_keys and on my bitbucket project repository
still no luck hahaha
my setting is

Name: MyServerName
Connect As: deploy
Host: 127.0.0.1
Port: 22
Project Path: /var/www/testing

**Comment by REBELinBLUE** [comment]
Have you definitely added to it `authorized_keys` for the user you are connecting as? I.e. in this case deploy, so `/home/deploy/.ssh/authorized_keys`

**Comment by skeith69** [comment]
sorry for the late reply yeaup I definitely added it. still connection failed

**Comment by bbashy** [comment]
@skeith69 Have you tried connecting to ssh via the local IP?

`ssh user@127.0.0.1`

**Comment by skeith69** [comment]
it says Permission denied (publickey).

**Comment by bbashy** [comment]
@skeith69 Sorry, you'll need to supply the private key from within deployer system. Can pass `-i /path/to/key`

**Comment by skeith69** [comment]
its asking me for a passphrase

**Comment by REBELinBLUE** [comment]
Uh, it shouldn't ask for the passphrase if you are using the key file. The key deployer creates is in the `private_key` column of the `projects` table

**Comment by skeith69** [comment]
sorry for the late reply @REBELinBLUE I was busy fixing other stuffs.
I got in using the private_key on the projects table.
so what do I do next?

**Comment by skeith69** [comment]
I still getting a failed status on testing connection

**Comment by skeith69** [comment]
is there a way to check where the connection is failing?

**Comment by skeith69** [comment]
I tried on my laptop lol it connects successfully..I don't know whats wrong with my server

**Comment by bbashy** [comment]
@skeith69 Have you tried a separate install of deployer?

**Comment by REBELinBLUE** [comment]
Can you check the `tail -f /var/log/auth.log` on the server you are trying to connect to at the same time as trying to connect

**Comment by skeith69** [comment]
https://pastebin.com/tBpWWvmV

this on the server trying testing connection

**Comment by REBELinBLUE** [comment]
Oh, so that looks like it is connecting successfully.

One thought, does the directory you have set in the server settings actually exist, and is it readable & writable by the user you are connecting as?

**Comment by skeith69** [comment]
I'm using ubuntu as the user so it should have permissions right?
I just added the public key of a project to the authorized_keys file and when I ssh it from my laptop it works just fine. but trying the testing connection fails

**Comment by REBELinBLUE** [comment]
the commands the server test runs can be found in `resources/scripts/TestServerConnection.sh` you could try running each of those and see if one fails.

I may have to look at adding logging for the server connection test

**Comment by skeith69** [comment]
./TestServerConnection.sh: line 3: [: too many arguments
./TestServerConnection.sh: line 7: cd: {{: No such file or directory
deploy	RunScriptLocally.sh  RunScriptOverSSH.sh  TestServerConnection.sh  tools
touch: cannot touch '{{': Permission denied
touch: cannot touch 'test_file': Permission denied
touch: cannot touch '}}': Permission denied
./TestServerConnection.sh: line 12: {{: Permission denied
chmod: cannot access '{{': No such file or directory
chmod: cannot access 'test_file': No such file or directory
chmod: cannot access '}}': No such file or directory
rm: cannot remove '{{': No such file or directory
rm: cannot remove 'test_file': No such file or directory
rm: cannot remove '}}': No such file or directory
mkdir: cannot create directory ‘{{’: Permission denied
mkdir: cannot create directory ‘test_directory’: Permission denied
mkdir: cannot create directory ‘}}’: Permission denied
touch: cannot touch '{{': Permission denied
touch: cannot touch 'test_directory': Permission denied
touch: cannot touch '}}/{{': No such file or directory
touch: cannot touch 'test_file': Permission denied
touch: cannot touch '}}': Permission denied
./TestServerConnection.sh: line 20: {{: Permission denied
chmod: cannot access '{{': No such file or directory
chmod: cannot access 'test_directory': No such file or directory
chmod: cannot access '}}/{{': No such file or directory
chmod: cannot access 'test_file': No such file or directory
chmod: cannot access '}}': No such file or directory
ls: cannot access '{{': No such file or directory
ls: cannot access 'test_directory': No such file or directory
ls: cannot access '}}/': No such file or directory

I don't get it hahaha

**Comment by REBELinBLUE** [comment]
Yeah need to replace the {{ VAR }} with the actual valued ;)

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by REBELinBLUE** [comment]
Also, you need the run the commands on the server you are testing, not the Deployer server. Essentially it uploads the script to the server and replaces the place markers with real values then runs it

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by REBELinBLUE** [comment]
Closing for now, feel free to reopen
