### ISSUE TITLE
Can't deploy using ftp

### ISSUE THREAD

**Issue by tidusvn05** [REBELinBLUE/deployer#311]
i using ftp to deploy, don't set repository & branch.
when deploy, i got this error.

✔ Executing task deploy:prepare
✔ Executing task deploy:lock
✔ Executing task deploy:release
➤ Executing task deploy:update_code
✔ Executing task deploy:failed

[RuntimeException]                                                                                         
  fatal: failed to open '/path/to/project/releases/33/objects': No such file or directory  

deploy [-p|--parallel]

Plz help me for this issue.

Thank You!

**Comment by tidusvn05** [comment]
solved.
i removed task: deploy:update_code
add using rsync to upload code.

it was worked.

**Comment by REBELinBLUE** [comment]
Sorry, I think you are looking for this project https://github.com/deployphp/deployer
