### ISSUE TITLE
Purge Old Releases Fails

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#312]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Purge old releases works without errors.

### Actual behaviour

Purge old releases fails due to:

```
rm: cannot remove ‘20160928102417/vendor/webmozart/assert/appveyor.yml’: Permission denied
```

**Comment by REBELinBLUE** [comment]
Sorry for the late reply James. Unfortunately there isn't really much that can be done about that, if files are created after the deployment or permissions are changed so that the user deployer runs as doesn't have permission it can't delete them.

However, it should finish successfully with the status "Completed with errors"

**Comment by axeloz** [comment]
Hello @REBELinBLUE, 

I have actually the same problem which I'm trying to investigate. 
Like @jbrooksuk, the deployer cannot remove some vendors files that I have never touched myself, all these were installed via a composer install command run by the deployer itself. 

It is still unclear to me why these folders and files are owned by root:root when the deployer runs with deploy:deploy but this might actually be a deployer's bug don't you think?

Thanks

Axel

**Comment by bbashy** [comment]
@axeloz Did you use sudo for doing a command that would of created files in vendor?

**Comment by axeloz** [comment]
@bbashy no, no sudo was used. Still trying to figure it out...

**Comment by bbashy** [comment]
@axeloz Very strange to why there'd be root:root folders/files within your app's files. Was clearly somehow added from a process that was owned by root... 😨

**Comment by axeloz** [comment]
Yeah I know, right?

Running deployer on :

- an Ubuntu 14.04 box
- Nginx 1.10.1 running as www-data:www-data
- PHP FPM 7.1.0 running as www-data:www-data

I just figured out something : the CRON task is running as root. Could it be it?

**Comment by bbashy** [comment]
I think if the cron is running as root and some package downloads a file from that process...maybe?

**Comment by REBELinBLUE** [comment]
yeah I suppose it could be that in theory, although none of the cronjobs should be touching the vendor folder, just files in the `storage` folder; but if one of the packages which gets loaded modifies a file that could do it.

Maybe I should change the file so it won't run without people actually setting it, I wasn't expecting people to leave it as root

**Comment by bbashy** [comment]
Yeah I've always added it to the user that is for that site.

Not sure why that file would ever be different owner/group because it's for the repo and not for the end product https://github.com/webmozart/assert/blob/master/appveyor.yml

**Comment by REBELinBLUE** [comment]
yeah that is the odd thing about that particular case

**Comment by REBELinBLUE** [comment]
Sorry, just also realised.... the deployer cron jobs are run on the machine deployer runs on not on the machine you deploy to so they won't affect the permissions on that machine, the cronjobs are all for cleaning up orphaned files in `storage`

**Comment by bbashy** [comment]
Yeah that's totally true. @axeloz is that cron based on the web server for the deployed site? Can you monitor the file from a fresh deploy?

**Comment by axeloz** [comment]
Hey, 

About the CRON, I have used the deployer documentation : 
`* * * * * root php /var/www/deployer/artisan schedule:run 1>> /dev/null 2>&1`
So clearly, the CRON is supposed to be run as root

Concerning the server, my deployer instance deploys on the very same server where it is hosted. 
But I'm still quite surprised because the command that deployer runs is supposed to be run as "deploy" which is the unix user for the deployment process (see screenshot)

![capture d ecran 2017-02-23 a 13 56 06](https://cloud.githubusercontent.com/assets/1597611/23259954/e65dfb0e-f9cf-11e6-9ec7-9e7943fa587f.png)

So I will make further testing and will let you know shortly

**Comment by axeloz** [comment]
I might have found what happened. 
The files that deployer could not delete were stored into the "shared" folder. There were actually owned by the wrong user therefore deployer could not delete them; 

However it is unclear to me why deployer tries to delete files stored in the "shared" folder via the persistent feature

**Comment by REBELinBLUE** [comment]
hmm, that is very odd. Can you turn on debugging in `.env` and then run `php artisan config:cache` then run a deploy again and upload the logs so I can see exactly which commands it is running
