### ISSUE TITLE
Migration issue to 0.0.43

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#317]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Actual behaviour

A Laravel QueryException occurs after upgrading from 0.0.40 to 0.0.43:
`Database "deployer" does not exist`

### How to fix

My .env pre-upgrade contained this setting:
`DB_TYPE=mysql`
It seems to have changed in latest Laravel release to
`DB_CONNECTION=mysql`

### Environment info
Operating System: Ubuntu
PHP Version: 7.1
Database System: MySQL

**Comment by REBELinBLUE** [comment]
Hmm, this line of `composer.json` should fix it https://github.com/REBELinBLUE/deployer/blob/master/composer.json#L91 and the `app:update` command should stop before attempting to run the migrations  https://github.com/REBELinBLUE/deployer/blob/master/app/Console/Commands/UpdateApp.php#L251

Can you confirm you have run composer install after checking out the tag?

**Comment by axeloz** [comment]
yes, I did run composer install
thanks

**Comment by REBELinBLUE** [comment]
hmm that makes no sense. 🤔 Can you try `php artisan config:clear` and then running `sed -i 's/DB_TYPE=/DB_CONNECTION=/g' .env` yourself? then run the `php artisan app:update` command

**Comment by REBELinBLUE** [comment]
oh I misunderstood, are you saying it has been changed successfully in the `.env` file?

**Comment by axeloz** [comment]
No, the .env was not changed. I have done it myself manually.

**Comment by axeloz** [comment]
@REBELinBLUE I will try to run your command when back in the office.

**Comment by axeloz** [comment]
@REBELinBLUE the sed works fine on my .env file. 
Maybe the [ -n \"$TRAVIS\" ] returned nothing and therefore the sed never ran.

**Comment by REBELinBLUE** [comment]
hmm, yeah it looks like I've done something wrong there ![](http://i.giphy.com/l0MYE0pAvRSSTyRzi.gif)

**Comment by axeloz** [comment]
Tough work, is it? :)
Good luck

**Comment by REBELinBLUE** [comment]
No comment >_< It was to stop my CI servers from running those steps

**Comment by REBELinBLUE** [comment]
hmm, a bit weird, the warning is definitely working for me

```bash
vagrant at deployer in /var/www/deployer on master ✚ 1
$ php artisan app:update

  Update not complete!

  Your .env file has a DB_TYPE key, please rename this to DB_CONNECTION and try again
```

Bit confused now

**Comment by REBELinBLUE** [comment]
I assume after running the sed command you were able to upgrade?

**Comment by axeloz** [comment]
Yes, absolutely. Thanks
