### ISSUE TITLE
Install command hanging on fresh install

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#318]
### Expected behaviour

Completion of the install command

### Actual behaviour

Hangs on whatever is at this point. Pressing enter after 10 minutes made it continue on to database migrations.
```
Writing configuration file
Generating JWT key
Generating application key
```

Pressing enter
```
Generating application key
**had to press enter here**
Running database migrations

Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
```

### Steps to reproduce

Clone and install via steps.

### Environment info
Operating System: Debian Jessie 8.7
PHP Version: 7.0.16
Node Version: 7.6.0
Database System: MariaDB
Database Version: 10.1, so MySQL 5.5 I believe

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by bbashy** [comment]
This part of the install script just hangs and doesn't generate the application key https://github.com/REBELinBLUE/deployer/blob/master/app/Console/Commands/InstallApp.php#L531-L532

I still had SomeRandomString in .env after it said it had completed.

**Comment by REBELinBLUE** [comment]
Very odd, I shall set up a debian VM and try it out

**Comment by bbashy** [comment]
Yeah strange, tried it multiple times as well.

FYI: running the `php artisan key:generate` command worked fine.

**Comment by REBELinBLUE** [comment]
ok managed to recreate the issue >_<

**Comment by REBELinBLUE** [comment]
Looks like the default environment has changed in laravel at some point so that if it isn't set it defaults to `production` rather than `local`. When running the installer the environment isn't set at first and I call `key:generate` silently so as the environment is production it waits for confirmation. Changed it to call `key:generate` with the `--force` parameter
