### ISSUE TITLE
Call to undefined function locale_get_display_name()

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#319]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Error

Next ErrorException: Call to undefined function locale_get_display_name() (View: /home/sites/deployer/resources/views/user/profile.blade.php)

### Steps to reproduce

Install from fresh and visit profile page of your user once logged in.

### Environment info
Operating System: Debian Jessie 8.7
PHP Version: 7.0.16

**Comment by REBELinBLUE** [comment]
hmm, that is interesting. I was under the impressive that it is built into PHP > 5.3 😡 I will have to look at another way to do that, for now you can just remove that function from the PHP file, it is "just" so that it displays the language name in the dropdown along with the locale code.

Would you mind sharing the output of `php -i` ?

**Comment by bbashy** [comment]
Yeah not used that function before but maybe it's something I can fix within PHP setup.

Here's the output https://d.pr/n/8Ntn/2YNFOx64.txt

**Comment by alsotop** [comment]
I believe on Ubuntu for example, you would need the (for example) `php5.6-intl` package, which installs and enables the intl extension which is disabled by default.

**Comment by bbashy** [comment]
@alsotop Works, thanks! Installed `php7.0-intl`.

**Comment by REBELinBLUE** [comment]
Ah! Of course. I shall tweak it so the function is only called if it exists
