### ISSUE TITLE
Column 'user' cannot be null on 'commands' table

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#320]
- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Expected behaviour

Save new command

### Actual behaviour

Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user' cannot be null (SQL: insert into `commands` (`name`, `user`, `target_type`, `target_id`, `script`, `step`, `optional`, `default_on`, `order`, `updated_at`, `created_at`) values (Migrate Database, , template, 1, cd {{ release_path }}

php artisan migrate --force, 6, 0, 0, 0, 2017-02-23 16:42:47, 2017-02-23 16:42:47)) in /home/sites/internal/deployer/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

![](https://d.pr/i/tSBJ/3KsCccly.jpg)

### Steps to reproduce

- Fresh install
- Add Template
- Add Command to a step

### Environment info
You know my setup :)

**Comment by REBELinBLUE** [comment]
Damn it! I bet this is because of the TrimStrings middleware in Laravel 5.4, thought I had caught all cases. Will fix it as soon as I am home from work in about 90 minutes and tag a new release

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by bbashy** [comment]
Absolutely fine! I'm just going through and reporting any issues I see.

**Comment by REBELinBLUE** [comment]
Fixed

**Comment by bbashy** [comment]
Thanks. Did you not tag it?

**Comment by REBELinBLUE** [comment]
Sorry completely forgot, didn't get home until late last night because of that stupid storm so it slipped my mind. Will do so this evening. Think I may change it so that the `master` branch is actually stable and has the JS/CSS and get rid of the `release` branch

**Comment by bbashy** [comment]
Yeah, what a storm :/ wasn't that bad South East luckily.

Sounds like a good idea.

**Comment by REBELinBLUE** [comment]
Wasn't that bad in London either, but any excuse for transport chaos! 😂
