### ISSUE TITLE
update fails

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#321]
Hello,

Since its a massive release, wanted to wait before any bugs pops out and you fix them.

and since everything looks cool now, i decided to update

but i face an issue.

when i run `php artisan app:update`

it throws
`  Please run "npm install --production" before you continue.` error

even though i ran that command multiple times.

please help

**Comment by REBELinBLUE** [comment]
Hmm, that is odd, do you get an error about node_modules/.install when running it? For now run 'touch node_modules/.install' to update the last modified time on the file

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by lorvent** [comment]
i did update through a workaround by commenting out https://github.com/REBELinBLUE/deployer/blob/master/app/Console/Commands/UpdateApp.php#L40

**Comment by lorvent** [comment]
now update is finished but in notificatons,hipchat is disabled,
do you have any idea why?

2. i have changed timezone in .env but still it shows old timezone only,
any fix for that?
