### ISSUE TITLE
Fail to deploy latest version

### ISSUE THREAD

**Issue by onesvat** [REBELinBLUE/deployer#322]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

The system should deploy latest available commit in the branch

### Actual behaviour

The system re-deploys latest deployment, after second try it deploys new version.

### Steps to reproduce

Deploy something, Commit something to repo, Wait some time, Deploy again, Deploy Again

### Environment info
Operating System: 16.04
PHP Version: 7.0
Node Version: 4.7.3
Database System: MySQL
Database Version: 5.7

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lorvent** [comment]
do you mean,
with webhooks its failing
but when you deploy manually, its working?

**Comment by onesvat** [comment]
Webhook failing too, I dont mention that. The problem is when i do manually deploy, I must do it twice time, because when the first try, it does not deploy latest version.

**Comment by REBELinBLUE** [comment]
Sounds like this is almost certainly the same issue as https://github.com/REBELinBLUE/deployer/issues/323 I am just finishing up a fix right now

**Comment by REBELinBLUE** [comment]
Can you change out branch `bug/323` and see if that works?

**Comment by REBELinBLUE** [comment]
Moving discussing to #323
