### ISSUE TITLE
Deployments failing when repository mirror needs updating

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#323]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Whenever a commit is made, it triggers webhook and deployment should be made
### Actual behaviour

Deployments failing with status "cancelled"

### Steps to reproduce

I am using self hosted gitlab,
pushing to repo.
### Environment info
Operating System:
PHP Version:
Node Version:
Database System:
Database Version:

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lorvent** [comment]
I don't think its just related to that.

yesterday i updated to latest version and after that we deployed code for more than 30 times and everytime it failed.

but when ever i make deployment manually, it works properly.

so i am suspecting its related to something else

PS: i did `config:clear` etc ... does that have any effect?

**Comment by REBELinBLUE** [comment]
Found the problem, fixing it now

**Comment by REBELinBLUE** [comment]
Can you change out branch `bug/323` and see if that works?

**Comment by lorvent** [comment]
I just tried that branch,
still its same :cry:

**Comment by REBELinBLUE** [comment]
Did you run `app:update` after pulling?

**Comment by lorvent** [comment]
my bad...

after `app:update` its working 100% fine.

You are awesome! :sparkles: :boom:

**Comment by REBELinBLUE** [comment]
Awesome! I'll get it merged in and released this evening

**Comment by lorvent** [comment]
BTW, I see that you added many test cases....and i find it very interesting.

did you learn any book on it or any other sources you can recommend for writing test cases in laravel?

**Comment by REBELinBLUE** [comment]
Not really to be honest, just learnt through doing I'm afraid
