### ISSUE TITLE
Include the project name in the comment for the SSH key

### ISSUE THREAD

**Issue by bbashy** [REBELinBLUE/deployer#324]
Hi,

Just wondering if we can get the project name within the comment of the ssh-rsa key that's generated here for the servers: https://github.com/REBELinBLUE/deployer/blob/master/resources/scripts/tools/GenerateSSHKey.sh

I have multiple deployments within one user so I have a few in the authorized_keys file and I don't know which are which since it just has `deploy@deployer`.

Should of added comments as I added them but would be nice to have it there?

Thanks.

**Comment by REBELinBLUE** [comment]
ooh, good idea!

**Comment by REBELinBLUE** [comment]
I've rewritten the key generation to make it more testable so I can't do this quite yet as I'll just need to redo it, but I should have the refactoring merged in by the weekend then I will do this

**Comment by bbashy** [comment]
Totally fine! Thanks.

**Comment by REBELinBLUE** [comment]
This is now in master, would you mind checking it out? Working OK for me

**Comment by bbashy** [comment]
Works! Wouldn't mind keeping `deployer` in there would you?

Or something along the lines of
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDKOrBZiw6UCvCkj6xXmI69qHnsoa3LY6MUKX3ETmzZX5+oHlyDG2GYIIawwaBp4FtxCHFluq2u+rql4rhg+bZR4Lh5AvJkTpxLddZfuMJe/2HVDrxW2BIhErtX18yQnsRyxii4aLDDLWKlzS8kEPbtlFp547I4r/CuIQA1OsCzAQ== worker@deployer - ProjectName
```

**Comment by REBELinBLUE** [comment]
Makes sense, I will do that

**Comment by REBELinBLUE** [comment]
Done
