### ISSUE TITLE
Webhook deployments are cancelled

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#326]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Expected behaviour

When pushing on the master branch on our GITEA instance, the deployer should start a deployment until the end of the process.

### Actual behaviour

The push triggers the deployment but it fails. When checking the detail, I can see "Cancelled". 

GITEA knows the deployment has properly started

![capture d ecran 2017-03-01 a 15 34 16](https://cloud.githubusercontent.com/assets/1597611/23464454/564a4f52-fe95-11e6-8d59-b0ea1983a448.png)

The deployment has failed

![capture d ecran 2017-03-01 a 15 34 30](https://cloud.githubusercontent.com/assets/1597611/23464472/645841d0-fe95-11e6-9639-edb4c450e369.png)

In the deployment details, I can see that it's cancelled.

![capture d ecran 2017-03-01 a 15 35 25](https://cloud.githubusercontent.com/assets/1597611/23464489/77d772da-fe95-11e6-9d07-8dfb9c70b37a.png)

Strangely, if I click on the "Test Webhook" button in GITEA, the deployment starts and succeeds 

### Steps to reproduce

Push on GITEA with Webhook set

**Comment by REBELinBLUE** [comment]
Are you running 0.0.44? This sounds like this issue https://github.com/REBELinBLUE/deployer/issues/323 ?

**Comment by axeloz** [comment]
My very bad, I was down to 0.0.43, seems fixed now, thanks.

But this may raise a new potential issue : Deployer did not warn me about the 0.0.44 release unlike the other releases. That's why I didn't upgrade.
Thanks again,

**Comment by REBELinBLUE** [comment]
Hmm, that is odd. I have Laravel caching the response so it will only check once a day or so but it has been several days now
