### ISSUE TITLE
Wrong source in automatic deployment

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#334]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Expected behaviour

The deployment is started via a GITEA webhook whose payload URL is:

![capture_d ecran_2017-03-09_a_14_53_17](https://cloud.githubusercontent.com/assets/1597611/23753152/a6f136e8-04d8-11e7-9374-166dfbe3a8c5.png)

The source should be `gitea` on the deployer project page.

### Actual behaviour

The deployer shows actually `github` as source.

![capture d ecran 2017-03-09 a 14 53 07](https://cloud.githubusercontent.com/assets/1597611/23753184/c48df8ee-04d8-11e7-9ba7-b68bd7a8caff.png)

**Comment by REBELinBLUE** [comment]
Gitea matches the GitHub webhook so doesn't use the Source query string parameter

Currently it is only used for requests which don't match one of the "known" web hooks https://github.com/REBELinBLUE/deployer/blob/master/app/Services/Webhooks/Custom.php#L32-L38 I guess I could change it so that it uses it if set 🤔

**Comment by axeloz** [comment]
Gitea should match Gogs as I did myself a pull request that you merged some time ago. I'm pretty sure Gitea used to match Gogs not long ago.

**Comment by axeloz** [comment]
Here is the header of Gitea's payload:

```
Request URL: https://deploy.wcie.io/deploy/LJKmBKGVY7YZzOJyHr981wFfm9j0QSdje5LOnXtXdD8j0vzdcInHGaO6YaXU?source=Gitea&url=https://git.wcie.io/agencew/maison-w&branch=master&update_only=true
Request method: POST
Content-Type: application/json
X-Github-Delivery: c3d0f67f-e9c4-4e5e-b03d-af12a6d54c04
X-Github-Event: push
X-Gogs-Delivery: c3d0f67f-e9c4-4e5e-b03d-af12a6d54c04
X-Gogs-Event: push 
```

Oooops when pasting these lines, I can see that Gitea has now 
```
X-Github-Delivery: c3d0f67f-e9c4-4e5e-b03d-af12a6d54c04
X-Github-Event: push
``` 

I wonder why they added these. I guess this is why deployer thinks this is coming from Github...

**Comment by REBELinBLUE** [comment]
Hmm, interesting. Maybe I'll change the order they run in then

**Comment by axeloz** [comment]
I think this is a regression due to Gitea, not to deployer. Sorry for the false bug report
