### ISSUE TITLE
Any plans for API?

### ISSUE THREAD

**Issue by lorvent** [REBELinBLUE/deployer#335]
Hello,

Do you have any plans to provide API for deployer? (or its already available? )

thanks

**Comment by REBELinBLUE** [comment]
Absolutely! Most of it is already technically a JSON API. It is third on my list after finishing the tests and adding key sharing

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by lorvent** [comment]
Oh Great to know that.

**Comment by robindirksen1** [comment]
@REBELinBLUE can you take a look at this issue if you have time?
