### ISSUE TITLE
Deployment failed when I do it on develop branch

### ISSUE THREAD

**Issue by SamXiao** [REBELinBLUE/deployer#338]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [Y] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [Y] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [Y] You've ran `composer install --no-dev` from the root of your installation.
- [Y] You've ran `npm install --production` from the root of your installation.
- [Y] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [Y] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Deployment failed when I try to do it on develop branch.  All steps are cancelled. But It works well when I deploy master branch
![2017-04-14 4 51 34](https://cloud.githubusercontent.com/assets/1905409/25038756/d02757a6-2132-11e7-8823-8478b6f5f635.png)

### Actual behaviour

*Please describe what you're actually seeing happen.*

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

### Environment info

Visit /admin/sysinfo on your install and click the "Get System Report" button. Paste the report here, if you can't
please provide the following instead.

Operating System: CentOS 7
PHP Version: 7.0.13
Node Version: 7.8.0
Database System: Mysql 
Database Version: 5.6

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).
my logs 
[cli-2017-04-14.log.txt](https://github.com/REBELinBLUE/deployer/files/921796/cli-2017-04-14.log.txt)

**Comment by REBELinBLUE** [comment]
This looks like this bug https://github.com/REBELinBLUE/deployer/issues/301 which happens if you try and deploy soon after setting up the project. Could you try deploying again? If it works that means that was the cause

**Comment by SamXiao** [comment]
It works! What I do is press the "refresh" button on the deploy dialog.  So this is bug #301 ?

![](https://static.dingtalk.com/media/lALOvxswPc0CNM0CTA_588_564.png_620x10000q90g.jpg)

**Comment by REBELinBLUE** [comment]
Yeah, I am working on a fix to 301. So when you press the refresh button it lets you click the blue button whilst it is still refreshing? Hmm, shouldn't do that

**Comment by SamXiao** [comment]
Sorry , What I mean is I do deploy develop branch successful after I press the "refresh" button (press "refresh" button , select "develop" branch and press "deploy" button, it works).
