### ISSUE TITLE
Succesfull deployment but project doesn't update

### ISSUE THREAD

**Issue by underthecocotree** [REBELinBLUE/deployer#346]
- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Replace the current project source with the latest release. Copy `latest/` to `/var/www/project`

### Actual behaviour

Creates a `/var/www/project/releses` folder
Creates a `/var/www/project/latest` folder

***

I am currently running a laravel application under `/var/www/project`. In that folder I have my git repo that I usually just `git pull` to update. I have set up my deployment and I see that the way it works is that it pulls it and sets it up in the `releases/` folder. Once the deployment is successful I get the `latest/` folder`

- Do I need to update my project's nginx root folder to be `/var/www/project/latest`?
- Do I need to copy the latest over the root folder `/var/www/project` as part of my deployment?
- Do I need to pull the repo in my root folder?

I am a bit confused.

I am new into the world of ci and cd. Thank you for creating this, it's amazing. I will be contributing into the wiki in the future. Thanks for the help!

Deployment commands:
![image](https://user-images.githubusercontent.com/18592003/27186877-542d24a0-51f2-11e7-90b8-f2bc88fc1354.png)

**Comment by REBELinBLUE** [comment]
Hi, yeah all you need to do is change nginx to point to `/var/www/project/latest/public`, the latest symlink will be recreated each time, no need to manually copy anything.

Basically `/var/www/project` should be an empty folder and deployer will create `releases` and the `latest` symlink. It will also create `shared` if you've set up any `Persistent Files` or `Configuration Files` on the files tab. As this is a laravel project you will want to enter `storage/` as a persistent file, and your `.env` as a configuration file

Glad to hear you find it useful, hopefully I should have some free time to continue working on it again soon!

**Comment by underthecocotree** [comment]
Perfect guidelines. Thanks again for your time.

**Comment by underthecocotree** [comment]
I have been using deployer for a while and every now and then I see that a deployment is made but the actual server is not updating the content. The `latest` folder symlinks successfully to the new release and the code is actually updated.

My setup is using nginx and php-fpm. This issue has to do with the way nginx serves the files.

Nginx

`/etc/nginx/nginx.conf`

```
http {
  disable_symlinks off;
}
```

`/etc/nginx/conf.d/default.conf`
```
location ~ \.php$ {
  include /etc/nginx/fastcgi_params;

  ...

  fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
  fastcgi_param DOCUMENT_ROOT $realpath_root;
}
```

Reference: https://serverfault.com/a/848526
