### ISSUE TITLE
Deployments stuck after php upgrade from 7.0 to 7.1

### ISSUE THREAD

**Issue by dgpro** [REBELinBLUE/deployer#348]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

The deployment should be completed successfully

### Actual behaviour

I have multiple servers deployed from one app and all of them used to work fine before ubuntu upgrade (not distro) and php upgrade from 7.0 to 7.1. All of the deployments now stuck at different stages showing "Running" icon endlessly spinning.

### Steps to reproduce

I've upgraded ubuntu server (not distribution) and upgraded php from 7.0 to 7.1

### Environment info

Visit `/admin/sysinfo` on your install and click the "Get System Report" button. Paste the report here, if you can't
please provide the following instead.

- Operating System: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-83-generic x86_64)
- PHP Version: 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
- Node Version: v6.11.1
- Database System: MySQL
- Database Version: 5.6.35-1+deb.sury.org~xenial+0.1
- Redis: v=3.2.9 jemalloc-4.0.3 bits=64
- beanstalkd: 1.10
- supervisor config exactly as in [installation docs](https://github.com/REBELinBLUE/deployer/wiki/installation)
- php max_execution_time=0 and memory_limit = -1 for both fpm and cli

### Logs (see storage/logs/) or other output that would be helpful

Failed jobs table has:
```
Illuminate\Queue\MaxAttemptsExceededException: A queued job has been attempted too many times
```
storage/logs/cli-*:
```
production.ERROR: Pheanstalk\Exception\ServerException: Server reported NOT_FOUND in /var/www/deployer/vendor/pda/pheanstalk/src/YamlResponseParser.php:36
```
[Full log](https://gist.github.com/dgpro/183a2e88f994b937cee1d1753a627220)
```
ps aux | grep deployer
root     13031  0.0  3.7 299124 38160 ?        S    13:10   0:03 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
root     13032  0.0  3.6 297012 36656 ?        S    13:10   0:03 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
root     13033  0.0  3.8 299124 38716 ?        S    13:10   0:03 php artisan queue:work --queue=deployer-default --sleep=3 --tries=1 --daemon
root     13615  0.0  3.7 299124 38416 ?        S    14:36   0:01 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
```

I've restarted all of the services (supervisor, beanstalkd, redis etc), reset queue jobs, `deployer:cleanup`. Deployer was the latest release 0.0.45, I then switched to master but no avail. 
Some servers fail on "Purge Old Releases", but when I remove old releases manually on those servers the deployments run successfully for some time but then fail again. One of the servers always fails on `gulp prod` (similar to #333 ). I've spent two days so far but still can't find solution.

Regards
Den

**Comment by REBELinBLUE** [comment]
Hmm, very odd, let me see if I can set up a VM after work tomorrow with the same setup.

When you say you upgraded PHP do you mean on the server deployer is running on, or the server it is deploying to?

**Comment by dgpro** [comment]
Hi Stephen,

Thanks for getting back to me. All the upgrades have been done to the server deployer is running from. My initial thoughts was that it's fails on long tasks, but it's randomly fails even on commands running after activating release like `artisan up` which takes 0 to 1 second but it stuck there anyway. Maybe you have any idea what should look at to help identifying the problem? If not, I can try to setup a fresh server as this issue is so random.

Regards
Den

**Comment by REBELinBLUE** [comment]
If you are running the latest release you could try running `php artisan app:debug` to enable debugging. Then restart the queue worker, there may be more in the logs then to debug with.

I am setting up a VM run now to try the same setup

**Comment by dgpro** [comment]
Hi,
Here is what I found in supervisor log when this happening:
```
INFO exited: queue_1 (terminated by SIGKILL; not expected)
INFO spawned: 'queue_1' with pid 4159
INFO success: queue_1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
But it doesn't restart Running processes and it just stuck there

**Comment by tomcoonen** [comment]
@dgpro I see the same thing here, it seems to stop (mostly) at the same step here though.
Running the command it stops at locally on the destination server, works fine.

**Comment by REBELinBLUE** [comment]
Having trouble recreating this still :|  Still working on it. Can I check, are you using the latest release or are you using the `master` branch?

**Comment by dgpro** [comment]
I'm currently on `master` but the problem started on `latest release`.
So how I understand the problem seems to be that something is killing the queue process (based on supervisor log) and when it's restarted it stuck in "Running" state, is it?

**Comment by tomcoonen** [comment]
@REBELinBLUE I'm trying to debug it now, most recent error is that the job fails for some reason:
```
Illuminate\Queue\MaxAttemptsExceededException: A queued job has been attempted too many times. The job may have previously timed out.
```

Payload:
```
stdClass Object
(
    [displayName] => REBELinBLUE\Deployer\Jobs\DeployProject
    [job] => Illuminate\Queue\CallQueuedHandler@call
    [maxTries] => 
    [timeout] => 
    [data] => stdClass Object
        (
            [commandName] => REBELinBLUE\Deployer\Jobs\DeployProject
            [command] => O:39:"REBELinBLUE\Deployer\Jobs\DeployProject":8:{s:51:"REBELinBLUE\Deployer\Jobs\DeployProjectdeployment";O:45:"Illuminate\Contracts\Database\ModelIdentifier":2:{s:5:"class";s:31:"REBELinBLUE\Deployer\Deployment";s:2:"id";i:21;}s:51:"REBELinBLUE\Deployer\Jobs\DeployProjectfilesystem";N;s:52:"REBELinBLUE\Deployer\Jobs\DeployProjectprivate_key";N;s:48:"REBELinBLUE\Deployer\Jobs\DeployProjectarchive";s:23:"1_20170727122827.tar.gz";s:10:"connection";N;s:5:"queue";N;s:5:"delay";N;s:6:"*job";N;}
        )

)
```

**Comment by tomcoonen** [comment]
It has to do something with a timeout of 60 seconds, since all deploys longer than this fail by timeout.
I set the timeout on the queue to 600 seconds, (deploy takes a bit more than 60 seconds), and they all go through.

The timeout on the queue was set to 'no timeout', but that doesn't seem to persist.

**Comment by REBELinBLUE** [comment]
Hmm, I've had deployments run for 45 minutes before with no problem. But that definitely sounds like a potential cause, I'll have a play around with the timeout

**Comment by tomcoonen** [comment]
@REBELinBLUE I've not seen this before, using Forge for this server. Seems like somehow the timeout is 60s.

**Comment by REBELinBLUE** [comment]
Can you post the content of `/etc/supervisor/supervisord.conf` and the output of `supervisord --version`

**Comment by tomcoonen** [comment]
It's version 3.20

```
[program:worker-123]
command=php /home/forge/domain.com/artisan queue:work beanstalkd --sleep=3 --daemon --quiet --tries=1 --env=production --queue="deployer-high"

process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=forge
numprocs=1
stdout_logfile=/home/forge/.forge/worker-123.log
```

**Comment by REBELinBLUE** [comment]
Sorry I meant the global `/etc/supervisor/supervisord.conf`

It'll have things like the following in

```[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket```

Want to compare it to mine, see if there is anything different in the global supervisor config which could explain it

**Comment by dgpro** [comment]
```
supervisord --version#
3.2.0
```

/etc/supervisor/supervisord.conf
```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf
```

We've had deployments run for 5 hours(!) (big database rebuild) before PHP upgrade without issues and now it fails after 60 seconds...

**Comment by REBELinBLUE** [comment]
OK, not that it is much progress yet but I can confirm I have finally managed to recreate the problem, so now to figure out what is happening.

**Comment by REBELinBLUE** [comment]
OK I think I see why, in Laravel the code to timeout the job in `src/Illuminate/Queue/Worker.php` is wrapped inside a call to `supportsAsyncSignals()`

and that function is 

```php
protected function supportsAsyncSignals()
{
    return version_compare(PHP_VERSION, '7.1.0') >= 0 &&
               extension_loaded('pcntl');
}
```

so the timeout only happens on PHP 7.1+ and if it isn't specified it defaults to 60 seconds. 

I'll play around and see if there is a way to disable it

**Comment by REBELinBLUE** [comment]
OK it seems if you add `--timeout 0` to the commands in the supervisor config it won't timeout so that is a temporary workaround.

I will look at configuring it via code as a proper solution

**Comment by dgpro** [comment]
Thank you Stephen, you are a legend!

**Comment by REBELinBLUE** [comment]
Sorry I did RideLondon yesterday and just collapsed in a heap when I got home and slept. Will sort out the new release this evening

**Comment by dgpro** [comment]
No worries, I'm ok using `master`. Well done! Cheers.
