### ISSUE TITLE
[Configuration] supervisord vs socket.js example not working

### ISSUE THREAD

**Issue by tomcoonen** [REBELinBLUE/deployer#353]
I'm trying to get supervisord to start the socket.js server but can't seem to get it to work.
Starting it in the web root by using `node socket.js` works fine.

Based on the [example](https://github.com/REBELinBLUE/deployer/blob/master/examples/supervisor.conf#L15) in this repo I created this (based on [Forge](https://forge.laravel.com)):
```
[program:daemon-123]
command=node socket.js
directory=/home/forge/domain.com
environment=HOME="/home/forge/domain.com",NODE_ENV="production"

autostart=true
autorestart=true
user=forge

redirect_stderr=true
stdout_logfile=/home/forge/.forge/daemon-123.log
```

The error when supervisord tries to start:
```
Error: Cannot find module '/socket.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

Probably someting is wrong with the paths, I tried multiple configurations, but the [example](https://github.com/REBELinBLUE/deployer/blob/master/examples/supervisor.conf#L15) supplied does not seem to be able to work?

**Comment by REBELinBLUE** [comment]
Hmm, really odd, looks absolutely fine to me. That linked config is exactly what I am using on Linode (or not provisioned by Forge).

Shouldn't be needed, but what happens if you change

```
command=node socket.js
```

to

```
command=node /home/forge/domain.com/socket.js
```

Looking at the example in https://laravel.com/docs/5.1/queues#supervisor-configuration for a forge server they are using the full path to the command rather than the directory directive to set the working directory

**Comment by tomcoonen** [comment]
@REBELinBLUE I've tried that, with and without the directory option. Same error.

**Comment by REBELinBLUE** [comment]
Just looking at an example of a similar issue someone else had with supervisor, could you try the following as the command

```
command=sh -c 'node /home/forge/domain.com/socket.js'
```

**Comment by REBELinBLUE** [comment]
@tomcoonen Did this work?

**Comment by tomcoonen** [comment]
@REBELinBLUE no this didn't work since it can't load the needed .env this way.

I got it working though now like this:
```
[program:daemon-123]
directory=/home/forge/dep.creacoon.nl/
command=node socket.js
```

**Comment by REBELinBLUE** [comment]
Glad you got it working
