### ISSUE TITLE
project names that starts with double letter causes issues like "llama"

### ISSUE THREAD

**Issue by skeith69** [REBELinBLUE/deployer#354]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

On the Project Details card area
Repository:          Skeith22/l (It should be Skeith22/llama)
Default Branch:   master
URL                     http://url

It should open the link to the repository
https://bitbucket.org/Skeith22/llama

### Actual behaviour

It just a single "l" in the uri instead of the word llama
this is the url when you click it https://bitbucket.org/Skeith22/l

### Steps to reproduce

create a repository named "llama"
then create a project and paste your repository

*NOTE the hover does say its Skeith22/llama

### Environment info

Visit `/admin/sysinfo` on your install and click the "Get System Report" button. Paste the report here, if you can't
please provide the following instead.

- Operating System: Windows 10
- PHP Version: 7.1.8
- Node Version: 6.11.0
- Database System:  phpmyadmin
- Database Version: MariaDB 10.2.2

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by REBELinBLUE** [comment]
Hmm, very odd, I just tried this with both the HTTP repository URL `https://git@bitbucket.org/Skeith22/llama.git` and the SSH URL `git@bitbucket.org:Skeith22/llama.git` and both come out exactly as expected 🤔

**Comment by REBELinBLUE** [comment]
Are you still having this issue?

**Comment by skeith69** [comment]
Yeah I still have it, it's weird and disturbing though but it doesn't
affect the system at all

**Comment by REBELinBLUE** [comment]
Very odd. Could you try typing the URL (or really just the last bit) into the project again, rather than copy and paste it? Wondering if a control character has gotten into there (although it seems unlikely as it should then impact other parts of the system)
