### ISSUE TITLE
Shared folders with the same name in different paths create one shared symlink

### ISSUE THREAD

**Issue by jamieburchell** [REBELinBLUE/deployer#356]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [X] You've ran `composer install --no-dev` from the root of your installation.
- [X] You've ran `npm install --production` from the root of your installation.
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [X] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Configuring two or more shared folders in different paths with the same name should be handled correctly.

### Actual behaviour

Creating two or more shared folders with the same name in different paths causes a single folder to be created with all symlinks pointing to it.

Consider the following special directories:

```
application/cache
httpdocs/cache
```

These are not segregated, instead they are merged together as a single symlink:

```
shared/cache
```

**Comment by jamieburchell** [comment]
Possible idea for a fix for this, use/recreate the full path within the shared folder:

```
application/cache > shared/application/cache
httpdocs/cache > shared/httpdocs/cache
```

**Comment by REBELinBLUE** [comment]
Can't believe I missed that, you are right. I will do exactly that. Unfortunately I won't have access to a computer until 19th/20th now as I am away. I will fix it as soon as I get back

**Comment by iflamed** [comment]
Hi，I don't think that is a right option! If
Someone create a new folder then what will happen!

发自 刘兵 的 iPhone

**Comment by jamieburchell** [comment]
Hi @flamed, I'm not sure what you mean. Can you demonstrate a scenario where this approach wouldn't work?

I don't feel confident that I could create a PR. I'm very new to Laravel and this project. I can see that probably the mkdir will need to have a flag to create parent folders if missing. And probably the file cp would need something similar.

**Comment by jamieburchell** [comment]
For info - having played with [Deployer](https://deployer.org/) this is how they do it

**Comment by REBELinBLUE** [comment]
Yeah I'm really not sure what you mean @iflamed 

@jamieburchell It shouldn't be a difficult change, my bigger concern is how to transition the existing shared folders people will have, I shall have to think about it

**Comment by iflamed** [comment]
sorry guys, I thought there may be a problem if people create a folder in the storeage folder. But, now, I think I was wrong! It should be work if we copy each file or folder to the shared one by one.

发自 刘兵 的 iPhone

**Comment by REBELinBLUE** [comment]
I've fixed this in https://github.com/REBELinBLUE/deployer/commit/fafc0b8ddb4ebface274e8f0f6fde5990922dd51

But I need to write a migration for existing projects before merging it
