### ISSUE TITLE
Hidden forks of yours and more

### ISSUE THREAD

**Issue by skyrpex** [REBELinBLUE/deployer#359]
Hi there!

I thought you'd like to know that there's [piplin](https://github.com/Piplin/Piplin), which looks like a refactored version of yours. It's [trending now on php](https://github.com/trending/php).

Also, I wanted to tell you that I already spent some days creating a Envoyer-like product from scratch, too. Maybe we could join forces in a future. My code isn't public yet, but I want to have a working version first. 

Have a nice day!

**Comment by REBELinBLUE** [comment]
Ooh, thanks, I'll take a look. There is also (https://github.com/fixhub/fixhub)[Fixhub]

**Comment by REBELinBLUE** [comment]
Ah, seems it is a new name for Fixhub

**Comment by iflamed** [comment]
I know that guy. He is one of my wechat contact！

发自 刘兵 的 iPhone

**Comment by bbashy** [comment]
If it really is a copy (looks like from the files), it's a bit sad if they haven't included any mention of you.

**Comment by REBELinBLUE** [comment]
There is a mention in the README, I had a bit of a word with them when it first appeared, they had also take a lot of stuff from Cachet at the time and they removed it after James had a word.

But, I am pinching some of the stuff they've done such as environments

**Comment by bbashy** [comment]
Oh I did search for your username on the README view but they've obviously just linked it as "Deployer". Didn't see that.

Yeah it does generate good things like that :)

**Comment by lianguan** [comment]
I'm sorry. I didn't think it would cause trouble for Stephen.

Just now, I've updated the readme and license files. Thank you again for the excellent code provided. Piplin is indeed based on deployer, but as you can see, I have changed a lot on the basis of deployer. I don't know if they are good or bad. Piplin chose different directions from deployer.

My statement: any of the piplin code, Stephen can put it in Deployer if he likes it. If any of my actions will displease you, please let me know.

English is not my mother tongue, if there is a lack of expression, please be more inclusive.
