### ISSUE TITLE
No forms working in Deployer web GUI

### ISSUE THREAD

**Issue by EdanBrooke** [REBELinBLUE/deployer#361]
### Expected behaviour
I should be able to add a new project with this form, and the error message should not display.

### Actual behaviour
When trying to add a new project, the form has this error state before it has ever been submitted and clicking Save does absolutely nothing. On click, no JS errors are logged in Console either.

### Steps to reproduce

•	Install Deployer on Ubuntu Server 16.04 via nginx. (this is a clean install of Deployer).
•	Navigate to the web UI, to the projects tab, and click the Add a new project button.
•	Attempt to add a new project (also does the same thing for groups, users etc.)

### Laravel Environment

- Laravel Version: 5.4.30
 - Timezone: Europe/London
 - Debug Mode: ✘
 - Storage Dir Writable: ✔
 - Cache Dir Writable: ✘
 - Decomposer Version: ^1.0
 - App Size: 35 MB
 
 ### Server Environment

 - PHP Version: 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
 - Server Software: nginx/1.10.3
 - Server OS: Linux Iggy 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64
 - Database: mysql
 - SSL Installed: ✔
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔
 - Curl Ext: ✔
 - GD Ext: ✔
 - JSON Ext: ✔
 
 ### Installed Packages & their version numbers

 - andywer/js-localization : dev-laravel-5
 - backup-manager/laravel : ^1.1
 - creativeorange/gravatar : ~1.0
 - cweagans/composer-patches : dev-master
 - doctrine/dbal : ~2.5
 - fideloper/proxy : ^3.1
 - graham-campbell/binput : ~3.3
 - graham-campbell/htmlmin : ~4.2
 - guzzlehttp/guzzle : ^6.2
 - intervention/image : ^2.3
 - laracademy/interactive-make : ^0.5.0
 - laravel-notification-channels/hipchat : ~0.2
 - laravel-notification-channels/twilio : ~1.0.2
 - laravel-notification-channels/webhook : ~1.0.2
 - laravel/framework : ^5.4
 - laravel/tinker : 1.0.*
 - lubusin/laravel-decomposer : ^1.0
 - mccool/laravel-auto-presenter : ^5.0
 - melihovv/laravel-log-viewer : ^1.2
 - michele-angioni/multi-language : 0.3
 - pda/pheanstalk : ~3.1
 - pragmarx/google2fa : ^1.0.0
 - predis/predis : ~1.0
 - tymon/jwt-auth : ~0.5
 - version/version : ^2.2
 
 ### Extra Information

 - proc_open enabled : ✔

**Comment by EdanBrooke** [comment]
![image](https://user-images.githubusercontent.com/17439456/33636530-825f80ac-da14-11e7-8b99-01c663327e79.png)

**Comment by EdanBrooke** [comment]
Console is giving me, however, this. Which seems relevant.
`TypeError: app.ProjectsTab is not a constructor`

**Comment by REBELinBLUE** [comment]
Odd, I shall investigate. Which version of Deployer are you using?

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by EdanBrooke** [comment]
It's Deployer 0.0.46.

**Comment by REBELinBLUE** [comment]
Still trying to recreate this, haven't managed to yet.

What happens if you enter `app` into chrome's console?

**Comment by EdanBrooke** [comment]
![image](https://user-images.githubusercontent.com/17439456/33724196-aab382d0-db66-11e7-9e45-e533f9e1fde6.png)

**Comment by REBELinBLUE** [comment]
Hmm, that is weird, app should have a lot more than that. Do you get the same results if doing it on other pages? I see you have errors because the websocket is not over SSL, I wonder if that is stopping the javascript from executing. I shall have to try setting up a VM with the same configuration and see if that recreates the issue

**Comment by REBELinBLUE** [comment]
Yeah, that does indeed seem to be the problem, I get the same error when I do that. Make sure `SOCKET_URL` in `.env` is pointing to HTTPS along with the `APP_URL`.

You'll want to add the certificate info as well https://github.com/REBELinBLUE/deployer/blob/master/.env.dist#L16-L19

**Comment by REBELinBLUE** [comment]
Note to self: Add a warning when this happens

**Comment by EdanBrooke** [comment]
I'll consider your comments and look at getting it fixed. Then I'll confirm.

**Comment by EdanBrooke** [comment]
Yeah, this fixed it for the most part. However, when deploying a project, the UI doesn't update as the job runs. The job does run fine, but just doesn't show on the web interface as running or completed without a manual refresh? No errors in console.

**Comment by EdanBrooke** [comment]
Not sure what the issue was but I seem to be 100% up and running now! Thanks for the help and for the awesome free product. I might contribute at some point 👍
