### ISSUE TITLE
Access denied for user 'deployer'@'localhost'

### ISSUE THREAD

**Issue by F2N** [REBELinBLUE/deployer#362]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour
Getting Deployer installed as shown in the installation guide
### Actual behaviour
I get an error after the final step of the wizard 

2018-01-18 17:01:27] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'deployer'@'localhost' (using password: YES)' in /tmp/deployer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

### Steps to reproduce

php artisan app:install
Following the installation wizard.

### Environment info

- Operating System:  FreeBSD 11.1-RELEASE-p6
- PHP Version: PHP 7.1.13
- Node Version: v8.9.3
- Database System: MariaDB
- Database Version: MariaDB 10.0.33

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).

2018-01-18 17:01:27] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'deployer'@'localhost' (using password: YES)' in /tmp/deployer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

**Comment by F2N** [comment]
Hello everyone,

This is my first install of deployer, I get stuck in the database part, after following the wizard I get the following error : 

`2018-01-18 17:01:27] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'deployer'@'localhost' (using password: YES)' in /tmp/deployer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43`

No matter what I try I always get this error, I've even tried to launch the install with the local mysql Root but each time it displays an error related to the user deployer even if I used the root account, could you please help, thanks.

**Comment by F2N** [comment]
- Deleted the database as it was created with root (even if deployer user had root privileges) it prevented it from touching the db, recreated the db with deployer user and all was good, you can mark this as solved.

**Comment by REBELinBLUE** [comment]
Hi, sorry for the delay getting back to you, been offline for the last few days. Glad you got it sorted :)
