### ISSUE TITLE
SSL configuration with no SSL key password

### ISSUE THREAD

**Issue by SimonTod** [REBELinBLUE/deployer#366]
# Problem

I am trying to configure deployer to work with let's encrypt ssl certificate.
During the installation, deployer asks for the `SSL key file`, then it absolutely wants a `SSL key password`. 
The thing is that with certbot, the certificates created don't have any password with the SSL key file.
I would like to be able to set an empty password when installing deployer but it gives me this error:
`[ERROR] A value is required.`

### Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [ ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

### installed versions

- Operating System: Ubuntu 16.04
- PHP Version: 7.0.22
- Node Version: 4.8.7
- Database System: MySQL
- Database Version: 5.7.21

**Comment by REBELinBLUE** [comment]
Sorry for the very late reply, hmm I will fix that, definitely shouldn't be like that.

Assuming you haven't already figured it out, for now enter a password and then after install edit the `.env` file to remove it, then run `php artisan config:clear`

**Comment by REBELinBLUE** [comment]
Fixed in `master`
