### ISSUE TITLE
Can't deploy / SSH keys not added

### ISSUE THREAD

**Issue by abfadil** [REBELinBLUE/deployer#368]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

The private key should be saved, but it not

### Actual behaviour

![image](https://user-images.githubusercontent.com/17857337/37357143-8d190384-26df-11e8-906f-eba1443d8797.png)

Even after adding the key it stays empty.

### Steps to reproduce

Add a private key to the project

### Laravel Environment

- Laravel Version: 5.4.30
 - Timezone: Africa/Casablanca
 - Debug Mode: ✘
 - Storage Dir Writable: ✔
 - Cache Dir Writable: ✔
 - Decomposer Version: ^1.0
 - App Size: 46 MB
 
 ### Server Environment

 - PHP Version: 7.1.13
 - Server Software: nginx/1.13.8
 - Server OS: FreeBSD centraldbvm 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017 root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
 - Database: mysql
 - SSL Installed: ✘
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔
 - Curl Ext: ✔
 - GD Ext: ✔
 - JSON Ext: ✔
 
 ### Installed Packages & their version numbers

 - andywer/js-localization : dev-laravel-5
 - backup-manager/laravel : ^1.1
 - creativeorange/gravatar : ~1.0
 - cweagans/composer-patches : dev-master
 - doctrine/dbal : ~2.5
 - fideloper/proxy : ^3.1
 - graham-campbell/binput : ~3.3
 - graham-campbell/htmlmin : ~4.2
 - guzzlehttp/guzzle : ^6.2
 - intervention/image : ^2.3
 - laracademy/interactive-make : ^0.5.0
 - laravel-notification-channels/hipchat : ~0.2
 - laravel-notification-channels/twilio : ~1.0.2
 - laravel-notification-channels/webhook : ~1.0.2
 - laravel/framework : ^5.4
 - laravel/tinker : 1.0.*
 - lubusin/laravel-decomposer : ^1.0
 - mccool/laravel-auto-presenter : ^5.0
 - melihovv/laravel-log-viewer : ^1.2
 - michele-angioni/multi-language : 0.3
 - pda/pheanstalk : ~3.1
 - pragmarx/google2fa : ^1.0.0
 - predis/predis : ~1.0
 - tymon/jwt-auth : ~0.5
 - version/version : ^2.2
 
 ### Extra Information

 - proc_open enabled : ✔

### Logs (see storage/logs/) or other output that would be helpful

[cli-2018-03-09.log](https://github.com/REBELinBLUE/deployer/files/1807910/cli-2018-03-09.log)

I can't deploy project even though the SSH connection to github repo is working fine from git-cli, also when add a key it does not show up on the project please help.

**Comment by REBELinBLUE** [comment]
The SSH key won't show in the field after saving as that would be insecure, if you look at the DB you should see it in the `private_key` field on the projects table.

However, the deploy isn't failing for you because of the key, it is failing as deployer can't find the `git` cli on the deployer server, its needs to be in `$PATH` for whatever user you have the queue listener running as.

Interesting that the installer ran though, as that checks git is in the path, are you running the worker as a different user to the one you installed as?

**Comment by REBELinBLUE** [comment]
Cleaning up, feel free to reopen if still relevant
