### ISSUE TITLE
Before & after shared directory are created / copied

### ISSUE THREAD

**Issue by fatonsopa** [REBELinBLUE/deployer#371]
I have a "public/uploads" directory which is shared to "/shared/public/uploads".

Whenever I do a new deploy, I would like to copy new/changed files from "{{release_path}}/public/uploads" to shared directory. 

Interesting enough, when I add "ls -la {{release_path}}/public/uploads" as a command before "composer install" I can see new files ex.  {{release_path}}/public/uploads/test.jpg. However, If I do this after the composer install. I don't see any new file, because the symlink has already been created and the output lists files from shared directory.

It seems like the symlinks are created between the  "Before Commands"  and  "After Commands" of "Install Composer Dependencies"

Is it possible to add a command just before the symlinks of "Persistent Files" are created? or just get the files of new release just after the installing of the composer is finished?

**Comment by fatonsopa** [comment]
Just to help you out;

In order to solve this, I need to execute a "php artisan command" which copies some files from a shared directory before the following line is executed:

<img width="877" alt="screenshot at apr 18 11-12-29 pm" src="https://user-images.githubusercontent.com/9337943/38958611-1018a7d6-435e-11e8-864f-209818db960b.png">

So, I think the command "shareFileCommands" should be executed after the "Install Composer Dependencies -> After Commands" is executed"

Thank you in advance, :)

**Comment by REBELinBLUE** [comment]
You could at it as a before install command or after clone.

The prepend/append there isn't adding them as before or after install, it is just building the entire install step script (because the amount of commands for configuration files and shared files is dynamic depending on how many you have configured). So anything you add as a before install command on the commands tab will run before them

**Comment by REBELinBLUE** [comment]
It is a bit messy but could you do a before install command to copy the files to a temp directory, and then an after install command to copy them to the destination.

Although I am slightly confused, are you saying you have files in a shared directory, i.e. uploads which as well as being changed by the application (i.e. uploading a file) can also be changed via git?

**Comment by fatonsopa** [comment]
Here is the case:

Shared files:
/public/uploads/

new files from git:
/public/uploads/test.jpg

we want to upload /public/uploads/test.jpg by executing laravel commands right after composer is installed.

Or put it differently :)

On the first time, the shared directory is deployed as it should. In other cases, when we add some new files on /public/uploads/* locally, we need these new files to be copied to /shared/public/uploads. We want to do this in order to keep the local updates reflectd online. 

Now, the only place where we can grep files of /public/uploads/* and move them to /shared/public/uploads is "After the clone" or "Before the composer i installed". However, we would like to do this by using some custom laravel commands (ex. php artisan deploy:uploads) which can only be executed after composer install is done (after laravel framework is downloaded). We are unable to do this because the path of {release_path}/public/uploads is already linked to /shared/public/uploads right after the composer is installed, and before the " After Commands" of "Install Composer Dependencies " are executed.
