### ISSUE TITLE
~ is not expanded in tar command

### ISSUE THREAD

**Issue by agentmarine** [REBELinBLUE/deployer#374]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [X] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [X] You've ran `composer install --no-dev` from the root of your installation.
- [X] You've ran `npm install --production` from the root of your installation.
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [X] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour
We normally install sites on the same server as deployer, this site is different as its installed on a new server.
Should deploy site as normal.

### Actual behaviour

Extracting...

tar (child): ~/public_html/15_20180430143750.tar.gz: Cannot open
: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

during deployment it does generate folder structure and the tar.gz file
![screen shot 2018-04-30 at 15 52 30](https://user-images.githubusercontent.com/3437134/39433765-a4f851f6-4c8e-11e8-82be-8928680be3ef.png)

### Steps to reproduce

Add a remote server, including a pre-generated SSH key provided by Deployer.

### Environment info

Visit `/admin/sysinfo` on your install and click the "Get System Report" button. Paste the report here, ### Laravel Environment

- Laravel Version: 5.4.36
 - Timezone: UTC
 - Debug Mode: ✔
 - Storage Dir Writable: ✔
 - Cache Dir Writable: ✔
 - Decomposer Version: ^1.0
 - App Size: 3 GB
 
 ### Server Environment

 - PHP Version: 7.1.16
 - Server Software: Apache
 - Server OS: Linux web3.pstheagency.com 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64
 - Database: mysql
 - SSL Installed: ✘
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔
 - Curl Ext: ✔
 - GD Ext: ✔
 - JSON Ext: ✔
 
 ### Installed Packages & their version numbers

 - andywer/js-localization : dev-laravel-5
 - backup-manager/laravel : ^1.1
 - creativeorange/gravatar : ~1.0
 - cweagans/composer-patches : dev-master
 - doctrine/dbal : ~2.5
 - fideloper/proxy : ^3.1
 - graham-campbell/binput : ~3.3
 - graham-campbell/htmlmin : ~4.2
 - guzzlehttp/guzzle : ^6.2
 - intervention/image : ^2.3
 - laracademy/interactive-make : ^0.5.0
 - laravel-notification-channels/hipchat : ~0.2
 - laravel-notification-channels/twilio : ~1.0.2
 - laravel-notification-channels/webhook : ~1.0.2
 - laravel/framework : ^5.4
 - laravel/tinker : 1.0.*
 - lubusin/laravel-decomposer : ^1.0
 - mccool/laravel-auto-presenter : ^5.0
 - melihovv/laravel-log-viewer : ^1.2
 - michele-angioni/multi-language : 0.3
 - pda/pheanstalk : ~3.1
 - pragmarx/google2fa : ^1.0.0
 - predis/predis : ~1.0
 - tymon/jwt-auth : ~0.5
 - version/version : ^2.2
 
 ### Extra Information

 - proc_open enabled : ✔

### Logs (see storage/logs/) or other output that would be helpful
(If logs are large, please upload as attachment).
[log.log](https://github.com/REBELinBLUE/deployer/files/1961021/log.log)

**Comment by REBELinBLUE** [comment]
Hmm, well this is interesting, I've never tried using ~ as the path before but it does indeed fail for me also.

Could you try using the full path for now and I will investigate further

**Comment by REBELinBLUE** [comment]
So it turns out the command doesn't work on my Mac either

```bash
$ tar -m --gunzip --verbose --extract --file=~/something.tar.gz --directory=~/tmp                                                            
tar: ~/something.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Looks like it doesn't expand the `~`
