### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by telekomcity** [REBELinBLUE/deployer#376]
To help us better understand your issue, please answer the following.

template

Open  the link to configure template commands (/admin/templates/2/commands/install)

### Actual behaviour

throwing 500 eroro

### Steps to reproduce

visit /admin/templates/2/commands/install

### Environment info
nginex
php 7.2
MySQL

**Comment by REBELinBLUE** [comment]
Can you please post the log

**Comment by REBELinBLUE** [comment]
Cleaning up as there is no response, feel free to reopen if still relevant
