### ISSUE TITLE
Create a new project is modifying an existing one

### ISSUE THREAD

**Issue by exlame** [REBELinBLUE/deployer#378]
### Expected behaviour

Create new project

### Actual behaviour

Modify an existing project instead creating a new one.

### Steps to reproduce

- Click on "Edit" button of an existing project.
- Close the window or click on "Save"
- Create a new project, without reloading page.
- Fill the form and create, it is modifying the last project instead creating a new one.

### Environment info

- Operating System: Windows 10 / Vagrant Virtual box / ubuntu/trusty64
- PHP Version: 7.0.3
- Node Version: 3.14.2
- Database System: MariaDB
- Database Version: 10.1.33

**Comment by REBELinBLUE** [comment]
Fixed in `master`
