### ISSUE TITLE
PHP fatal error on a brand new instance

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#379]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Describe the bug

When trying to create a template action, I get a Fatal exception:

```
 (3/3) ErrorException

count(): Parameter must be an array or an object that implements Countable (View: /tank/www/deployer/resources/views/commands/dialog.blade.php) (View: /tank/www/deployer/resources/views/commands/dialog.blade.php)
``` 

This is probably due to this line:
`@foreach ($project->servers as $server)`

URL is : /admin/templates/1/commands/install

### Expected behaviour

I should be able to add action to the template

### Actual behaviour

Fatal exception

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Laravel Environment

- Laravel Version: 5.4.36
 - Timezone: Europe/Paris
 - Debug Mode: ✔
 - Storage Dir Writable: ✔
 - Cache Dir Writable: ✔
 - Decomposer Version: ^1.0
 - App Size: 34 MB
 
 ### Server Environment

 - PHP Version: 7.2.5-1+ubuntu16.04.1+deb.sury.org+1
 - Server Software: nginx/1.10.3
 - Server OS: Linux dev 4.9-xxxx-std-ipv6-64 #1 SMP Tue Mar 13 18:41:47 CET 2018 x86_64
 - Database: mysql
 - SSL Installed: ✘
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔
 - Curl Ext: ✔
 - GD Ext: ✔
 - JSON Ext: ✔
 
 ### Installed Packages & their version numbers

 - andywer/js-localization : dev-laravel-5
 - backup-manager/laravel : ^1.1
 - creativeorange/gravatar : ~1.0
 - cweagans/composer-patches : ^1.6
 - doctrine/dbal : ~2.5
 - fideloper/proxy : ^3.1
 - graham-campbell/binput : ~3.3
 - htmlmin/htmlmin : ~4.5
 - guzzlehttp/guzzle : ^6.2
 - intervention/image : ^2.3
 - laracademy/interactive-make : ^1.1
 - laravel-notification-channels/hipchat : ~0.2
 - laravel-notification-channels/twilio : ~1.0.2
 - laravel-notification-channels/webhook : ~1.0.2
 - laravel/framework : ^5.4
 - laravel/tinker : 1.0.*
 - lubusin/laravel-decomposer : ^1.0
 - mccool/laravel-auto-presenter : ^5.0
 - melihovv/laravel-log-viewer : ^1.2
 - michele-angioni/multi-language : 0.3
 - pda/pheanstalk : ~3.1
 - pragmarx/google2fa : ^1.0.0
 - predis/predis : ~1.0
 - tymon/jwt-auth : ~0.5
 - rebelinblue/laravel5-zxcvbn : dev-master
 - version/version : ^2.2

**Comment by REBELinBLUE** [comment]
Hmm, that is weird, that has not changed in a long time and it is working for me, shall have to update to PHP 7.2

**Comment by REBELinBLUE** [comment]
OK confirmed on PHP 7.2

**Comment by axeloz** [comment]
thanks @REBELinBLUE sorry for giving you extra work :-)

**Comment by REBELinBLUE** [comment]
Fixed in master
