### ISSUE TITLE
installing on debian 9 with apache 2 404 error

### ISSUE THREAD

**Issue by charlesRms** [REBELinBLUE/deployer#382]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ X ] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [ X ] Ensure that you're running at least PHP 7.0.8, you can check this by running `php -v`
- [ X ] You've ran `composer install --no-dev` from the root of your installation.
- [ X ] You've ran `npm install --production` from the root of your installation.
- [ X ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ X ] You have restarted the queue listener and node socket server.

### Describe the bug
After install, deploy.mysite.com redirect to /login. i get the error 
"Not Found
The requested URL /login was not found on this server."

### Expected behaviour

the deployer beeing displayed

### Actual behaviour

Nothing, i got a 404

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*
-installing php 7.0.28
-installing MariaDB
-installing Composer
-installing redis
-installing Node.js
-installing Beanstalkd

-doing all steps in installation wiki until "Finalising setup
-running  `php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon` -> nothing happens, no error.

### Screenshots
<img width="1680" alt="pcapture d ecran 2018-06-27 a 17 00 54 copie" src="https://user-images.githubusercontent.com/40624770/41982561-0a4823d6-7a2c-11e8-97a9-3de68b530ae2.png">

### Environment info

Can't visit `/admin/sysinfo` (I get a 404 error)

- Operating System: Debian 9
- PHP Version: 7.0.28
- Node Version: 6.14.3
- Database System: MariaDB
- Database Version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

### Logs (see storage/logs/) or other output that would be helpful
nothing

**Comment by lommes** [comment]
Is mod_rewrite enabled in the webserver?

**Comment by REBELinBLUE** [comment]
Looks like you either don't have `mod_rewrite` enabled  as @lommes says, or .htaccess isn't turned on https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride

**Comment by charlesRms** [comment]
... I'm so confused, I indeed forgot to enable mod-rewrite. It's working like a charm, thank you !

**Comment by REBELinBLUE** [comment]
👍
