### ISSUE TITLE
remote server test error

### ISSUE THREAD

**Issue by charlesRms** [REBELinBLUE/deployer#383]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ X ] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [ X ] Ensure that you're running at least PHP 7.0.8, you can check this by running `php -v`
- [ X ] You've ran `composer install --no-dev` from the root of your installation.
- [ X ] You've ran `npm install --production` from the root of your installation.
- [ X ] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ X ] You have restarted the queue listener and node socket server.

### Describe the bug
I am trying to add a server to project, when testing connection, I get the following error : 
`site1
site2
site3
touch: cannot touch '2_2_testing_deployer.txt': Permission denied`
in test log

### Expected behaviour

test connection working

### Actual behaviour

I get an error

### Steps to reproduce
- configure a new server in project
- create a new user "deploy" in web server with root privileges
- creating key pair for ssh connections
-testing connection

### Environment info

Visit `/admin/sysinfo` on your install and click the "Get System Report" button. Paste the report here, 
<img width="1680" alt="capture d ecran 2018-06-29 a 10 43 04" src="https://user-images.githubusercontent.com/40624770/42082807-443fc3ec-7b89-11e8-8549-208b3769c4b5.png">

### Logs (see storage/logs/) or other output that would be helpful

```
[2018-06-29 09:42:57] production.ERROR: touch: cannot touch '2_2_testing_deployer.txt': Permission denied

[2018-06-29 09:58:56] production.ERROR: touch: cannot touch '2_2_testing_deployer.txt': Permission denied
```

**Comment by charlesRms** [comment]
solved this issue by changing ownership of /var/www/ in the remote server to "deploy" user.

**Comment by REBELinBLUE** [comment]
Don't need to change the owner, but the user you are deploying as needs to be able to read and write to the directory otherwise it obviously won't be able to deploy your code there
