### ISSUE TITLE
Remember me feature broken when 2FA enabled

### ISSUE THREAD

**Issue by axeloz** [REBELinBLUE/deployer#387]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 7.0.8, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

### Describe the bug

When 2FA is enabled, the "remember me" feature is broken. 

I checked the source code, I noticed a variable naming bug.  Easy to fix. 

```
// LoginController.php line 105
if ($auth->user()->has_two_factor_authentication) {
	$this->session->put('2fa_user_id', $auth->user()->id);
	$this->session->put('2fa_remember', $request->has('remember'));
}
```
And 

```
// LoginController.php line 146
$remember = $this->session->pull('2fa_login_remember');
```

It's saved into the session as `2fa_remember` and gathered as `2fa_login_remember`

I could fix it myself via a pull request but I'd better wait you merge first otherwise I fear there will be many conflicts right?

Thanks

**Comment by REBELinBLUE** [comment]
Hmm, good catch!

**Comment by REBELinBLUE** [comment]
Fix merged
