### ISSUE TITLE
Installation not possible due to "Redis not running"

### ISSUE THREAD

**Issue by MCStreetguy** [REBELinBLUE/deployer#395]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 7.0.8, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [ ] You have restarted the queue listener and node socket server.

### Describe the bug

I want to install this tool on our server. I've maked sure about all prerequisites.
Now wenn I execute `php artisan app:install` it tells me:
> Redis is not running
> Deployer cannot be installed ...

We have a Redis instance running on a different one of our vHosts for a long time, due to the recommendation not to run Redis on the same server as the applications accessing it.
Deployer only seems to check the current host and doesn't even give me the possibility to define an external Redis connection. I also couldn't find anything about it in the wiki.
We have the `redis-tools` package installed, so connecting to the Redis instance from the vHost where Deployer runs is possible.

### Expected behaviour

It should be possible to install Deployer without having to install Redis along with it on the same server.

### Actual behaviour

As already mentioned, it is not possible to do so.

### Steps to reproduce

1. Follow the installation guide of Deployer on a system without a running `redis-server`

### Screenshots

![image](https://user-images.githubusercontent.com/8970747/46809663-422b5480-cd6f-11e8-90a5-00da2f58fc7f.png)

### Environment info

- Operating System: Ubuntu 14.04.5 LTS, Trusty Tahr
- PHP Version: 7.1.20-1+ubuntu14.04.1+deb.sury.org+1
- Node Version: v8.12.0
- Database System: MySQL
- Database Version: Ver 14.14 Distrib 5.6.27-76.0

**Comment by MCStreetguy** [comment]
I have unfortunately encountered countless other problems on a test installation on another server, which is why I have finally given up trying to install Deployer. What a pity, the tool is really exactly what I need, but obviously it doesn't work at all. Maybe I'll keep an eye on it and try it again if it's stable somehow.

**Comment by REBELinBLUE** [comment]
Hmm that is a good point, can't believe I'd never thought about that. You can get around it by setting the `REDIS_HOST` in the `.env.example` before starting the installation.

What other issues have you encountered? It works fine for lots of other people so "obviously it doesn't work at all" is completely wrong but I can't help you and/or fix whatever issue you are having if I don't know what it is
