### ISSUE TITLE
synatx error in dockerfile: apt-get missing sub command

### ISSUE THREAD

**Issue by maoxuner** [REBELinBLUE/deployer#403]
### Describe the bug

Error when build docker/php-fpm
```
E: Invalid operation ssh
```

missing `install` command in [Dockerfile line 10](https://github.com/REBELinBLUE/deployer/blob/master/docker/php-fpm/Dockerfile)
```
&& apt-get -y ssh \
```
It should be
```
&& apt-get -y install ssh \
```

### Steps to reproduce

current commit of master
```
cd docker/php-fpm
docker build . -t php-fpm
```

**Comment by REBELinBLUE** [comment]
Fixed
