### ISSUE TITLE
Deployer need a logo or favicon .

### ISSUE THREAD

**Issue by iflamed** [REBELinBLUE/deployer#41]
It's weird. In my chrome, it's show like this used the google's favicon. 
![image](https://cloud.githubusercontent.com/assets/1819687/7842467/cafc4ffa-04d5-11e5-8e5e-a6871bc91f29.png)

**Comment by REBELinBLUE** [comment]
Oh, I thought that was just my browser doing that! Will have to try and bug one of the designers at work, see if they can knock something up

**Comment by jbrooksuk** [comment]
I'm seeing a favicon?

![image](https://cloud.githubusercontent.com/assets/246103/8847456/c62f8a28-3126-11e5-8f61-aa82bc4982bd.png)

**Comment by REBELinBLUE** [comment]
Yeah I added that one as a temporary icon using with of the font-awesome icons, keep meaning to bug the designers at work for a proper one

**Comment by jbrooksuk** [comment]
:+1:
