### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [REBELinBLUE/deployer#423]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by REBELinBLUE** [comment]
I shall do so this evening

-----------------
Stephen Ball
***@***.***

**Comment by REBELinBLUE** [comment]
I have added a SECURITY.md with my contact information as requested. Thanks

**Comment by REBELinBLUE** [comment]
Thanks, I have received your report. I will put a summary here

Like this comment https://github.com/lovell/sharp/issues/2782#issuecomment-874260229 I have to ask, are these reports checked by humans?

> Visit https://github.com/REBELinBLUE/deployer/blob/master/database/seeds/ConfigFileTableSeeder.php#L32-L37 for the exposed database usernames and passwords and https://github.com/REBELinBLUE/deployer/blob/master/database/seeds/ConfigFileTableSeeder.php#L27 for JWT_SECRET token
> 
> This vulnerability is capable of information disclosure

The report can be summarised as "an example configuration file includes example credentials". I'm really not sure how else to respond to that except with

![](https://media.giphy.com/media/kc0kqKNFu7v35gPkwB/giphy.gif)
