### ISSUE TITLE
Use StyleCI for code standards

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#75]
I noticed you're using PHPCS to check standards. I'm part of the team who run [StyleCI](https://styleci.io) which uses PHP-CS-Fixer. It's worth checking out :)

**Comment by vinkla** [comment]
:+1:

**Comment by REBELinBLUE** [comment]
I do keep meaning to take a look at it, currently using https://github.com/Block8/PHPCI just set up to run PHPCS and PHPMD

**Comment by jbrooksuk** [comment]
You'll love StyleCI :)

**Comment by vinkla** [comment]
It is very easy to setup, works almost out of the box. Just have to enable the repository once logged in.

**Comment by jbrooksuk** [comment]
And, since you're using PSR-2, set the preset. It's what I did to make the PR you just merged :)
