### ISSUE TITLE
User levels

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#77]
It's possible that you may not want people adding a server or a new project, only being able to deploy and manage a site.

**Comment by REBELinBLUE** [comment]
I am thinking of doing something like gitlab, a series of predefined levels like

- Viewer - Can view the details of a project/deployments but not do anything
- Deployer - Can view a project and run deployments (view SSH key or not?)
- Administrator - Can manage servers, commands etc within projects (maybe manage projects but not groups?)
- Master - Can do everything

Viewer/Deployer/Administrator could be defined per user on a per group basis, or a per project basis.

Not sure yet, still thinking about it and playing with laravel's new authorization feature

**Comment by REBELinBLUE** [comment]
Moved to #267
