### ISSUE TITLE
Rollback deploys

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#8]
Implement the deployment rollback as the button is there but doesn't do anything

**Comment by iflamed** [comment]
Any suggestions about the rollback? It's seem to that just rollback the code is secure. Database or some user upload file should not be rollback.

So may be just create a soft link file back to the specific revision is enough.

**Comment by REBELinBLUE** [comment]
Yeah essentially all I was going to do is repoint the symlink to the release. As you said there is no easy way to automatically rollback a deployment completely due to DB migrations etc

**Comment by REBELinBLUE** [comment]
I think rather than simply re-creating a symlink it will need to essentially do a redeploy of a specific commit, which should be possible once I implement #49

**Comment by iflamed** [comment]
I still think redeploy is not a secure way to rollback. It will run some command of the deploy, and do some job we don't know. Maybe there is no redeploy, it's just deploy a specific commit.

**Comment by iflamed** [comment]
@REBELinBLUE  May I was wrong. I see the [dploy.io](http://support.dploy.io/customer/portal/articles/1302283-how-do-i-rollback-a-deployment-?b_id=527) do rollback by create a new deployment.

**Comment by REBELinBLUE** [comment]
Being addressed as part of #129
