### ISSUE TITLE
Run through StyleCI

### ISSUE THREAD

**Issue by jbrooksuk** [REBELinBLUE/deployer#82]
I know currently you use Deployer-CIBot to comment on code written incorrectly about standards. How about using https://styleci.io which not only produces a patch file for you to apply, it also integrates directly into GitHub's statuses but can also open a PR containing the fixed code for you.

**Comment by vinkla** [comment]
:+1:

**Comment by REBELinBLUE** [comment]
Duplicate of #75

**Comment by jbrooksuk** [comment]
Oh haha!

**Comment by jbrooksuk** [comment]
I thought I'd opened an issue about this before :)

**Comment by REBELinBLUE** [comment]
Ha ha, no problem. I was right that I had actually tried StyleCI before, but hadn't actually looked at the documentation much so had not figured out how to change it to psr-2 which I have now done.

**Comment by jbrooksuk** [comment]
Ah yes, we recently re-released the StyleCI service with extra documentation! :)

**Comment by REBELinBLUE** [comment]
Don't suppose StyleCI offers the badges in different styles does it, i.e. flat rather than flat squared

**Comment by REBELinBLUE** [comment]
i.e. [https://img.shields.io/badge/StyleCI-passed-green.svg]

**Comment by jbrooksuk** [comment]
Oh, not styles I'm afraid. I'll look into adding that though.

**Comment by jbrooksuk** [comment]
I lied, we do; `https://styleci.io/repos/33559148/shield?style=plastic`

**Comment by REBELinBLUE** [comment]
Fair enough, just wondered :)

**Comment by REBELinBLUE** [comment]
ah

**Comment by jbrooksuk** [comment]
![Shield!](https://styleci.io/repos/33559148/shield?style=plastic)

**Comment by REBELinBLUE** [comment]
![Shield!](https://styleci.io/repos/33559148/shield?style=flat)

**Comment by REBELinBLUE** [comment]
Perfect, thanks
