### ISSUE TITLE
Error if GD is missing

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#85]
Add ext-gd or imagemagick to composer.json so you get an error if GD is missing

**Comment by REBELinBLUE** [comment]
Seems this isn't possible

**Comment by jbrooksuk** [comment]
You can always use `extension_loaded`.

**Comment by REBELinBLUE** [comment]
Yeah true, I was just looking at adding "ext-gd": "*" like laravel has for ext-mbstring, but since intervention/image can use either GD or Imagemagick there is no way to do it in composer.json
