### ISSUE TITLE
Fatal error when deploy starts

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#91]
Occasionally when a deploy starts trying to load the top nav bar results in a fatal error, apparently due to to the date not being set, haven't managed to reliably recreate this yet

```
[2015-08-19 13:33:40] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function format() on null' in /var/www/deployer/storage/framework/views/24f7c47b5a44c792b7792c86153a0e59:22
Stack trace:
#0 {main}
```

line 22 is

```
<h4><?php echo e($deployment->project->name); ?> <small class="pull-right"><?php echo e(Lang::get('dashboard.started')); ?>: <?php echo e($deployment->started_at->format('g:i:s A')); ?></small></h4>
```

**Comment by jbrooksuk** [comment]
For me, the whole `deployments` row is empty of data.

![image](https://cloud.githubusercontent.com/assets/246103/10314096/e99caf68-6c4a-11e5-8d68-c908dc11412c.png)

**Comment by REBELinBLUE** [comment]
Hmm, very odd. Could you see if there is any error in the cli log?

Also, does it "just" go away. Everytime I've had this issue it works as soon as the deploy starts, I've never checked the database though as it changes to working so quickly

**Comment by jbrooksuk** [comment]
Nope, the deployment row just never gets filled in.

**Comment by REBELinBLUE** [comment]
And absolutely nothing in the log?

**Comment by REBELinBLUE** [comment]
Is there anything in `php artisan queue:failed` around the time the empty rows were created? @dancryer is having an equally strange problem occasionally when starting a new deployment and I'm wondering if they are related

**Comment by jbrooksuk** [comment]
I can't deploy anything, because none of the deployments row is properly created. I'll see what I can get for you.

**Comment by jbrooksuk** [comment]
```
+-------+------------+-------+-----------------------------------------+---------------------+
| ID    | Connection | Queue | Class                                   | Failed At           |
+-------+------------+-------+-----------------------------------------+---------------------+
| 40400 | beanstalkd | low   | mailer@handleQueuedMessage              | 2015-10-06 13:37:20 |
| 40399 | beanstalkd | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-06 11:47:44 |
| 40398 | beanstalkd | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-06 11:35:43 |
| 40397 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 11:40:58 |
| 40396 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 11:35:16 |
| 40395 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 11:27:50 |
| 40394 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 11:07:11 |
| 40393 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 10:42:30 |
| 40392 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 10:41:05 |
| 40391 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 09:48:49 |
| 40390 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 09:46:59 |
| 40389 | database   | high  | REBELinBLUE\Deployer\Jobs\DeployProject | 2015-10-05 09:06:44 |
+-------+------------+-------+-----------------------------------------+---------------------+
```

**Comment by jbrooksuk** [comment]
Right, I've flushed the queue and removed any blank rows from `deployments`. Looks to be working.

**Comment by jbrooksuk** [comment]
Looks to work now.

**Comment by jbrooksuk** [comment]
Hmm, it looks like if I setup GitHub to ping the webhook, it fails.

**Comment by REBELinBLUE** [comment]
Ah! Thanks, I shall check that out this evening (along with bitbucket and gitlab I guess). Had not actually tested it with those as it is just a URL which simply responded to a post request so shouldn't have any problems with what is posted but obviously it does

**Comment by jbrooksuk** [comment]
Thanks! Auto deploy from GitHub is the reason we started using Deployer ;)

**Comment by REBELinBLUE** [comment]
Damn, working fine for me.

Don't suppose you can check the web hook in github and send post the payload of one of the failed deploys (obviously remove anything sensitive like the URL of your webhook

**Comment by jbrooksuk** [comment]
Ah. Ok, so I've just tried it again and it works.

I **think** that this may be that I forced some outstanding migrations to finally run. All seems to be working right for now.

**Comment by REBELinBLUE** [comment]
hmm, interesting... OK I'll work on other issues for then now, but shout if it happens again

**Comment by jbrooksuk** [comment]
Mind if we keep it open for now? It's always been spontaneous.

**Comment by REBELinBLUE** [comment]
Yep no problem

**Comment by REBELinBLUE** [comment]
I believe I have discovered the problem https://github.com/REBELinBLUE/deployer/commit/41fb4ad40b19088d1573da9eb4b64e9b169ba831

So I've put a bit of a messy hack in place, what I actually need to do is figure out a way to detect if it fails to add to the queue
