### ISSUE TITLE
Persistent file permissions

### ISSUE THREAD

**Issue by REBELinBLUE** [REBELinBLUE/deployer#93]
Persistent files created via deployer are owned by the user who connects to the server, although this may not be a problem it could be if the app needs to write to that directory (for example an uploads directory). Although I'm not sure there is a way to fix this in deployer easily (the user would potentially need to be in the same group as www-data)  it may be worth adding a note to say "You may need to change the owner of the file/folder"

**Comment by iflamed** [comment]
It's best that user can set the owner and the mod of the file and the folder when create it.
