### ISSUE TITLE
support for aws codecommit.

### ISSUE THREAD

**Issue by pavankumarkatakam** [REBELinBLUE/deployer#96]
For now, when im entering my codecommit git url `ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/*` when creating project it is saying that this is not a valid git repository.

**Comment by REBELinBLUE** [comment]
Hmm, that is an interesting URL. Never used code commit before so will need to take a look, in theory it is just a case of changing the regex used to validate the URL

**Comment by pavankumarkatakam** [comment]
Yeah i have seen the code, you are checking for normal,gitlab,github and another git url formats, add this also it will be nice.

**Comment by pavankumarkatakam** [comment]
Thanks

**Comment by REBELinBLUE** [comment]
No problem
